### ISSUE TITLE
Swtichover Point

### ISSUE THREAD

**Issue by trek** [emberjs/guides#1]
We forked website at this commit https://github.com/emberjs/website/commit/4f5b06b64558054505c7fcfabe462a1e1b4030d7

We'll need to hand-apply subsequent Guide changes.

**Comment by joostdevries** [comment]
List of (potentially) blocking issues/questions: 
- [ ] Is the "switchover point" when we first deploy the guides?
- [ ] We we link "Guides" button on `emberjs.com`  to `guides.emberjs.com` at that point?
- [ ] How to map the current Guide URL's to the new ones (bookmarks, search engines).
- [ ] Fix SiftType#2 

Please add/update.

**Comment by trek** [comment]
We'd switch over after we add redirects to all current guide pages and then change the guides link to point to the new subdomain.

**Comment by ricardojmendez** [comment]
Guys, I'm not sure you've got the right Ricardo J. Méndez - I'm @ricardojmendez but not an emberjs developer.

Cheers!

**Comment by joostdevries** [comment]
sorry! reasonably sure I actually mean @locks

**Comment by ricardojmendez** [comment]
No problem, good luck!
