### ISSUE TITLE
ensure users use node 0.12 npm 2.7 or greater

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/guides#100]
I am unsure how to wordsmith this nicely, i don't want to make a mess of the new guides but we need to ensure users start with a reasonable version of node and npm, or they will suffer the minefield of older versions.

In addition, ember-cli aims to drop support for node 0.10.x shortly, as this will allow us to rely on features like `execSync` without requiring some brittle c extension.

**Comment by ToddSmithSalter** [comment]
I agree it's tricky. Linking to resources for staying up to date might be a better option, paired with "minimum system requirements". For example, specifying nvm for *nix users as a optimal experience to getting latest node and npm.

**Comment by kellysutton** [comment]
The recommendation for nvm might be a bit heavy-handed, but a simple "ember-cli requires Node 0.12.x or later" should do the trick. The fact that ember-cli will still work on 0.10.x for some time will just be a nice surprise.

**Comment by bsclifton** [comment]
The troubleshooting section has some good notes- are those not specific enough?
http://guides.emberjs.com/v1.11.0/ember-cli/#toc_troubleshooting

Writing the page, I tried to avoid getting way too specific like ember-cli.com is.  Actually, the original version had the versions in it, but all the feedback folks gave was that it was too long winded and version specific stuff could be put under troubleshooting

**Comment by bsclifton** [comment]
I seem to remember someone talking about proposing an ```ember troubleshoot``` or similar command to ember-cli that would look at the system and figure out what might be wrong with the environment (old NPM, etc)

**Comment by trek** [comment]
This is now mentioned in the guides.
