### ISSUE TITLE
[Tutorial] Autocomplete component

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1018]
See https://github.com/emberjs/guides/pull/801 for info on where this goes in an outline

**Comment by acorncom** [comment]
@rtablada were you wanting to work on this?

**Comment by mattw59** [comment]
I'm going to take this one unless somebody has already done so.

**Comment by rtablada** [comment]
@mattw59 go ahead I'm working on helpers I think

**Comment by mattw59** [comment]
@rtablada will do

**Comment by michaelrkn** [comment]
@mattw59 we're shooting to get this stuff out with 2.3, which is scheduled for the end of December. Do you think you'll be able to get to this by then?

**Comment by mattw59** [comment]
Yeah, I've gotten a start. I should have something by Monday, I think.

**Comment by michaelrkn** [comment]
Sweet!

**Comment by michaelrkn** [comment]
@mattw59 How is this coming along?

**Comment by mattw59** [comment]
Sort of slowly with the holidays. Will try to get you something to look at
tomorrow. The code is close to done.
