### ISSUE TITLE
[Tutorial] Google Maps service and component

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1019]
See https://github.com/emberjs/guides/pull/801 for where this goes in our outline

**Comment by michaelrkn** [comment]
@toddjordan You had mentioned interest in helping on the tutorial - would you be game to take this part on?

**Comment by toddjordan** [comment]
Sure!  It will probably be about a week until I can start on it, but I'd be happy to take it on.

**Comment by michaelrkn** [comment]
Sweet!

**Comment by michaelrkn** [comment]
@toddjordan How is this coming along?

**Comment by toddjordan** [comment]
I'm planning on starting this week.  @locks mentioned that these weren't going out with 2.2.

**Comment by michaelrkn** [comment]
Ah, I missed that news ;)

**Comment by toddjordan** [comment]
@locks @michaelrkn starting to look at this.  I'm assuming this fits into the fuller tutorial "Super Rentals" example?  Is there a codebase I can build this example onto?

**Comment by acorncom** [comment]
@toddjordan How's progress on this going?

**Comment by toddjordan** [comment]
Working on it.  Developing a service onto the super-rentals repo.  Been working on some other prs as well, but I'm down to this.  We can discuss at the meeting.

**Comment by acorncom** [comment]
:+1:

**Comment by toddjordan** [comment]
I'm concerned about google maps being used as a service here.  Seems more tailored for a component/utility combo.  There's not a need for a singleton available across components.  I'm looking for other ideas of potential services for super-rentals at the moment.  Shopping cart would seem logical, but its already used in the services section of the guides.  Might be good to show off something else.

**Comment by knownasilya** [comment]
I use google maps as a service, this guarantees that the map is initialized before you place it in the dom, making using it from routes possible.

**Comment by toddjordan** [comment]
I've had a pull request out on this: #1289 , but I think it actuall might be a bit much for the tutorial (it displays a map, as well as charts directions by city).  I'm going to make a second pass at this with a simple service example.

**Comment by toddjordan** [comment]
Issue #1374 is swallowing this issue up.  Tutorial stuff will be tracked there going forward.
