### ISSUE TITLE
[Tutorial] Helpers

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1020]
See https://github.com/emberjs/guides/pull/801 for where this goes in our outline

Suggested helpers

- Format currency
- Moment for formatting time?

**Comment by rtablada** [comment]
@acorncom are we using accounting.js or something else for currency?

And are we set on moment for time formatting? Seems like passing in a native date object could give us the ability to `getMinutes`, `getSeconds`, etc

**Comment by acorncom** [comment]
@rtablada As far as I know, the helpers above aren't set in stone. So if you've got other ideas for helpers that fix well with the rental idea, I think it'd be fine to use those instead.  We use monetary / currency helpers both on the writing helpers page (http://guides.emberjs.com/v2.2.0/templates/writing-helpers/) and for the actual API docs (http://emberjs.com/api/classes/Ember.Helper.html#method_helper) so it might be nice to use a different example for a change :-)

@michaelrkn Any additional thoughts here?

**Comment by michaelrkn** [comment]
@acorncom is spot on.

**Comment by michaelrkn** [comment]
Also there was an initial effort made at https://github.com/ember-denver/guides/commit/ff6c1120766f78577087570ff2440bc6f43c9d19.

**Comment by rtablada** [comment]
Ok will check.



—

**Comment by michaelrkn** [comment]
@rtablada How is this coming along?

**Comment by michaelrkn** [comment]
Just noticed/made the connection between this and your open PR.
