### ISSUE TITLE
[Tutorial] Deploying

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1022]
See https://github.com/emberjs/guides/pull/801 for where this goes in our outline

We may want to introduce barebones deploys (copying the `dist/` folder to start with) and then discuss `ember-cli-deploy` as a more advanced option

**Comment by acorncom** [comment]
Another option that has been discussed here was to deploy to Firebase

**Comment by boztek** [comment]
If the goal is to show an "easy" install and we don't mind referencing services like Firebase then surge.sh would be a possible beginners option too.

**Comment by boztek** [comment]
Are we thinking just one page with a bunch of simple deployment options?

I have an example here: https://github.com/boztek/guides/blob/1022-deploy-tutorial/source/localizable/tutorial/deploying.md

**Comment by acorncom** [comment]
@boztek Yes, that type of page was what we were thinking.  Send over a PR when you're ready and we'll mark it up! ;-)

**Comment by boztek** [comment]
Thanks @acorncom. Is there a way to run the spellcheck tester locally? Apparently ```scp``` is not in the dictionary. :smile:

**Comment by acorncom** [comment]
@boztek If I remember right, when you do a build locally (as shown here: https://github.com/emberjs/guides/blob/master/.travis.yml#L9) it should run the spelling setup automatically.  But you should be able to update this file and re-push an amended commit and have things work:

https://github.com/emberjs/guides/blob/master/data/spelling-exceptions.txt

**Comment by boztek** [comment]
@acorncom Quite right. Thanks.
