### ISSUE TITLE
[Tutorial] Upgrading

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1024]
See https://github.com/emberjs/guides/pull/801 for where this goes in our outline

**Comment by mellatone** [comment]
@acorncom what the scope of upgrading? It could end up covering a _lot_ of ground.

**Comment by acorncom** [comment]
@mellatone True that :-)

Maybe some significantly simplified version of these tutorials?

- http://www.jordanhawker.com/posts/128580938346
- http://www.jordanhawker.com/posts/128657408146
- http://www.jordanhawker.com/posts/128725196501

Or a slightly expanded version of the Ember-CLI upgrade docs?  Given this is a tutorial, the later might be a better fit with the tutorials above going in under Upgrading under the main guides ...

@michaelrkn @locks Thoughts?

**Comment by michaelrkn** [comment]
I would suggest holding off on this until CLI 2.x is released, and/or write it targeting CLI 2.x, since the process for upgrading Ember and ED will be different than 1.x (and easier).

For the tutorial, I think we should cover upgrading Ember, ED, and Ember CLI, and dealing with deprecations.

**Comment by jrhorn424** [comment]
Happy to take this when contingencies are met.

**Comment by toddjordan** [comment]
Issue #1374 is swallowing this issue up.  Tutorial stuff will be tracked there going forward.
