### ISSUE TITLE
Update core concepts image with higher quality

### ISSUE THREAD

**Issue by kimroen** [emberjs/guides#1025]
The nice new image was submitted by @alexG53090 in #987 (and originally #983), but it has a problem:

This image is of fairly low quality and doesn't look that great in practice, unfortunately - at least not on a retina screen. In use here: http://guides.emberjs.com/v2.2.0/getting-started/core-concepts/

Some possible solutions:

- Make it twice the size and serve that with width set on the `img`-tag
- Use some kind of method of serving a retina version to retina screens
- Recreate it inline with markup
- Use svg or canvas

The original files seem to be available in the original issue: #979

**Comment by michaelrkn** [comment]
@alexG53090 and I had talked about adding a folder to `source/images` called `originals` where we'd put the originals for future editing, but I think we forgot about it. Let's definitely add that folder to make this process easier in the future!

**Comment by michaelrkn** [comment]
Also just FYI it looks great on a non-retina screen. Life is tough for you retina folks! ;)

**Comment by kimroen** [comment]
The struggle is real

**Comment by alexG53090** [comment]
Hey! Thanks for the feedback! I still have all the high-quality images in every img. file type (.svg, .jpeg, .gif, .png). With proper implementation, the images should appear crystal clear on any device. I'll create a new PR with all the assets and if they get approved, I am more than happy to help with formatting, etc.

**Comment by alexG53090** [comment]
Still having trouble figuring out how to make the proper PR. In the interest of time please have these images. 

https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.jpg
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.gif
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.png
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.svg 
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.xml
https://s3-us-west-2.amazonaws.com/ember-core-concepts/ember-core-concepts-master.ai

**Comment by michaelrkn** [comment]
Thank you!!

**Comment by alexG53090** [comment]
for sure! thank you @michaelrkn for not forgetting about this project :+1:  :)
