### ISSUE TITLE
Add Analytics to tutorials

### ISSUE THREAD

**Issue by Lewiscowles1986** [emberjs/guides#1033]
So most of Google links to an incredibly old Analytics setup for Ember on your old docs, or addons for something that seems basic, and unnecessary.  

http://guides.emberjs.com/v1.10.0/cookbook/helpers_and_components/adding_google_analytics_tracking/

I would be great to add an updated tutorial.

**index.html**  
```html
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-XXXXXX', 'auto'); // Replace with your site code
  </script>
```

**app.js**  
```js
App = Ember.Application.create(); // find this

// Add this code
App.Router = Ember.Router.extend({

  didTransition: function() {
    this._super(...arguments);
    return ga('send', 'pageview', {
      'page': this.get('url'),
      'title': this.get('url')
    });
  }
});
```

**Comment by michaelrkn** [comment]
Yes, unfortunately all of our Google-juice goes to the oldest version of the Guides. We only recently came up with a [solution](https://github.com/emberjs/guides/issues/604#issuecomment-161872837) for the versioning problem; once that's in place, we can look at adding `rel="canonical"` to get Google pointing towards the latest version.

As for this particular page, it has been removed from the Guides as we decided it was out of scope. You might check out [this analytics addon](https://github.com/poteto/ember-metrics).
