### ISSUE TITLE
[Redesign] Fix responsive design issues on mobile with the new guides

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1036]
The new design is supposed to collapse as the screen size shrinks (and does on desktop screens when the browser window is shrunk), but when viewed on an iPhone the full page is shown.  We probably just need to add a screen-size meta tag to the header to trigger this

**Comment by nicholalexander** [comment]
@acorncom i was taking a look at this and a simple view port fixes the issue - but it seems like it'd be nicer to have the menu collapse into a hamburger (or slide out from the side).  Is that something you would like me to add?

**Comment by acorncom** [comment]
@nicholalexander Yes please!  Might be worth doing in two pull requests so we get the first one done while you work on the addition ...

**Comment by acorncom** [comment]
Oh, and thanks! :+1:

**Comment by steveszc** [comment]
I'll take a shot at the menu. I'll aim to submit a PR by christmas, if not sooner.

**Comment by michaelrkn** [comment]
Thanks @steveszc!

**Comment by steveszc** [comment]
Just submitted a PR to fix this: https://github.com/emberjs/guides/pull/1090
