### ISSUE TITLE
[The Object Model] - Classes and instances - description of the .create() method

### ISSUE THREAD

**Issue by gpluta** [emberjs/guides#1038]
In the guides it says:
For performance reasons, note that you ___cannot___ redefine an instance's computed properties or methods when calling create(), nor can you define new ones. You should only set simple properties...

Should it not state:
For performance reasons, note that you ___should not___ redefine...
?

Cheers,

**Comment by michaelrkn** [comment]
I'm not sure about this. @locks?

**Comment by gpluta** [comment]
The thing is that you technically CAN redefine methods and you CAN create new methods while instantiating a class using .create(). You can NOT redefine computed props (errors when trying to do so). This works just fine:

```js
let Person = Ember.Object.extend({
  say() {
      console.log(`Hello, my name is ${this.get('name')}`);
    },

    fullName: Ember.computed('name', 'surname', function() {
        return `${this.get('name')} ${this.get('surname')}`
    }),

    sayFullName() {
      console.log(`My full name is ${this.get('fullName')}`);
    }
});

let greg = Person.create({
  name: 'Greg',
  surname: 'Pluta'
  say() { //overwriting say() method
    console.log(`Hello, my name is ${this.get('name')}, and I have just overriden an instance method`);
  },
  smile() { //adding a method
    console.log(`${this.get('name')} smiled deceptively`);
  }
});

greg.say(); //logs "Hello, my name is Greg, and I have just overriden an instance method"
greg.smile(); //logs "Greg smiled deceptively"
```

Trying to overwrite a computed property throws an error, as expected.

The way this is described in the guides at the moment is a bit misleading. :)

Cheers,

**Comment by michaelrkn** [comment]
Sounds good! Will you open a PR to fix it?

**Comment by gpluta** [comment]
https://github.com/emberjs/guides/pull/1043
