### ISSUE TITLE
Something is wrong with Typekit

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#1042]
Pop open the dev console and you'll see:

> Failed to load resource: the server responded with a status of 403 (Forbidden)
> https://use.typekit.net/c/8c3c31/1w;anonymous-pro,7cdcb44be4a7db8877ffa5c00…83d2f4e2e3bfbed9187d69f62758d61841ad3c9287d12dc30209e5e71b79734cca4681ee54

**Comment by acorncom** [comment]
@wifelette Looks like this issue may be related to Tom's addition when he was working on the footer (here are the offending lines: https://github.com/emberjs/guides/blob/master/source/layout.erb#L12-L14), any ideas on why we'd be getting a 403?

>

**Comment by wifelette** [comment]
Hmm. I verified that that code snipped is correct, could be some other issue.

What's the domain we're trying to access this from? Maybe we're missing some silly variant that I need to list on the whitelist? Current list:

`emberjs.com,localhost,www.emberjs.com`

Just guessing. No idea what else might be going wrong.

**Comment by michaelrkn** [comment]
Ah, can you whitelist guides.emberjs.com?

**Comment by wifelette** [comment]
> Your new kit may take a few minutes to be completely distributed across our network.
...but it's done :)

**Comment by michaelrkn** [comment]
Thank you!! It works now for me!
