### ISSUE TITLE
Document hash helper and contextual components

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#1047]
It appears these features have landed and are in the 2.3 beta releases. Are they appropriate for inclusion in the Guides? If so, that documentation needs to be written.

/cc @Serabe @mmun @mixonic

**Comment by locks** [comment]
I'm taking the hash helper.

**Comment by rwjblue** [comment]
@locks - How is this going?

**Comment by michaelrkn** [comment]
@locks ping

**Comment by locks** [comment]
@rwjblue @michaelrkn it'll get done this week, sorry

**Comment by acorncom** [comment]
@locks Did this ever get written?

**Comment by locks** [comment]
Fixed by https://github.com/emberjs/guides/pull/1335.
