### ISSUE TITLE
[Proposal] Removal of `e.g`

### ISSUE THREAD

**Issue by rtablada** [emberjs/guides#1050]
While working through areas of the guides other than the tutorial, I have been noticing a lot of `(e.g.` usage.
I think this is a bit unapproachable for quick reading and comes off with the wrong tone.

Instead I think we should consider each `e.g` and try to replace it with a `such as` statement or similar.

**Comment by michaelrkn** [comment]
Sounds good to me!

**Comment by michaelrkn** [comment]
The one thing I'll add is that it is very difficult to enforce rules like this when we have many different contributors, especially when many of them make are one-time contributors. I've leaned towards correcting gross mistakes/style violations but not nitpicking over smaller things like this.

**Comment by rtablada** [comment]
Yup which is why sometimes it just needs a long weekend and a good pass through every so often.

**Comment by michaelrkn** [comment]
:+1:

**Comment by acorncom** [comment]
:+1:

**Comment by acorncom** [comment]
Might be worth adding to the contributing guidelines as well so if folks read them prior to contributing we don't have to do additional work ;-)

**Comment by rtablada** [comment]
I would say that it is kind of part of the "write examples" area, but that might be expanded on?

**Comment by acorncom** [comment]
I'm closing this to clear it from the tracker, but looking forward to seeing more work on this!
