### ISSUE TITLE
Remove font smoothing

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#1058]
Currently, our styles use font smoothing, which is [non-standard and should not be used](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth). This should be removed, and the styles updated so that the font still looks good. 

The relevant properties are `-webkit-font-smoothing` and `-moz-osx-font-smoothing`, and they are in `_highlight.scss`, `_typography.scss`, and `_buttons.scss`.

**Comment by michaelrkn** [comment]
@nicholalexander @josemarluedke either of you feel like you could take this on?

**Comment by nightire** [comment]
@michaelrkn I've taken this.

**Comment by jsmestad** [comment]
@michaelrkn this looks like this can be closed now that #1034 was merged.

**Comment by acorncom** [comment]
@jsmestad There's been some debate back and forth about whether to remove the font-smoothing altogether (see https://github.com/emberjs/guides/pull/1034#issuecomment-164554578)  Based on docs team discussions, we're not opposed to removing it, but would like to see the design not take a hit in the process.  And it's not an urgent priority IMO.

So would love a PR if someone wants to send one in! :-)

**Comment by locks** [comment]
Not sure this is still relevant? Make yourself heard if it is!
