### ISSUE TITLE
Add more details to the Transforms section

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/guides#1061]
@acorncom mentioned on Twitter that I could improve the transforms documentation. I'd like to include more details under the transform section of the guide Defining Models about number, boolean, and date transforms similar to my blog post. Also, maybe it'd be useful to add a guide "Creating Custom Transforms" under Models, similar to the example in my blog post.

**Comment by michaelrkn** [comment]
Awesome! Go ahead and open a PR.

**Comment by skaterdav85** [comment]
@acorncom Do you think it'd be useful adding a new guide "Creating Custom Transforms" under Models?

**Comment by acorncom** [comment]
@skaterdav85 Seems like it fits better in context on the "Defining Models" page, don't you think?  Seems like if we added another section beneath Transforms called "Custom Transforms" that that would give us the needed space.  What we might end up doing as I look at the pages would be to split out simple attributes from relationships (which could go on their own separate page).

@michaelrkn @locks Thoughts on the above?

**Comment by michaelrkn** [comment]
@acorncom sounds good to me!

**Comment by skaterdav85** [comment]
What do you think about taking the "Defining Relationships" section under Models and moving it to its own guide right before "Working with Relationships"?

**Comment by locks** [comment]
@skaterdav85 that would be a different issue

**Comment by skaterdav85** [comment]
ah yes, sorry. will open that.
