### ISSUE TITLE
Customizing Serializers enhancements

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/guides#1071]
I think it would be useful to add a couple sections to the Customizing Serializers guide for the JSONSerializer and RESTSerializer. I wrote about it in a blog post because I had a hard time finding it in the guides: http://thejsguy.com/2015/12/05/which-ember-data-serializer-should-i-use.html

What do you think?

**Comment by acorncom** [comment]
I'm a :+1: on that. I believe we've already got JSONSerializer info here: http://guides.emberjs.com/v2.2.0/models/customizing-serializers/ but not much mention of the RESTSerializer.  

locks @michaelrkn ?

**Comment by skaterdav85** [comment]
Cool, let me know when I can proceed =)

**Comment by locks** [comment]
I don't particularly care about documenting RESTSerializer, and there's your blog post already.
I believe JSONSerializer is documented in the guides because it's the base one for the others.

**Comment by skaterdav85** [comment]
I just noticed JSONSerializer in the guides. I guess I missed that before.

I think having RESTSerializer would be useful because a lot of tutorials on the web use the RESTSerializer format. For someone new to Ember, finding out this expected format can be a little frustrating. Also, since both JSONAPISerializer and JSONSerializer are documented, it seems fitting to have the other commonly used serializer in there as well. That's just my two cents. :)

**Comment by locks** [comment]
@skaterdav85 the guides aren't meant to be exhaustive. The API docs however, are a very good home for documentation about the format.

**Comment by acorncom** [comment]
Seems like what we might want to do is link these initial mentions of the serializers to the appropriate serializer api pages.  We could then improve those API docs as needed.
![screen shot 2015-12-14 at 6 18 45 pm](https://cloud.githubusercontent.com/assets/802505/11799205/23903e18-a28f-11e5-992a-c286eac53fce.png)

@skaterdav85 Would you be willing to send in a pull request for that?

**Comment by skaterdav85** [comment]
sure thing!
