### ISSUE TITLE
Removing the version from a url gives a 502

### ISSUE THREAD

**Issue by wagenet** [emberjs/guides#108]
For instance: http://guides.emberjs.com/object-model/computed-properties/

**Comment by rwjblue** [comment]
What is expected?

**Comment by wagenet** [comment]
Preferably a 404 and not a Gateway Error.

**Comment by trek** [comment]
That was probably a divshot hiccup. That link 404s right now.
![page not found 2015-03-27 13-27-54](https://cloud.githubusercontent.com/assets/9736/6874417/1a83e50a-d485-11e4-8f3f-9357c5aec0b0.png)
