### ISSUE TITLE
API missing Component's "attributeBindings"

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/guides#1084]
It's available [in the Guide](https://guides.emberjs.com/v2.2.0/components/customizing-a-components-element/#toc_customizing-attributes), however, it's not documented [in the API](http://emberjs.com/api/classes/Ember.Component.html).

**Comment by locks** [comment]
It's documented in the parent class: http://emberjs.com/api/classes/Ember.View.html#toc_html-attributes.
I believe the course of action is to open an issue with emberjs/ember.js instead. cc @rwjblue

**Comment by acorncom** [comment]
Closing this, as it's an API docs issue.  @tsteuwer if you can open an issue over there, that'd be great!
