### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by jrhorn424** [emberjs/guides#1092]
See https://github.com/emberjs/website/issues/2126

I initially wanted to help update Twiddles, but since the guides are moving away from Twiddles, I'm happy to make myself useful in other ways. 😄

**Comment by rtablada** [comment]
@jrhorn424 stick your head in #documentation on Slack and we'll be able to talk more. Github isn't a great forum for longer discussions.

**Comment by michaelrkn** [comment]
Thanks for your interest, @jrhorn424! Check out an [issues tagged with "Help Wanted"](https://github.com/emberjs/guides/labels/help%20wanted).

**Comment by jrhorn424** [comment]
Thanks @rtablada and @michaelrkn!
