### ISSUE TITLE
[Tutorial] Nested routes

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#1100]
We need a page in the tutorial that explains nested routes, including `index` routes and the `application` route.

**Comment by filipecrosk** [comment]
Hi @michaelrkn, I can do this. Just a question, is there a guide/format to write these tutorials?
I think I'll need to cover these:
- Action Bubbling
- Alias 
- Templates structure/directories

**Comment by locks** [comment]
@filipecrosk what do you mean by action bubbling? you should be using closure actions as much as possible.

**Comment by filipecrosk** [comment]
@locks you right, my bad.

**Comment by locks** [comment]
@filipecrosk no problem! just trying to clear things out to avoid unnecessary work on your part :smile:

**Comment by michaelrkn** [comment]
@filipecrosk Thanks for your interest in helping out! Just to warn you, we have a much higher bar for the tutorial content than other parts of the Guides, so be prepared for a lot of feedback and back-and-forth. I'd strongly suggest opening a PR as soon as possible after you start so you can immediately get pointed in the right direction.

As far as format, start by reading the [contributing guidelines](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md), including the style guide. Then go through the [existing sections of the tutorial](https://guides.emberjs.com/v2.2.0/tutorial/routes-and-templates/) to see the writing style and think about where this page could fit in.

**Comment by toddjordan** [comment]
Issue #1374 is swallowing this issue up.  Tutorial stuff will be tracked there going forward.
