### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#1101]
This moves https://github.com/emberjs/website/issues/2311 over to the proper repo. All of the below content is from @wycats:

To make it possible to do documentation work for features that have not yet landed, we should have a feature-flag infrastructure in guides.

For example, you could imagine:

```
<feature-flag feature="ember-htmlbars-component-generation">
All of the new docs here.
</feature-flag>

<feature-flag not-feature="ember-htmlbars-component-generation">
All of the old docs here.
</feature-flag>
```

An alternative approach would be to preprocess the guides with Handlebars, and do something like:

```hbs
{{#feature-flag "ember-htmlbars-component-generation"}}
New docs
{{else}}
Old docs
{{/feature-flag}}
```

We would then use the `features.json` in Ember to build release-specific versions of the documentation. This would allow us to begin active work on documentation at the same time as active work on features, with the same collaboration benefits (versus feature **branches**) as feature flags have on the code itself.

The main work item here is to write infrastructure that strips content behind feature flags based on a `features.json`.

**Comment by locks** [comment]
I don't think this is happening in a foreseeable future.
