### ISSUE TITLE
[Tutorial] Reference codebase for tutorial

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1106]
> locks [9:56 PM]  One thing, I wanna make a repo for the tutorials and it'd be cool to link to "snapshots"
> locks ​[9:57] No idea how to do it because of the versioning
> acorncom [9:58 PM] @locks: open an issue :trollface:

**Comment by acorncom** [comment]
Initial repo setup here, more work on it welcome: https://github.com/acorncom/super-rentals

**Comment by locks** [comment]
https://github.com/emberjs/super-rentals

**Comment by acorncom** [comment]
Closing this, we have the codebase

**Comment by toddjordan** [comment]
Issue #1374 is swallowing this issue up.  Tutorial stuff will be tracked there going forward.
