### ISSUE TITLE
Add import statements 

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1107]
According to @tomdale we are good to go on the new module shims, so we can start adding import statements.

Here are the shims for reference: https://github.com/ember-cli/ember-cli-shims/blob/master/app-shims.js

Example. In https://guides.emberjs.com/v2.2.0/controllers/dependencies-between-controllers/ the second code sample would go from

```javascript
export default Ember.Controller.extend({
  postController: Ember.inject.controller('post')
});
```

to

```javascript
import Controller from 'ember-controller';
import injectController from 'ember-controller/inject';

export default Controller.extend({
  postController: injectController('post')
});
```

I need further confirmation before labelling this `help wanted` and have people move ahead.

**Comment by rwjblue** [comment]
Unless this just changed, we have not agreed on the final shim paths. 

@tomdale - Was this something just discussed today (sorry for being absent)? If not, how did you reach the conclusion that we were all onboard with the current shims?

**Comment by locks** [comment]
Might be my misunderstanding, hence wanting confirmation. Apologies if I generate any confusion.

**Comment by rwjblue** [comment]
No worries! I also want this to be ready to go. Hoping to discuss at the next F2F (in January) if it isn't resolved before then.

**Comment by locks** [comment]
I've put it in the "Future" milestone to signal that it's still upcoming, and I'll leave the issue open to document the need to do it.

**Comment by tomdale** [comment]
@rwjblue We've been shipping `ember-cli-shims` with Ember CLI for awhile now. They've become de facto standardized by that, IMO. Unless someone has specific objections, I think it's past time we document them. If we need to change them later, the backwards-compat strategy is pretty straightforward.

**Comment by acorncom** [comment]
Per @rwjblue on Slack, tldr from the the last core team call:

> we will add imports to guides when they are shipped by ember (and not the shims)

I'm going to close this issue and we'll revisit when they've shipped

**Comment by tomdale** [comment]
For context, that should be in the next release IIRC.

**Comment by acorncom** [comment]
@tomdale Can we request a ping when that lands?  We'll organize a scavenger hunt when it does :-)

**Comment by acorncom** [comment]
I've been hauled onto the mat for closing this issue, I hereby duly repent of my errant ways ...

Thanks @locks :smile:

**Comment by rwjblue** [comment]
Yes, I will definitely let y'all know when we get a PR up for moving the shims/modules into Ember itself.
