### ISSUE TITLE
Translations for Docs 

### ISSUE THREAD

**Issue by IsaacLessard** [emberjs/guides#1110]
Thoughts on doing translations of the docs into other common languages? I understand that the current docs are still growing, but I am willing to start/lead a team for translation into French, Spanish, Japanese, or another suggested language. We can keep the translation open source as well.

**Comment by michaelrkn** [comment]
@IsaacLessard This sounds great. First, through, we need to figure out the infrastructure for the translations. Will they live in this repo or a fork for each language? If here, what will the directory structure be? If elsewhere, will they be deployed separately? How will the translations be kept in sync?

**Comment by acorncom** [comment]
Agreed on working out the infrastructure first.

For reference on which languages people might be interested, the below screenshots show traffic patterns on the Ember sites in 2015:

![2015-12-17_17-29-42](https://cloud.githubusercontent.com/assets/802505/11935428/095d06bc-a7c5-11e5-87cf-2d9dc8e001d8.png)

![2015-12-17_17-30-47](https://cloud.githubusercontent.com/assets/802505/11935435/0dd3b72c-a7c5-11e5-9137-2a964039873f.png)

English is pretty dominant right now ...

**Comment by IsaacLessard** [comment]
Awesome. Agreed on figuring out infrastructure, I am open to suggestions for best practice. Hopefully interest in Ember will increase more globally with access in their native languages. Interesting that German/Russian/French are the top languages after English. Most open source translations that I have seen floating around have been Chinese or German.

**Comment by locks** [comment]
Where's that CMS when we need it.

For reference: https://github.com/emberjs/guides/issues/188.

I myself proposed translations a long while back, but we do not have nearly enough bandwidth to do them "internally" at the moment. The good news is that the translation projects can get well underway without the docs team ;) There is an informal effort going on for [pt-BR](https://github.com/EmberJSBrasil/guides) already.

I basically make trek words mine, make it happen and we'll figure out integration once its quality is up to par.

**Comment by acorncom** [comment]
This tool might be useful as well: https://crowdin.com  Per a tweet I saw this morning, BabelJS just got comped its use, so there might be hope for us as well ...

**Comment by thejameskyle** [comment]
I wrote this about the setup Babel uses for translations https://github.com/thejameskyle/crowdin-sync

**Comment by acorncom** [comment]
@thejameskyle Thanks! :+1:

**Comment by nightire** [comment]
Yeah, I'm one of the translators in Babel Plugin Handbook, I would say Crowdin is a good option for Ember as well.

**Comment by wifelette** [comment]
I've been chatting with somone from the Japanese Ember community very interested in helping get things started on the Japanese front, who also says he has experience working on this kind of effort before. Going to see if I can get Tim (GH handle currently unknown) to jump in here.

**Comment by IsaacLessard** [comment]
Awesome, crowdin looks great. I am also very interested in helping getting the Japanese translations started as well, I would love to talk with him.

**Comment by timoth3y** [comment]
I few members of the Japanese Ember community are interested in helping out with the localization. Crowdin is fine. Regardless of platform, the secret to making these projects work is communication with the core team and setting up lots of small wins early on.

**Comment by timoth3y** [comment]
Is this project going to be moving forward? There is already a great (but small) community in Japan and Japanese language tutorials and docs would really help it grow.

**Comment by thejameskyle** [comment]
I'm happy to set everything up on my server to sync translations from crowdin if thats what is wanted. Just needs a project structure and `crowdin.yaml` file setup like this one: https://github.com/thejameskyle/babel-plugin-handbook/blob/master/crowdin.yaml

**Comment by acorncom** [comment]
@timoth3y Yes, we're interested in having it move forward, mainly working on figuring out the logistics on it.  Planning on discussing it in our meeting tomorrow.  If you'd like to drop in to the Slack `#documentation` channel, we can discuss in more detail.

@thejameskyle Thanks, much appreciated!

**Comment by nightire** [comment]
...and this awesome walk-through guid: thejameskyle/crowdin-sync

**Comment by locks** [comment]
We are hooked up, people! Time to get busy translating.

**Comment by nightire** [comment]
@locks Cool, where to join now?

**Comment by acorncom** [comment]
If you'd like to help with translating, please contact us on the Slack `#documentation` channel (after signing up for a Crowdin.com account) and we can give you access
