### ISSUE TITLE
config.js example not working

### ISSUE THREAD

**Issue by JasperKamp** [emberjs/guides#1120]
Hello. I could not get the mirage example to work, neither on a mac nor on a linux setup.
The website url is: https://guides.emberjs.com/v2.2.0/tutorial/ember-data/

I ended up looking at other examples on the internet which caused me to change the content of the <code>config.js</code> to <code>[config.js.txt](https://github.com/emberjs/guides/files/73594/config.js.txt)</code>

**Comment by michaelrkn** [comment]
This isn't a great place to ask for help - please try stackoverflow.com.

**Comment by JasperKamp** [comment]
@michaelrkn This was not a request for help. Instead, it was a correction (answer) of an issue I encountered on the Getting Started guide. 

Perhaps I should have rephrased the original issue. 

Anyways it is working for me, just wanted to share my findings with the rest.

**Comment by michaelrkn** [comment]
Sorry for the misunderstanding. You should not need to rename config.js to config.js.txt (see http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/). If you believe there is a bug that require you to rename your file like this, could you please provide the steps to reproduce the issue? Thanks!

**Comment by JasperKamp** [comment]
Now I understand the confusion. I was not renaming the file to config.js.txt, but I was using an *text-file attachment* of a corrected config.js to demonstrate the full version of config.js that was working for me.

Allow me to be more elaborate. 

The following code, as posted on the guide, was **not** working for me:
```
export default function() {
    this.get('/rentals', function() {
    return {
        data: [{
        type: 'rentals',
        id: 1,
        attributes: {
          title: 'Grand Old Mansion',
          owner: 'Veruca Salt',
          city: 'San Francisco',
          type: 'Estate',
          bedrooms: 15,
          image: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Crane_estate_(5).jpg'
        }
      }, 
...
```
After seeking help in other examples, I altered the config.js to a working: 

```
export default function() {

  this.get('/rentals', function() {
    return {
      rentals: [
      {
        id: 1, 
        title: 'Grand Old Mansion',
        owner: 'Veruca Salt',
        city: 'San Francisco',
        type: 'Estate',
        bedrooms: 15,
        image: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Crane_estate_(5).jpg'     },
...
```

However, after reading some of the other closed issues, I too notice that my ember version is not 2.2 as the guide states. Perhaps that's (part of) the issue?!

Running `ember -v` on command line, yields:
```
version: 1.13.13
node: 5.3.0
npm: 2.14.10
os: linux x64
```

**Comment by michaelrkn** [comment]
Looks like you missed the section on [upgrading to the latest version of Ember Data](https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember).
