### ISSUE TITLE
numeric character displayed as square on google chrome on windows

### ISSUE THREAD

**Issue by tsing80** [emberjs/guides#1124]
Environment : Windows 10 x64
Browser : Google chrome  47.0.2526.106 m

All the numeric character is shown as square for the latest guide :
![before](https://cloud.githubusercontent.com/assets/9977225/12048513/fc28aca4-af16-11e5-8ae1-3574a7f080ce.png)

After removing the "pnum" element from the below style highlight in blue, (changed to '-webkit-font-feature-settings: "kern", "liga"')

![css-style](https://cloud.githubusercontent.com/assets/9977225/12048521/1015dd04-af17-11e5-873a-79d8a7311cad.png)

It display fine again:

![after](https://cloud.githubusercontent.com/assets/9977225/12048519/093f7e7c-af17-11e5-9505-3d9e75c69443.png)

Firefox and Edge browser work fine without the change

**Comment by tsing80** [comment]
Just find out if you enable "Disable DirectWrite" feature in chrome://flags,  there will not be square anymore  but the font display is not as nice with the feature disabled

**Comment by mattmazzola** [comment]
It looks like it's fixed in latest Chrome: Version 49.0.2623.110 m

![image](https://cloud.githubusercontent.com/assets/2856501/14086718/63e0cef8-f4db-11e5-8dd8-955823e593e8.png)

**Comment by acorncom** [comment]
Thanks, will close.  If someone else sees this, we'd be happy to open this again

**Comment by tsing80** [comment]
confirmed latest version of chrome solve the issue. Thanks
