### ISSUE TITLE
Add (temporary) note to Getting Started about upgrading Ember

### ISSUE THREAD

**Issue by toobulkeh** [emberjs/guides#1125]
At the end of [The Getting Started / Installing Ember Guide](https://guides.emberjs.com/v2.2.0/getting-started/) it says "You're good to go", but at this point in onboarding you're using Ember 1.13 and Ember-CLI 1.13. While Ember-CLI 2+ hasn't been production released yet, Ember is on 2.2.1 as of this writing.

It took us, as new users to Ember, way too long to figure out that a few extra steps were needed.

After some discussion on Ember's Slack #needhelp, I believe the preferred Ember installation method is still ember-cli, and the current preferred Ember update procedure is updating bower.json manually, [as referenced here](https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember).

Seeing as how Ember 2.0.0 was released 5 months ago and Ember-CLI is pending, (but still pending...), I would suggest adding a detailed (yet temporary) note and steps for overriding those versions without upgrading Ember-CLI.

I totally realize this is temporary work, but this is a large gap to a newbie, which I'm assuming these guides are targeted towards.

Note: I mistakenly commented about this in another [seemingly related task](https://github.com/emberjs/guides/issues/1094), which is not at all related. Sorry about that!

**Comment by cafreeman** [comment]
+1 It totally seems trivial now, but it took several different false starts and a lot of googling to finally find an article that actually mentioned how to get Ember and Ember Data up to the current version.

**Comment by locks** [comment]
This has been previosuly discussed and rejected. It is not trivial to update older versions of the guides (which 2.2.0 would be by then).

**Comment by michaelrkn** [comment]
@locks We have not added anything 2.3-specific yet. Several issues have been opened by people going through the tutorial accidentally using old versions of Ember and especially Ember Data. I think this is a real problem and we should get this in before we add anything 2.3-specific.

**Comment by locks** [comment]
@cafreeman https://guides.emberjs.com/v2.2.0/getting-started/ember-cli/#toc_upgrading-ember shows how to update said versions

**Comment by locks** [comment]
@michaelrkn 2.3 of the guides won't be released until after CLI 2.2 so that is a moot point

**Comment by michaelrkn** [comment]
rwjblue [8:07 AM] 
Most likely going to release 2.3 final next weekend (by the 4th). 

michaelrkn [4:00 PM] 
is cli 2.3 going to be released simultaneously?

rwjblue [4:03 PM] 
Beta most likely, but ya

**Comment by toobulkeh** [comment]
Guides trailing CLI trailing Ember?

**Comment by acorncom** [comment]
#1153 should help resolve this.  Looks like ember-cli is likely to be in beta through at least Ember 2.4 as final items are cleaned up with it (per rwjblue on Slack in the last few days)
