### ISSUE TITLE
Routes and Templates Confusion

### ISSUE THREAD

**Issue by rovo79** [emberjs/guides#1140]
https://github.com/emberjs/guides/blob/881b4850705402c1535d64a8ac3721996a5b853f/source/tutorial/routes-and-templates.md

On line 90, it shows correctly, localhost:4200/about

but on the public site guide it still shows localhost:4200:
https://guides.emberjs.com/v2.2.0/tutorial/routes-and-templates/

**Comment by locks** [comment]
This will be fixed during the 2.3 release.

**Comment by acorncom** [comment]
Closing this as it'll be handled during release
