### ISSUE TITLE
Run loop example has a mixed content error from the iframe src

### ISSUE THREAD

**Issue by mozeryansky** [emberjs/guides#1146]
https://guides.emberjs.com/v2.2.0/applications/run-loop/#toc_an-example-of-the-internals

In source/applications/run-loop.md, the iframe points to a http url:
`http://emberjs.com.s3.amazonaws.com/run-loop-guide/index.html`
But the site is served on a https connection, so the console reports a mixed content error and doesn't load the url. Testing in Firefox and Chrome.

I would submit a PR for https, but the amazon certificate isn't valid for the domain. Chrome reports it as "NET::ERR_CERT_COMMON_NAME_INVALID", with the explanation "This server could not prove that it is emberjs.com.s3.amazonaws.com; its security certificate is from *.s3.amazonaws.com."

Doing some research I found the original app came from `https://github.com/machty/ember-run-loop-visual`, but the version in that repo doesn't look like the one being served through s3.

I believe this is an artifact from when the guides moved from emberjs/website to emberjs/guides. I think a solution to this would be to serve the example through Firebase, like the rest of the guides. But this is not something I can submit a PR for.

**Comment by acorncom** [comment]
@mozeryansky Thanks, looks like we can shift to using a folder name instead of the `emberjs.com.s3.amazonaws.com` path, which fixes both the SSL issue and eliminates the need to put everything on Firebase :-)
