### ISSUE TITLE
Using Mirage with Ember Data

### ISSUE THREAD

**Issue by rovo79** [emberjs/guides#1155]
I've been struggling to successfully complete this guide for a few days now, stuck each time at the Ember Data section. After I installed ember-cli-mirage, I would try to proceed through the rest of the guide, but http://localhost:4200 would return a blank page in the browser, with an error http://localhost:4200/rentals 404 not found. 

What seemed to fix it for me: in super-rentals/package.json I added (~line 31);
`"ember-cli-mirage": "^0.1.11",`

Then in the terminal I ran:
`ember init'`

Then:
`ember s`

**Comment by acorncom** [comment]
@rovo the thing that actually fixes it is restarting your Ember server. Sent you some details on Slack. Glad you're up and running!

**Comment by rovo79** [comment]
@acorncom  I did try restarting Ember to fix it, but that didn't seem to resolve it for me. So I looked again at all my JSON files, and noticed no mention of Mirage in there. Maybe my build was erroring out causing it not to be added? 

Thank you very much for all the help you provided me in getting up and running.
