### ISSUE TITLE
Tip on testing Error substates

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/guides#1157]
I think it may be a good idea to add to the testing guides how to test fault tolerant behaviors in acceptance tests. For example, writing an acceptance test with a mocked XHR error with status 502 (Bad Gateway) which can be handled using the application-error substate to display a friendly message to visitors instead of a blank screen.

However, because an error is thrown and the env is testing Ember calls Test.adapter.exception which fails the test because there was an error. In acceptance testing using `assert.throws` will not help since it's async. I found that I had to reopen my test adapter in the acceptance test like so:

```js
Ember.Test.QUnitAdapter.reopen({
  /*
    This is a hack, throwing an error in a route must use the error.name
    `TransitionAborted`; otherwise, `Test.adapter.exception(error)` inside
    `onerrorDefault` fails tests via the same error that results in rendering
    the application-error template.
  */
  exception: function(error) {
    if (error.name === 'ServerError' /* my custom error */) {
      console.warn('Expected this error, ignoring (no reason to fail a test)…', error);
    } else /*if (error.name !== 'TransitionAborted')*/ {
      return this._super.call(this, error);
    }
  }
});
```

This is the code that would normally fail the test for the applicaiton-error.hbs template  (without the reopen code above) -> https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/rsvp.js#L66

Do you agree? Do we need an example for testing error substates in the guides or not?

**Comment by acorncom** [comment]
I'm inclined to think this is more in-depth than we would want for the guides, but would make a great blog post somewhere (or possibly something to add to the API docs somehow).  @locks ?

**Comment by pixelhandler** [comment]
@acorncom thanks, I agree prolly not needed in the guides, thx.

**Comment by locks** [comment]
@pixelhandler I would suggest submitting it to https://github.com/emberwatch/emberwatch as a recipe

**Comment by theseyi** [comment]
@pixelhandler in what file you have to insert the reopen above?
