### ISSUE TITLE
Add documentation for `{{#each key="something"}}` back to "Displaying a List of Items"

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/guides#1166]
I noticed that the documentation for `key` usage in the [Displaying a List of Items](https://guides.emberjs.com/v2.2.0/templates/displaying-a-list-of-items/) has been removed from the guides. It was removed in [this PR](https://github.com/emberjs/guides/pull/629).

> @index should really never be needed in 1.13.8 or 2.0+

In a Canary app (2.2.0-beta.3) I changed rerender performance from ~650ms to ~90ms by adding `@index` to `{{#each}}` when rendering an array of arrays in a Conway's Game of Life app.

> Sufficient documentation exists in the [API docs](http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_specifying-keys).

`@index` is used in an example, but not explained in the linked API docs. Also I previously looked in the API documents and was not able to find the `key` documentation. I did not know to look in `Ember.Templates.helpers` and the search doesn't show this result because the term `key` is so common.

> Really, we do not want new users to need to reach for this functionality. Seems more confusing than helpful

I'm worried that someone who hasn't been following the project would never know that `@index` or even `key` exists. Given that using keys can dramatically change rerender performance I feel something should be added back to the guides. Perhaps using keys is an "advanced" feature, but if I were starting with Ember and saw the rendering performance issues that I did before setting a key, I would conclude that Ember is not performant enough for many use cases.

I do agree with the comments in the PR indicating that the previous documentation didn't really explain when or why to set `key`. Perhaps the mental model here should be something like:

> If `{{#each}}` determines that its new array has items that are similar to items it previously rendered, Ember will try to reuse and modify the exiting template pieces for those items rather than starting from scratch. In many cases this reuse can increase re-render performance inside of `{{#each}}` helpers. 

> Ember attempts to match array items by Object identity (`obj === obj`) or by value for Strings and Numbers. If you're looking for ways to increase re-render performance, you can tell `{{#each}}` how to match items between renders by using the `key` attribute. This is most effective when passing a new array to `{{#each}}` that contains items that were previously rendered. For instance...

I would definitely want to run the explanation by some Glimmer gurus to make sure we have an accurate (if simplified) representation of what is going on. Does this seem reasonable?  If so, I'd be happy to create a pull request.

**Comment by rwjblue** [comment]
> In a Canary app (2.2.0-beta.3) I changed rerender performance from ~650ms to ~90ms by adding @index to {{#each}} when rendering an array of arrays in a Conway's Game of Life app.

Usage of `@index` is complicated. If you example used local component state and then the items are reordered, you are in for a very bad time.  This is definitely not "the happy path", and I'm not convinced it belongs in the guides.

> @index is used in an example, but not explained in the linked API docs.

Lets fix that! 

> I'm worried that someone who hasn't been following the project would never know that @index or even key exists.

Having a link from the `Displaying a List of Items` section (or other applicable place where we talk about the `{{each}}` helper) to the API docs, seems good to me (combined with a PR to better document `key` and whatnot it should resolve your concerns here).

**Comment by mitchlloyd** [comment]
> Having a link from the Displaying a List of Items section (or other applicable place where we talk about the {{each}} helper) to the API docs, seems good to me (combined with a PR to better document key and whatnot it should resolve your concerns here).

Sounds like a good compromise given that there are pitfalls to using this feature. I can create a PR in this repo to link to the correct API section, but I'm probably not the right person to update the API documentation. Just looking at the Ember and HTMLBars isn't giving me a picture of what is going on. I've _always_ seen an increase in rerender performance when adding a key -- even if it is something that isn't unique. I must have not hit these other edge cases yet.

**Comment by acorncom** [comment]
@mitchlloyd Would you be willing to send in a PR to this repo and then open an issue on the main https://github.com/emberjs/ember.js/issues repo about the need for API docs on this?

**Comment by mitchlloyd** [comment]
@acorncom Added a PR: https://github.com/emberjs/guides/pull/1187

**Comment by mitchlloyd** [comment]
@acorncom Also added an [issue to emberjs/ember.js](https://github.com/emberjs/ember.js/issues/12853).

**Comment by acorncom** [comment]
Closing this issue, PR has been merged. Thanks!
