### ISSUE TITLE
Setting properties on the component in didInsertElement() triggers a re-render - not clear

### ISSUE THREAD

**Issue by ryrych** [emberjs/guides#1173]
In [Integrating with Third-Party Libraries with didInsertElement](https://github.com/emberjs/guides/blob/master/source/components/the-component-lifecycle.md#integrating-with-third-party-libraries-with-didinsertelement) it is not clear **which properties trigger re-render**:

- `this.$().attr(…)
- this.set('componentAttribute', 'foo')

I tried both:

```js
didInsertElement() {
  this.$().attr('contenteditable', true);
}
```

and

```js
this.set('componentAttribute', 'foo');
```

and no exception has been thrown. **Perhaps it concerns top-level component**: 
https://github.com/emberjs/ember.js/blob/d69b2f75b8bfa509a7146b2f1efe44ba5bb6c35f/packages/ember-views/tests/views/view/view_lifecycle_test.js#L108-L122

**Comment by locks** [comment]
@ryrych the test right after is for non-top level views: https://github.com/emberjs/ember.js/blob/d69b2f75b8bfa509a7146b2f1efe44ba5bb6c35f/packages/ember-views/tests/views/view/view_lifecycle_test.js#L124-L142

`this.$().attr('contenteditable', true);` isn't setting an attribute of the component's JavaScript though, which is what's meant afaik. Meaning, your last snippet should throw a warning.

**Comment by ryrych** [comment]
Thanks, I'll check that out!

**Comment by ryrych** [comment]
@locks you're right, this triggers a deprecation warning. I'm closing the issue.
