### ISSUE TITLE
Sidebar section links may wrap on hover

### ISSUE THREAD

**Issue by kevinkucharczyk** [emberjs/guides#1174]
I'll start with a gif:

![emberguides](https://cloud.githubusercontent.com/assets/3127419/12419060/ee154c4c-beb3-11e5-9723-9f26e1542c71.gif)

Some section name lengths may cause wrapping the link to another line when hovered, but are short enough to stay on one line otherwise. This can be disruptive while navigating through the Guides.

**Comment by locks** [comment]
Hm, what do you propose? I personally don't mind the current behaviour. Maybe ellipses instead?

**Comment by kevinkucharczyk** [comment]
This behaviour is a little bit annoying when I'm moving the cursor from the top - imagine trying to move the cursor from "Wrapping Content in a Component" and wanting to click "Handling Events" - the target would move down a little bit :)

Ellipses should work, though I'm not sure if cutting off a section name is desirable. I was also thinking of `white-space: nowrap`, but then again this might cause problems with really long section names.

**Comment by eccegordo** [comment]
Perhaps adjust the margin on hover to account for thicker border on hover state of left div side.

I can guess what the CSS might be just need to look at it. I think left margin on hover should be negative a couple pixels probably.
