### ISSUE TITLE
Search is broken in 2.3.0 guides

### ISSUE THREAD

**Issue by jeradg** [emberjs/guides#1183]
Using the search field in the header is broken in the 2.3.0 version of the guides. Works in other versions and in the API docs.

Stacktrace from Chrome:

```
Uncaught TypeError: Cannot read property 'query' of undefined
  d @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:18
  c @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:14
  h.fireWith @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:14
  r @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:16
  n.onload.n.onreadystatechange @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:16
```

**Comment by locks** [comment]
> locks [5:41 PM] 
I didn't deploy the resources for 2.3 search
[5:42] 
we're going to redeploy and the only way I know is to manually delete the search indices
[5:42] 
so I didn't deploy it :angel:

**Comment by jeradg** [comment]
Well, I guess I just volunteered myself to look into automating it.

**Comment by jeradg** [comment]
Will possibly be addressed by https://github.com/emberjs/guides/issues/1184.

**Comment by acorncom** [comment]
> Well, I guess I just volunteered myself to look into automating it.

@jeradg If you don't have time, we'll understand.  But would love to have the help if you're able :

**Comment by locks** [comment]
:shipit:
