### ISSUE TITLE
Wrong version on Getting Started / Installing Ember

### ISSUE THREAD

**Issue by jansegre** [emberjs/guides#1190]
[Getting Started / Installing Ember](https://guides.emberjs.com/v2.3.0/getting-started/#toc_installation) for version 2.3.0, the `ember-cli` version shown there is `2.2.0-beta.6`, I would expect `2.3.0-beta.1`.

I would open a PR, but I'm just not sure to what branch I should request the pull, or if this actually temporary until `ember-cli` is out of beta.

**Comment by locks** [comment]
Hi, @jansegre. This will be addressed by https://github.com/emberjs/guides/pull/1176 when it gets merged.
Ember CLI 2.x won't come out of beta until a couple of behind the scenes changes are made, namely addonifying Ember (Ember Data is fully addonified in 2.3). That explains the beta-ness.

To explain why the PR hasn't been merged, we deployed a temporary version of the 2.3 guides while we merge some work that has been done for 2.2. We will updating 2.2 and 2.3 soon properly.

Thanks for reporting :)

**Comment by jansegre** [comment]
:+1:

**Comment by acorncom** [comment]
I'll go ahead and close now
