### ISSUE TITLE
Filtering Deprecations example uses underscores

### ISSUE THREAD

**Issue by gandalfar** [emberjs/guides#1193]
This example:
https://guides.emberjs.com/v2.3.0/configuring-ember/handling-deprecations/#toc_filtering-deprecations

Doesn't work out of the box, because it uses `_` from underscores.js. It might be better to either mention this dependancy or rewrite it in a way that doesn't need underscores.

**Comment by acorncom** [comment]
@toddjordan Here's that underscore issue that was getting discussed on the Slack `#documentation` channel

**Comment by acorncom** [comment]
Closed by the PR above, thanks for the feedback!
