### ISSUE TITLE
ES6/ES2015 in Getting Started Guide

### ISSUE THREAD

**Issue by peterramsing** [emberjs/guides#1196]
While going through the [Getting Started](https://guides.emberjs.com/v2.3.0/getting-started/ember-cli/) section I noticed that the reference to ES6 didn't also reference ES2015.

There is a [line](https://github.com/emberjs/guides/blame/master/source/getting-started/ember-cli.md#L100) that says:
> Ember CLI uses ECMAScript 6 (or ES6 for short) modules to organize application code.

I think it might be worth adding "...ECMAScript 6 (or ES6 for short **or also referred to as ES2015**) modules..." (bold to reference change).

(I can submit a PR and maybe wordsmith it a bit more if this seems appropriate. Being I just "started" in the Ember community I don't want to impose. :smile:)

(...and goodness these docs are amazing! Thanks!)

**Comment by locks** [comment]
Hm, technically the name is `ECMAScript 2015`, so maybe switch it around and have "(also known as ES6)"?

cc @acorncom

**Comment by rtablada** [comment]
Peter, submit a pr. I always appreciate feedback like this. We aim to make the docs clearer and to developers of all experience with JS and Ember!

**Comment by acorncom** [comment]
@peterramsing welcome to Ember and thanks for the suggestion. Nice to get positive feedback, we mainly heard negative things for quite a while :smile: And yes, please do send in a PR.

@locks personally I prefer the original suggestion, as I see more references across JS tutorials, etc to ES6 than ES2015 even though that may not be quite as correct ...

**Comment by peterramsing** [comment]
To be technically correct but also having ES6 in there, how does this feel:

> Ember CLI uses ECMAScript 2015 (ES2015 for short or previously known as ES6) modules to organize application
code.

Off to go for a run and will submit the PR later tonight or in the AM.

**Comment by peterramsing** [comment]
Closing for #1197
