### ISSUE TITLE
The link to "ES6 Support" on Glossary page is broken

### ISSUE THREAD

**Issue by nagarajhubli** [emberjs/guides#120]
The link to "ES6 Support" on Glossary page is broken, it has extra semicolon at the end, but I see that the issue is not with the corresponding Markdown file.

**Comment by bsclifton** [comment]
Looks and works great when running locally w/ Middleman. I also ran a middleman build and looked at the output, it looks correct: ```<a href="http://kangax.github.io/compat-table/es6/">``` compared to https://github.com/emberjs/guides.emberjs.com/blob/master/snapshots/v1.11.0/ember-cli/glossary/index.html.  @trek, can you try rebuilding?

**Comment by trek** [comment]
This appears to be fixed on master. Thanks!
