### ISSUE TITLE
[Tutorial] Route generator output is wrongly inlined

### ISSUE THREAD

**Issue by sotojuan** [emberjs/guides#1203]
In the second paragraph of [this](https://guides.emberjs.com/v2.3.0/tutorial/routes-and-templates/#toc_an-index-route) section, the code after "We can see the now familiar output for the route generator" should be in a box, like the other shell output or code examples. When looking at [the Markdown](https://github.com/emberjs/guides/blob/master/source/tutorial/routes-and-templates.md#an-index-route) though, it looks fine.

Any ideas to what is causing this?

**Comment by locks** [comment]
I believe the fix was merged after we deployed. Should get fix soon.

**Comment by sotojuan** [comment]
Sounds good! Closing the issue for now.
