### ISSUE TITLE
v1.11 doc is missing (updated) TodoMVC-style guide

### ISSUE THREAD

**Issue by LionsPhil** [emberjs/guides#121]
v1.10 docs have a pretty good lead-in with a small sample application:
http://guides.emberjs.com/v1.10.0/getting-started/planning-the-application/
It covers good starting matter like:
* Ember's opinion of what Model, View and Controller mean in a client-side world
* Data-binding between the model and view in both directions (read and edit)
* Binding of other actions ("delete completed")
* Non-persistent state, and the concept that the controller is a proxy for the model which can manipulate and infer data for the view
* Routing
* Data persistence layers (fixtures for inital template work vs. moving to some real storage, although expanding it to continue on to a ReST endpoint would be even better)

In particular it's impressive that it starts with a spec and static mockup, because this fits the real world and keeps the whole thing in firm context of the end goal.

v1.11 docs don't seem to have these pages, but should have something covering the same ground, e.g. an updated version of the v1.10 app since for a simple example it can already cover a lot of angles.

https://github.com/emberjs/guides/issues/91 also covers Getting Started, but in the context of Ember CLI AFAICT. At least personally I already had different infrastructure around (Dancer project and some initial experiements with Backbone) so having an example which was just Ember (and Ember Data) was useful.

(Moved from https://github.com/emberjs/ember.js/issues/10738 )

**Comment by trek** [comment]
There is another sample application in the works that sadly did not get finsihed in time for 1.11. We did not believe that TodoMVC demonstrated a useful application for Ember, but didn't want to update the additional resources (git repo, jsbins, etc) around it for a single version.

**Comment by fullofcaffeine** [comment]
@trek Where can I find this new sample application?

**Comment by trek** [comment]
cc @poteto who was working on it

**Comment by poteto** [comment]
I am in the process of re-writing it for Ember 2.0, as well as the accompanying guides
