### ISSUE TITLE
Document how dasherized model names work in relationships / store calls

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1213]
Some folks get confused without clarification on this (see https://github.com/emberjs/guides/issues/1192).  Suggested locations:

- `models/finding-records` (in addition to our `post` we might want to alternate with `blog-post`)
- `models/relationships` (again, might be worth changing `post` to `blog-post` under One to Many)

**Comment by alexwilkinson** [comment]
I think this issue can be resolved now! : D
