### ISSUE TITLE
Fix illegible + / - setup in the new Quick Start

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1221]
In the new Quick Start that just got merged, the background behind the code blocks makes it very hard to read.  Parts of it look great, but others definitely do not ;-)  /cc @locks 

![screen shot 2016-02-03 at 10 20 35 pm](https://cloud.githubusercontent.com/assets/802505/12806559/61e2e104-cac4-11e5-83db-acd719b290d6.png)

**Comment by locks** [comment]
Looks fine to me.

**Comment by acorncom** [comment]
Hmm, this is Safari 9.0.2 (or Chrome 47) on 10.9.5.  I'll see about checking on a different OS in a bit ...

**Comment by acorncom** [comment]
I'm seeing the same issues with same browser versions on OS 10.10.  Initial few code blocks look fine but the later ones don't look so good ...

**Comment by locks** [comment]
I forgot :trollface: .
