### ISSUE TITLE
Install Guide - wrong version

### ISSUE THREAD

**Issue by cllns** [emberjs/guides#1231]
On: https://guides.emberjs.com/v2.3.0/getting-started/

When I run
```
npm install -g ember-cli@beta
ember -v
```
I get version `1.13.15`:
```
version: 1.13.15
node: 5.4.1
npm: 2.14.10
os: darwin x64
```

I didn't realize I was on the wrong version until I got to the Mirage section, when it just didn't work.

The Getting Started page says:
```
If a version number is shown, you're ready to go.
```
Maybe it should be more specific? I didn't even run `ember -v` to check, but if I did, it would've shown *a* version number, but not the correct one.

Instead, the install line should be something like
```
 npm install -g ember-cli@2.3.0-beta.2
```
Is there some more general way to get the latest beta? `@latest` does 1.13.15 too

First reported at emberjs/ember.js#12837, and I also ran into this issue.

**Comment by locks** [comment]
If you ran `ember -v` inside a project you got the version that the project depends on, not the global one.
I just tried `npm install -g ember-cli@beta` and it correctly installed `2.3.0-beta.2`.

We don't want to be more specific because we don't change older versions of the guide, and those specific versions would need to be changed, especially for security releases.

**Comment by cllns** [comment]
When I first ran that install command, I was using node `v0.12.2` instead of a more recent one. Maybe that's why it installed `1.13.15`?

**Comment by locks** [comment]
@cllns `latest` is the latest _stable_, that is why it will also install `1.13.x`. If try try `@beta` like we currently suggest in the guides, you should be good to go.

**Comment by cllns** [comment]
I think this should be re-opened. I ran `npm install -g ember-cli@beta`, like the guides say, and got `1.13`. I didn't realize it until a later step inexplicably didn't work. 

At least 2 other people reported this same thing: https://github.com/emberjs/ember.js/issues/12837

**Comment by locks** [comment]
That's impossible. I advise asking for help in the Slack channel, something might be off in your env.
The other report was before we updated the guides with the beta instruction.

**Comment by cllns** [comment]
Ok, thanks for you help
