### ISSUE TITLE
Improve Services page

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1232]
- [ ] Reorganize content so injection conventions are explained in the same place
- [ ] Remove mention of being able to inject in an initializer. [? I don't really agree with the idea xD] Or expand on it.
- [ ] Fill out prose

**Comment by toddjordan** [comment]
I can pick this up after I get the service tutorial in, which is this week

**Comment by toddjordan** [comment]
@locks  is this good to close?

**Comment by locks** [comment]
Yup, good catch.
