### ISSUE TITLE
[Tutorial] Need consistency name of rentalUnit

### ISSUE THREAD

**Issue by ChangJoo-Park** [emberjs/guides#1237]
In tutorail, I see the word **rentalUnit**, **rental-unit** in each syntax.

**rentalUnit** is in the  (A Simple Component)[https://guides.emberjs.com/v2.3.0/tutorial/simple-component/]

**rental-unit** is in the (An Autocomplete Component)[https://guides.emberjs.com/v2.3.0/tutorial/autocomplete-component/]

It need to be change to same name.

**Comment by ChangJoo-Park** [comment]
Pull request #1238

**Comment by locks** [comment]
PR merged :)

**Comment by ChangJoo-Park** [comment]
Thank you!
