### ISSUE TITLE
Guides give JSON API data but default is REST API

### ISSUE THREAD

**Issue by bencodezen** [emberjs/guides#1244]
Worked with @spencer516 on this issue when going through the tutorial and discovered that there is a missing step since the default adapter and serializer is using the REST API as opposed the JSON API which is being used in the guide.

![screen shot 2016-02-10 at 10 52 37 pm](https://cloud.githubusercontent.com/assets/4836334/12969061/00a2e364-d049-11e5-995c-ae36134e58ce.png)

The two suggested ways to fix this are:

1. Change the provided data to utilize REST
2. Add steps to generate JSON API adapters and serializer

Would appreciate some discussion on this and then I would be happy to submit a PR on the agreed upon solution.

**Comment by locks** [comment]
@bencodezen your project has the wrong versions, you probably installed CLI `v1.13` instead of the `v2.x` beta like we instruct in https://guides.emberjs.com/v2.3.0/getting-started/#toc_installation.

**Comment by locks** [comment]
Still trying to figure how to make it less error-prone without putting notices all over :\

**Comment by bencodezen** [comment]
@locks Ah. My mistake! I think my confusion was in glossing over the `@beta` part of the command and reading the last line which just says "if a version number shows up, you're good!"

Maybe the appropriate route is to change the verbiage to say, "If your version is v2.x or higher, you're good to go!"

**Comment by locks** [comment]
It's a good suggestion, the potential problem is that we need to specify both the major and minor versions since that's what the guides are synced to. I'll bring it up at the meeting today.
