### ISSUE TITLE
Concat Helper is missing

### ISSUE THREAD

**Issue by spencer516** [emberjs/guides#1249]
After digging through the guides, I couldn't find any place where the concat helper is discussed. With some talk of `classNameBindings` being deprecated (source needed — maybe a Stef Penner tweet?), having good examples of how to use the concat would be great to add.

I'd be happy to create a PR for adding this if there's some guidance on wether to include and where to include.

**Comment by locks** [comment]
Hi @spencer516. The `concat` helper is listed in the [API documentation](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_concat). I don't know about `classNameBindings` being deprecated, what I do know is that with glimmer components they won't be necessary due to the change in semantics.

I can help you improve the API documentation if you feel they're lacking.

**Comment by spencer516** [comment]
You're right that it's there; but getting to that list of helpers is hard to find. I don't think the documentation there is lacking necessarily. It's something I'd expected to find in the guides, but didn't. 

(I actually didn't realize there _was_ a concat helper until I tried to create my own and wondered why it wasn't working and then spent a bit trying to find where helpers were in the API Docs). 

I couldn't find where I'd read that `classNameBindings` was on the list of possible deprecations. I suppose this is moot if it's not. 

Regardless, I've found `concat` to be a particularly useful helper recently. For example, I've had to override the input component in the past to get dynamic class names; concat removed that need.

Anyway — if y'all think it'd be useful, I'd be happy to work on adding it; if not, feel free to close this issue. (PS: Seriously, the work you all have done on the guides and API docs is so awesome!)

**Comment by acorncom** [comment]
I'm inclined to think we don't want to specifically list this helper in the guides (as we're aiming for the guides to be a good, thorough introduction to Ember's API but not an exhaustive documenting of it).

@spencer516 Maybe what we could do is add a note to the bottom of the Input Helpers page (https://guides.emberjs.com/v2.3.0/templates/input-helpers/) with a link to the API page for helpers (http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_concat) saying something like:

> for additional useful helpers not mentioned above, please refer to the Helpers page in the API docs

or something like that.  @locks thoughts?

**Comment by locks** [comment]
I had a similar thought, the thing is that they're not input helpers. I don't know where to put the `hash` helper either. I'll whip up a new helper guide for you to review.

**Comment by Gaurav0** [comment]
@locks Are you still working on this? If not I could try writing up something.

**Comment by Gaurav0** [comment]
Fixed.
