### ISSUE TITLE
[Quick Start] - Video screencast

### ISSUE THREAD

**Issue by rtablada** [emberjs/guides#1250]
I want to offer my time to help contribute a free version of the quick start as a screencast to follow.
I think the early video of Tom creating a small app with Ember helped sell it to a lot of people early on.

A few things as discussed in the docs team meeting:

* Release updates with LTS releases
* Follow Quick Start instead of full Tutorial section to allow the video to stay up to date

I have a few videos on back burner currently, but I think that I can realistically get a first draft of the screencast for Quickstart out by end of next week.

A few things to trim up and answer before going to much further:

* Should there be a review of the script before I start recording (this script time can be really reduced since the guides are already fairly conversational)
* How do we review the final cut/edit
* Where do we host the video?

**Comment by acorncom** [comment]
Re questions above:

- review of the script: I think as long as we stick reasonably close to what we've got we should be fine @locks ?
- how we do the review: post it here or on a video system somewhere?  that or send it over on Slack (either in the `documentation` channel or privately to the docs folks)
- where do we host: the 1.10 video (https://guides.emberjs.com/v1.10.0/) was on Youtube on Tom's personal account. I'm fine with putting it on Youtube, but for future logistics sake it might be worth uploading it to an Ember account instead ...
