### ISSUE TITLE
Crowdin could not parse markdown code block correctly

### ISSUE THREAD

**Issue by nightire** [emberjs/guides#1258]
Unfortunately, our guide uses an advanced markdown syntax that Crowdin couldn't fully understand, here are some examples:

![image](https://cloud.githubusercontent.com/assets/1104018/13023013/d970182e-d21f-11e5-8208-6b10d1c032bc.png)

---

![image](https://cloud.githubusercontent.com/assets/1104018/13023091/64ce005c-d220-11e5-8510-af358bdc983e.png)

Since we append file path and diff info after the open triple backticks, Crowdin didn't know where is the proper ending.

This isn't our side of problem, I just wish to let Crowdin knows the bug of the parser and it should not be hard to fix.

**Comment by mswanson** [comment]
@locks and I found a related issue with the translated markdown files. in many places the code blocks are being rendered incorrectly causing the following syntax error when running `middleman build`:

```bash
Running spell checker for /addons-and-dependencies/managing-dependencies.ja-JP 
guides/lib/highlighter.rb:19:in '_highlight': Code blocks must be fenced with proper language 
designated. If you don't know what language to use, specify text. 
(Highlighter::MissingLanguageError)
```

as an example this markdown from `addons-and-dependencies/managing-dependencies.js`

```markdown
  The globals provided by some assets (like `moment` in the below example) can be used in your
  application without the need to `import` them. Provide the asset path as the first and only argument.
   
    ```ember-cli-build.js
    app.import('bower_components/moment/moment.js');
    ```
  You will need to add `"moment": true` to the `predef` section in `.jshintrc` to prevent JSHint errors
  about using an undefined variable.
```

gets rendered by Crowdin like this:

```markdown

    The globals provided by some assets (like `moment` in the below example) can be used in your 
    application without the need to `import` them. Provide the asset path as the first and only argument.

    ```ember-cli-build.js app.import('bower_components/moment/moment.js');

    <br />You will need to add `"moment": true` to the `predef` section in `.jshintrc` to prevent JSHint errors
    about using an undefined variable.
```

Notice the closing code ticks are absent and the code is all rendered on one line and the next paragraph is nested underneath it. This is not valid markup syntax, hence the error. There appears to be a bug in the Crowdin transpiler.

@locks can we log a bug with Crowdin?

**Comment by nightire** [comment]
@mswanson they say this will be take care of: 

https://twitter.com/crowdin/status/698306618384064512

**Comment by mswanson** [comment]
@nightire thanks

**Comment by acorncom** [comment]
@nightire Do you know if this has been resolved at this point?

**Comment by locks** [comment]
https://twitter.com/crowdin/status/724862924385357824 fffiixxeedd
