### ISSUE TITLE
[Tutorial] Wrong sample shown for "ember g help rental-property-type"

### ISSUE THREAD

**Issue by andela-ooranagwa** [emberjs/guides#1260]
I'm following the ember 2.3.0 guide.

The screenshot in the Handlebars Helper section: https://guides.emberjs.com/v2.3.0/tutorial/hbs-helper/ shows the wrong entry for the result of running
> ember g helper rental-property-type

It shows 
```js
import Ember from 'ember';

export function rentalGroup(params/*, hash*/) {
  return params;
}

export default Ember.Helper.helper(rentalGroup);
```
instead of

```js
import Ember from 'ember';

export function rentalPropertyType([type]/*, hash*/) {
  return communityPropertyTypes.contains(type) ? 'Community' : 'Standalone';
}

export default Ember.Helper.helper(rentalPropertyType);
```

**Comment by locks** [comment]
Hi, thanks for reporting the issue but this has already been addressed by a contributor, but have been deployed. 
The deploy should happen during the next release at the latest.

**Comment by andela-ooranagwa** [comment]
Ok. I'll close this then.d
