### ISSUE TITLE
Improve guide writing style: lists

### ISSUE THREAD

**Issue by fredguth** [emberjs/guides#1262]
There is no standard in how the list items of the guides are written today.
Take for instance: https://github.com/emberjs/guides/blob/master/source/localizable/getting-started/index.md

The first list has items which end with an end point and others with nothing.

One suggestion is to use ";", "; and" and ".".  Example:

> - Modern application asset management (including concatenation, minifying, and versioning);
> - Generators to help create components, routes, and more;
> - A conventional project layout, making existing Ember.js applications easy to approach;
> - Support for ES2015/ES6 JavaScript via the Babel project. This includes support for JavaScript modules, which are used throughout this guide;
> - A complete QUnit test harness; and
> - The ability to consume a growing ecosystem of Ember Addons.

Or just don't use punctuation in the end of a list item. Example:

> - Modern application asset management (including concatenation, minifying, and versioning)
> - Generators to help create components, routes, and more
> - A conventional project layout, making existing Ember.js applications easy to approach
> - Support for ES2015/ES6 JavaScript via the Babel project. This includes support for JavaScript modules, which are used throughout this guide
> - A complete QUnit test harness
> - The ability to consume a growing ecosystem of Ember Addons

**Comment by acorncom** [comment]
I'm partial to the second option (lists without punctuation at the end) over the first option.  However, what we may find if we audit the guides is that our normal use of lists actually already follows that style and it's only the "Getting Started" lists that have punctation at the end.  @fredguth would you be interested in vetting the guide lists and sending in PRs to update as needed?

**Comment by fredguth** [comment]
@acorncom sure.
