### ISSUE TITLE
Setup issue and PR templates?

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1273]
Per https://help.github.com/articles/helping-people-contribute-to-your-project/ we've now got the option to setup issue and PR templates.  Do we want to do this?  Could be helpful / friendly, but don't want to make this overwhelming either (especially for guides).  @locks ?

**Comment by acorncom** [comment]
See also https://github.com/emberjs/ember.js/pull/12976

**Comment by locks** [comment]
Sounds like a good idea! Let's come up with ideas and discuss it at the next meeting.

**Comment by acorncom** [comment]
At a docs meeting last week during EmberConf we decided to skip this for now.  Closing
