### ISSUE TITLE
Components: Documentation missing for yield and block params

### ISSUE THREAD

**Issue by edeis53** [emberjs/guides#1281]
It would be very useful to have an example somewhere in the docs that explains:

1. explaining + example of using `{{yield param1 param2}}` in the component template.  
2. Assigning the output in your handlebars helper via as pipes. `{{#neko-cat phrase1="Siamese” phrase2=“Tabby” as |param1 param2|}}

Logical places would be in the in a section immediately following "wrapping content in a component" possibly two sections "yielding params" and "composing with components"

The only place where I was able to find any mention was here:
http://emberjs.com/blog/2014/12/08/ember-1-9-0-released.html#toc_block-params

Would be good to have yield explained here as well:
http://emberjs.com/api/classes/Ember.Templates.helpers.html

@mmun
@locks

**Comment by locks** [comment]
Related:

* https://guides.emberjs.com/v2.3.0/components/wrapping-content-in-a-component/
* #845

**Comment by acorncom** [comment]
Closed by #1351
