### ISSUE TITLE
Setup a 404 error page to replace default Firebase page

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1285]
If you visit a nonexistent page (https://guides.emberjs.com/v2.3.0/object-model2/) you'll see a Firebase 404 page instead of something that matches our current design.  It would be nice to have a 404.html page built that would display some text that's a bit more friendly (and in the Ember theme) instead.

More details on what we would need are here: https://www.firebase.com/docs/hosting/guide/url-redirects-rewrites.html#section-404

Step 2 (which would probably involve talking with Firebase support) would be to see if we could localize the 404 page and serve it depending on which url path they were trying to reach (i.e. if they went to /pt-BR/bad-page it would show a Portuguese 404 instead of an English 404).

That seems like something we could either explore as part of the initial setup or could wait until we'd shipped the first English-only 404 ...

**Comment by locks** [comment]
Let's ship the english 404 first, feed it to our translators, and then improve on the 404.

**Comment by acorncom** [comment]
@locks suggested using http://emberjs.com/images/tomsters/fishy.png as part of this design.  For the record, @wifelette would like to double-check what we're doing on this prior to merging it.  So please add a screenshot of the finished design as part of a PR here ...

**Comment by filipecrosk** [comment]
Hi @acorncom take a look at this screenshot, I used the same text that I found on 404 page from Ember's site, i.e: (http://emberjs.com/builds/asdfa): 
<img width="1276" alt="screenshot 2016-03-04 01 57 49" src="https://cloud.githubusercontent.com/assets/194257/13523831/a8064bea-e1ac-11e5-854d-794a586997ad.png">

Let me know what do you think

**Comment by locks** [comment]
@filipecrosk can you PR?

**Comment by acorncom** [comment]
I like it! Could you float the image to the left like we're doing here? https://github.com/locks/ember-welcome-page/pull/7

And what does it look like on a small mobile screen? And yes, a PR would be great!

David

**Comment by filipecrosk** [comment]
Based on the firebase's documentation I created this page as a regular HTML page on the root of our project. Let me know if I'm wrong :) 

Desktop version:
![screenshot 2016-03-04 08 57 41](https://cloud.githubusercontent.com/assets/194257/13534174/bc25dd5c-e1e8-11e5-8974-5664deaf457f.png)

Mobile version:
![screenshot 2016-03-04 08 57 25](https://cloud.githubusercontent.com/assets/194257/13534176/c0e14a84-e1e8-11e5-9a26-d3e3e1c541eb.png)

**Comment by acorncom** [comment]
@wifelette You'd wanted to be pinged about the use of the Tomster on the 404 page, this look ok to you?

**Comment by wifelette** [comment]
Ah, yep! It looks good, but the Tomster image version isn't most current. Give me a couple hours to days to get the corrected one, brb...

**Comment by wifelette** [comment]
Also, I could swear I saw a comment about adding some more whitespace between the Tomster and the headline, but now I'm not seeing it. Can we make that happen?

**Comment by filipecrosk** [comment]
@wifelette it's already updated, take a look:
![screenshot 2016-03-04 09 30 47](https://cloud.githubusercontent.com/assets/194257/13534816/d8904a88-e1eb-11e5-8abf-3fce5669c474.png)

**Comment by acorncom** [comment]
@wifelette Yes, the discussion is over on the PR here: #1307 Can we move all discussion of this over there so it's just in one place where the code is being changed? ;-)

**Comment by wifelette** [comment]
Ugh, yes. And I can stop thinking I'm losing my mind :p

**Comment by acorncom** [comment]
Closing this issue because the PR merge didn't merge it automatically
