### ISSUE TITLE
Making Guides Available as PDF (mobi, ePub, etc)

### ISSUE THREAD

**Issue by rtablada** [emberjs/guides#1291]
I have begun to do some preliminary work to make the Ember guides available as PDF.
My initial attempt was to use gitbook for this export process, I think this still may be the easiest path to making a PDF version of the guides.
However, there are a few hurdles that I found in my initial assessment that would have to be addressed in the export process:

* [ ] Gitbook prefers pages to end in `.html` for internal and local links (this could be circumvented by providing configuration via the `structure` option, but I was unable to get said result to work
* [ ] The codeblock file name syntax is breaking Gitbook's codeblock rendering
* [ ] Gitbook requires the `index` or `readme` page to be located in the root directory of the project (even when changed via the `structure` configuration options.
* [ ] Gitbook in the past has not played well with HBS code samples since they use a form of mustache internally for dynamic templating :(

My initial thought was to maybe set up a broccoli build system that moves files into a more gitbook friendly `dist` and does any file manipulation for things like relative links and codeblocks.

I'm also open to looking at other MD -> PDF tools, but I have not had the time to investigate.

**Comment by locks** [comment]
Related:
* https://killercup.github.io/trpl-ebook/
* http://edgeguides.rubyonrails.org/ (see the sidebar for the Kindle book)

**Comment by locks** [comment]
Tracking this off-GitHub.
