### ISSUE TITLE
Referring to objects

### ISSUE THREAD

**Issue by stevekinney** [emberjs/guides#13]
In an effort to find a common voice, how do we want to refer to controllers, routes, etc.?

Previously, the guides had something like `ApplicationRoute`. This made sense because it was defined as `App.ApplicationRoute`. Should we continue this or do we want to switch to `controller:application`?

**Comment by joostdevries** [comment]
Excellent point. The inspector also uses `controller:application` so I think that makes the most sense.

**Comment by trek** [comment]
let's go with it. We can fix it in post.
