### ISSUE TITLE
Living Styleguide

### ISSUE THREAD

**Issue by ryanlabouve** [emberjs/guides#1303]
In the docs meeting we talked about developing a living style guide.

This would be useful for:
* DRY up styles between multiple Emberjs projects and 
* Smaller marketing / project page rapid development (i.e. Here's how you can make a page acceptable Ember enough)
* Help with transitioning older apps to consistent Ember style

It was also mentioned that we could potentially generate style guides using some tool?

/cc @locks @toddjordan

**Comment by acorncom** [comment]
@ryanlabouve The style guide thing I mentioned was this (http://bitters.bourbon.io)  Not sure if would help generate a style guide or not (haven't looked at it too carefully)

**Comment by ryanlabouve** [comment]
Sweet @acorncom!

(sry, I meant to /cc you previously!)

**Comment by namack** [comment]
Hi @ryanlabouve, somewhat related, here is a PR to extract the style code to a gem that can be shared with the website.

#1323

**Comment by locks** [comment]
Tracked at https://github.com/locks/ember-styleguide
