### ISSUE TITLE
Should Ember logo be centered on narrow screen?

### ISSUE THREAD

**Issue by ryanlabouve** [emberjs/guides#1305]
All of the other UI in the nav is centered on narrow screens. I feel like doing the same with the Ember logo creates an improved balance.

Here's a screenshot comparing the two:
![ember_js_-_guides_and_tutorials_and_ember_js_-_guides_and_tutorials_and_new_issue_ _emberjs_guides](https://cloud.githubusercontent.com/assets/1318878/13521963/14532f52-e1b2-11e5-85a6-0d690540edd0.jpg)

I'll go ahead and open up a PR to show what this would look like.

**Comment by locks** [comment]
Yup, I like this.

**Comment by acorncom** [comment]
Yes

**Comment by acorncom** [comment]
Closing this, as the PR just merged
