### ISSUE TITLE
createRecord in store gives no data

### ISSUE THREAD

**Issue by ersuryapurohit** [emberjs/guides#1308]
When we createRecord in from store in any model, it does not give the data in response, in the _internalModel>_data & _attributes, bothe are empty. I found that in store.js, the funtion **buildInternalModel** accepts 3 parameters but when we call createRecord, it's calling **buildInternalModel** with 2 parameters, and not sending the data to the function. I've create a pull reqeust https://github.com/emberjs/data/pull/4210 for the same. Thanks

**Comment by locks** [comment]
Hi @ersuryapurohit.
Thank you for reporting this issue, but the emberjs/data repository was the right place to report it, since it doesn't seem to impact the guides.
