### ISSUE TITLE
[Quick Start] ember build --env production -- /scientist route returns 404 

### ISSUE THREAD

**Issue by earthquakesan** [emberjs/guides#1327]
Nodejs/npm installed with nvm: v5.8.0

Using the last version of the guide available at https://guides.emberjs.com/v2.4.0/getting-started/quick-start/

To reproduce the problem create a route "scientists" and try to navigate it as written in [Quick Start], when app is served after building it:
```
ember generate route scientists
ember build --env production
cd dist
python -m SimpleHTTPServer
```

The main page has no problem (by default http://localhost:8000/), however http://localhost:8000/scientist returns 404 error (obviously, http://localhost:8000/#/scientist works).

The problem is similar to the problem described in: https://github.com/stefanpenner/ember-app-kit/issues/486 (solution is to use rewrite rules of apache/nginx config).

I propose to provide an example how to run the app in the production env inside the quickstart. As I see it right now, the last part of quick start is very confusing. Is every ember application requires rewrite rules? (meaning that it would be broken otherwise)

**Comment by acorncom** [comment]
>  Is every ember application requires rewrite rules? (meaning that it would be broken otherwise)

That's the default (and normal way for an Ember app to be setup).  It's by no means the only option (and there are ways of retrofitting Ember into other systems as you're displaying), but I don't think we want to be documenting those as part of the Quick Start.  We're aiming to have the Quick Start be a quick and dirty overview instead of a comprehensive setup.

@locks Thoughts?  We could potentially mention PageFrontHQ, but that may be too prominent of a spot for one of the many options in the Ember ecosystem ...

@earthquakesan Would you be interested in working on a Deploying section (further down the sidebar) showing different ways of handling deploys if we decide to add that to the guides?

**Comment by locks** [comment]
@earthquakesan that is how all client-side routing works, you still need your server to respond to the URLs expected so it can serve the app. Here's the [Specifying the URL type](https://guides.emberjs.com/v2.4.0/configuring-ember/specifying-url-type/) guide, which is somewhat related. Like @acorncom says, we understand it might be a bit confusing, but we don't want too many details in the Quickstart.

I don't think a standalone guide on deploying would fit the guides quite well, [EmberWatch's cookbook](http://emberwatch.com/recipes) would be a better fit.
We will cover deploying as part of the tutorial, so hopefully that will be enough to clear doubts.

**Comment by earthquakesan** [comment]
@acorncom @locks at least a note that you can not just serve the dist/ folder and references for the further reading are required in the section imo.

**Comment by eighteight** [comment]
Is there a an example rewrite rules for apache2 somewhere? The motivation for the quick start guide to be "quick" is understandable, but not at the expense of it leading to a broken deployment, right?

**Comment by acorncom** [comment]
@eighteight We don't currently have example rewrite rules for Apache2.  If you work out what that takes, sending in a PR to http://emberwatch.com/recipes would be much appreciated!

**Comment by acorncom** [comment]
@eighteight Just saw some discussion of Apache2 rewrite rules here: http://builtbykrit.com/blog/deploying-ember-apps-to-aws-digitalocean-with-deploybot  Would you mind sending in a PR over on EmberWatch to save those for other folks in the future?  Thanks!

**Comment by eighteight** [comment]
@acorncom Thanks for the link. It will take me sometime to test that solution. If it works, I will submit a PR.

**Comment by Barnoid-** [comment]
Following the Quickstart I have been hit by same problem. Wasted a couple of hours on rewrite rules but didn't get it to work. What finally did the trick was the directive
  FallbackResource index.html
in the virtual host configuration of the Ember app. This should work for Apache 2.2.16 and above.

I would strongly suggest to put this information in the Building For Production section at the end of the Quickstart, or you may lose potential new users right there.
