### ISSUE TITLE
Property brace expansion in computed properties

### ISSUE THREAD

**Issue by adam-knights** [emberjs/guides#1340]
I only found out about property brace expansion by luck. The only official link to it that I can see is in the 1.4 blog post (http://emberjs.com/blog/2014/02/12/ember-1-4-0-and-ember-1-5-0-beta-released.html#toc_property-brace-expansion).

Suggest that a section is added to computed properties in the guide to show this handy shorthand syntax.

**Comment by acorncom** [comment]
Sounds good to me.  @adam-knights if you'd like to send in a PR, we'd be happy to take it :smile:
