### ISSUE TITLE
Inconsistency in specifying actions?

### ISSUE THREAD

**Issue by MarkMT** [emberjs/guides#1345]
In the section '[Templates - Actions](https://guides.emberjs.com/v2.4.0/templates/actions/)' the type of event to be handled by an action is specified using the `on` option inside the action helper as shown by this example -

`<button {{action "select" post on="mouseUp"}}>✓</button>`

A little further down the page, there's an explanation of how the `value` option can be used in the `action` helper and we're shown this example:

```
<input type="text" value={{favoriteBand}} onblur={{action "bandDidChange" value="target.value"}} />
```

Here the type of event to be handled is apparently specified by prefixing the helper with `onblur=` rather than using the `on` option inside the helper.

I haven't been able to find any other instance of this usage elsewhere in the guides but I have seen it [used](https://github.com/emberjs/ember.js/issues/13058#issuecomment-198552048) [elsewhere](https://github.com/emberjs/ember.js/issues/11678#issuecomment-132838923). Is it actually valid? Or deprecated?

I suggest either the two examples should be made consistent, or some clarification should be added to note that variant forms are allowed.

There is a second similar situation in the discussion of event handling for components. In the section '[Components - Handling Events](https://guides.emberjs.com/v2.4.0/components/handling-events/)' an example is given of passing an action to a component -

`{{drop-target action="didDrop"}}`

and then invoking the action using `sendAction` within the component -

```
export default Ember.Component.extend({
 ...
  drop(event) {
    let id = event.dataTransfer.getData('text/data');
    this.sendAction('action', id);
  }
});
```

But in the section '[Components - Triggering Changes with Actions](https://guides.emberjs.com/v2.4.0/components/triggering-changes-with-actions/)' there is an example that _appears_ to be doing the same thing, but with a slightly different sytax -

```
{{button-with-confirmation text="Click here to delete your account." onConfirm=(action "userDidDeleteAccount")}}
```

and then invoking the action in response to an internal event -

```
export default Ember.Component.extend({

  actions: {
    ...
    submitConfirm() {
      //call the onConfirm property to invoke the passed in action
      this.get('onConfirm')();
    }...
  }
});
```

When I look at the API documentation for [sendAction](http://emberjs.com/api/classes/Ember.Component.html#method_sendAction) and compare the examples there with those above, they seem to be doing the same thing - passing an external action to the component so it can be invoked in response to a local event. And `this.get('onConfirm')()` seems to do the same thing as `sendAction`.

I'm not an Ember expert at all so I could be mistaken, but if my understanding is correct it seems again that either the same syntax should be used in both cases or at least the variant usages should be pointed out.

**Comment by acorncom** [comment]
Thanks for bringing this up.  For your first question - "is it `{{action on="mouseUp"}}` or `<input onmouseup={{action}}`" - from what I'm able to track down it's both ;-)

Specifically, I'm looking at the API docs here under **Passing functions with the action helper**: http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_action

That section was updated as part of this PR (https://github.com/emberjs/ember.js/pull/11723/files)

Looking into it, it looks like `{{action on="mouseUp"}}` is an older syntax (you can see its introduction in this PR: https://github.com/emberjs/ember.js/pull/9606/files) whereas the `<input onmouseup={{action}}` seems to have been a syntax that Glimmer allows for.

As such, I think you'd be able to use either one, but might want to go with the `<input onmouseup={{action}}` approach, as that's more likely to be what is supported long-term.  Good suggestions about clarifying in the docs ;-)

Haven't had a chance to dive into your questions about components yet, will try to come back later.

@locks any comments here?  Would you agree with my assessment above?  Also, thoughts on how we should address this in the guides?

**Comment by MarkMT** [comment]
The part of this issue related to `sendAction` was addressed in https://github.com/emberjs/guides/commit/4f6e84ad701e03ef85e87be2299252f0d0197364. I'm closing this in favor of https://github.com/emberjs/guides/issues/1727 which deals with the remainder of what is contained here plus some other related concerns.
