### ISSUE TITLE
Document loading states more thoroughly

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1352]
We want to clarify and improve documentation about loading states more clearly, as they are fairly confusing.  See this Twiddle from Robert Jackson for examples: https://ember-twiddle.com/a77b3db275d91c7f34c2?numColumns=0

**Comment by acorncom** [comment]
Here's a StackOverflow question about the same problem: http://stackoverflow.com/questions/36346518/ember-loading-template-never-displaying

**Comment by acorncom** [comment]
Other background here: https://github.com/emberjs/ember.js/issues/13072#issuecomment-194605112

**Comment by alexspeller** [comment]
I did a recent talk on this, it might be helpful for an overview of the current state of affairs (I've been meaning to PR the guides but I got super ill and am way behind on real work):

http://alexspeller.com/loading-and-error-substates-in-ember/

**Comment by acorncom** [comment]
Sweet, thanks!

**Comment by rwjblue** [comment]
https://github.com/emberfest/diagonal-routes is a great resource also (thanks once again @alexspeller!).  It would be great to tackle [these issues](https://github.com/emberfest/diagonal-routes/issues) and update that demo with the current version...

**Comment by acorncom** [comment]
Closing this as the PR linked in above is merged.
