### ISSUE TITLE
Improve "Contributing"

### ISSUE THREAD

**Issue by locks** [emberjs/guides#1361]
# Contributing

Possibly introduce a new guide that covers more of the meta, explains the Ember family of projects, etc.

## [Main Repositories](https://guides.emberjs.com/v2.4.0/contributing/repositories/#toc_main-repositories)

Link to each project's contributing, maybe include a snippet or somesuch. If the project doesn't have a clear process, work with the maintainers to try and come up with one.

## [Libraries used by Ember](https://guides.emberjs.com/v2.4.0/contributing/repositories/#toc_libraries-used-by-ember)

Relevant? Easily maintainable?

**Comment by acorncom** [comment]
Per our docs meeting today, we're going to try to keep issues in guides to more actionable items unless we open RFC-type issues.  Closing this for now
