### ISSUE TITLE
Clarify use of dynamic segments when defining routes

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/guides#1364]
Need clarification on Dynamic Segments section, here: 

- https://guides.emberjs.com/v2.4.0/routing/defining-your-routes/#toc_dynamic-segments
- https://github.com/emberjs/guides/blob/master/source/localizable/routing/defining-your-routes.md#dynamic-segments

Regarding: https://github.com//emberjs/ember.js/issues/13254

"constraint intuitive not obvious" for unique names of dynamic segments, consider the clobbering behavior of doing the following…

```js
Router.map(function() {
  this.route("photo", { path: "photo/:id" }, function() {
    this.route("comment", { path: "comment/:id" });
  });
});
```

Both dynamic segments are the same name so the deepest one clobbers. All params are stored in a single POJO so the names need to be unique. Generally we would name these :post_id and :comment_id.

It should be clearer…

```js
Router.map(function() {
  this.route("photo", { path: "photo/:photo_id" }, function() {
    this.route("comment", { path: "comment/:comment_id" });
  });
});
```

…documentation needs a note to "never" use the same name for a dynamic segment.

**Comment by acorncom** [comment]
Agreed.  I've heard various people say this is a non-obvious, very painful bug to track down
