### ISSUE TITLE
Clarify recommended places to store assets

### ISSUE THREAD

**Issue by MarkMT** [emberjs/guides#1365]
In [Managing Dependencies](https://guides.emberjs.com/v2.4.0/addons-and-dependencies/managing-dependencies/), under the h2 heading 'Other Assets', it says -

> Assets not available as an addon or Bower package should be placed in the vendor folder in your project.

Later on the same page there's an h3 heading with the same name, 'Other Assets' (and the same link url) with this -

> All other assets like images or fonts can also be added via import(). By default, they will be copied to dist/ as they are.

Yet the [Ember-CLI documentation](http://ember-cli.com/asset-compilation) states that raw assets should go in `public/assets`, which is what I actually use. Presumably the advice above is correct for the particular situations they're meant to refer to, but the distinction isn't clear to me and as far as I've been able to find, the use of `public/assets` isn't mentioned in the ember.js guides at all.

**Comment by acorncom** [comment]
@locks comments here?

**Comment by locks** [comment]
The usual distinction is that `vendor` -> third-party assets, `public` -> your assets. That's basically what I have to say on the subject :P

**Comment by acorncom** [comment]
@MarkMT Is that discussion above clear enough?  Would you want to write something up for the guides on this?
