### ISSUE TITLE
Add example of using `{{some-component class="some-class"}}`

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#1372]
I think it would be useful to show an example of using `{{some-component class="some-class"}}` style of specifying classes for components [Customizing a Component's Element](https://guides.emberjs.com/v2.5.0/components/customizing-a-components-element/) section of the guides.

There are examples for customizing via `classNames` prop inside the component class but not from the template.

I'll have some time to do this tomorrow if this is wanted.

**Comment by acorncom** [comment]
Let's do it
