### ISSUE TITLE
Broken link for Ember CLI Deploy

### ISSUE THREAD

**Issue by nfriedly** [emberjs/guides#1376]
Both http://ember-cli.com/user-guide/#deployments and http://ember-cli.com/user-guide/#deployments and link to http://ember-cli.com/ember-cli-deploy/ for Ember CLI Deploy but that's a 404.

**Comment by acorncom** [comment]
Hmm, that's correct, they moved their website to a different location (http://www.ember-cli-deploy.com).  Would you be willing to open an issue over on the Ember-CLI repo (https://github.com/ember-cli/ember-cli/issues)?  We'll update our Quick Start here to fix the links in guides ...

Thanks!

**Comment by acorncom** [comment]
All links found in this search need to be updated as outlined above (https://github.com/emberjs/guides/search?utf8=✓&q=ember-cli-deploy)

**Comment by nfriedly** [comment]
Done. Want to close this one, or keep it open for now?

**Comment by acorncom** [comment]
We'll keep it open, the above items have to be fixed as well.  If you've got a minute, I'd be happy to merge a PR ;-)

**Comment by nfriedly** [comment]
Yea, I was going to send one that pointed to http://ember-cli.com/user-guide/#deployments but then I saw that it also had a Ember CLI Deploy link, and then I realized that one was broken too.. so I'm not sure where it should actually point.

**Comment by acorncom** [comment]
They should all point to http://www.ember-cli-deploy.com as I believe they'll keep that going for a long time ... ;-)

**Comment by locks** [comment]
Fixed by https://github.com/emberjs/guides/pull/1395.
