### ISSUE TITLE
Initializer code example results in failing test

### ISSUE THREAD

**Issue by ctcpip** [emberjs/guides#1381]
By following the example here:

https://guides.emberjs.com/v2.5.0/applications/dependency-injection/#toc_using-an-application-instance-within-an-instance-initializer

The result is an error in the test (automatically generated unit test) for the instance initializer:  undefined is not an object (evaluating 'logger.log')

**Comment by locks** [comment]
@ctcpip I'm not sure I understand the issue. `logger:main` is just an example name for a factory that the user might have registered in their application.

I'm not sure how to make that clearer, any suggestions?

**Comment by ctcpip** [comment]
If you register logger:main in the application initializer, and try to access it from the instance initializer (both exactly as described in the examples), the boilerplate unit test for the instance initializer fails when executing initialize() within test(), with the error message:

> undefined is not an object (evaluating 'logger.log')

**Comment by acorncom** [comment]
Hmm, yes, the boilerplate unit test would fail, as you've made a change to the instance initializer 😄 .  The error is related to the fact that the `logger:main` object which was registered in the container is not being properly mocked (or setup) in the test.  We need a page written about testing instance initializers, so if you have the time or inclination to send in a PR for that, it would be much appreciated! 👍 I'll close this for now though ...
