### ISSUE TITLE
Click helper accepts context

### ISSUE THREAD

**Issue by sethbrasile** [emberjs/guides#1386]
Looks like the `click` helper 

http://emberjs.com/api/classes/Ember.Test.html#method_click
https://guides.emberjs.com/v2.5.0/testing/acceptance/#toc_asynchronous-helpers

Accepts context as a second arg. Don't see anything about it in the guides. Just want to make sure that's on purpose!

**Comment by sethbrasile** [comment]
I don't see it here either https://github.com/emberjs/ember.js/blob/v2.5.0/packages/ember-testing/lib/helpers.js#L347-L349

But I do know of multiple cases of it working properly.

**Comment by acorncom** [comment]
Hmm, interesting.  Would you mind opening an issue in the https://github.com/emberjs/ember.js repo asking about whether we want to document it?  If we do, then yes, we'll update the guides ;-)

**Comment by faizaanshamsi** [comment]
I've opened a PR on ember.js, can update the guides as well if necessary. https://github.com/emberjs/ember.js/issues/13397

**Comment by locks** [comment]
Having checked out the guide in question, it should be simplified to only the helpers. They already link to the API docs, which should be consulted or details. This also avoids having the description get out of sync, as when the `click` API docs get updated.

**Comment by acorncom** [comment]
@locks that sounds like a vote to close this then and open a new issue re: adjusting guides content?
