### ISSUE TITLE
Update Models section to use the new import syntax

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1391]
In the new Ember Data blueprints, apparently things have changed to this:

```
import Model from 'ember-data/model';
import attr from 'ember-data/attr';

export default Model.extend({
    title: attr(),
    owner: attr(),
```

Whereas we still have `DS.Model` and `DS.attr` mentioned here: https://guides.emberjs.com/v2.5.0/models/defining-models/

**Comment by acorncom** [comment]
@locks how do we get folks to let us know about this ahead of time?  seems like something we missed on the 2.5 update?

**Comment by locks** [comment]
@acorncom ¯\_(ツ)_/¯

**Comment by toddjordan** [comment]
@acorncom should be like core has been doing - no docs no ship

**Comment by pangratz** [comment]
Sorry, I should have addressed this once emberjs/data#4331 got merged 😔 . I will create a PR to update this in the guides this weekend.

Also, I will try to remember this for future things, so this doesn't become an issue anymore!

Thanks btw for the hard work on keeping the guides up to date! 🚀

**Comment by pangratz** [comment]
Oh, looks like good guy @Gaurav0 already took care of this in #1375 ❤️

**Comment by locks** [comment]
We might try bridge the gap with some tooling, but it's such an unspecific space that I worry about adding even more overhead.
If everything was implemented in TS, maybe we could check the types :trollface: 
@pangratz ping us on Slack if you have any ideas.

**Comment by acorncom** [comment]
Sorry, hadn't checked `master` before posting ...
