### ISSUE TITLE
Tutorial Final Stage: Deploying to Surge (build error?)

### ISSUE THREAD

**Issue by ml242** [emberjs/guides#1417]
This might be a Surge issue but I came across it within the context of the tutorial. 

I have completed 'Super Rentals' and there are no errors in the server, but when I go to deploy I only get a blank page... I believe that there is a problem with the build process which returns the minified file, but I can't figure out what it is.

The error is:  "while processing route: index Unexpected token < in JSON at position 0 SyntaxError: Unexpected token < in JSON at position 0"

My repo is here: https://github.com/ml242/super-rental in case anyone thinks this could be an issue related to the tutorial or the build tool.

Otherwise, it was a pretty cool tutorial. Thanks.

**Comment by acorncom** [comment]
hey @ml242 , would you try it against https://www.pagefronthq.com and let us know if you have problems there too?  If you have problems with PageFront, it's likely to be your setup.  If you don't, then there may be some glitches with `surge.sh` ...  Thanks!

**Comment by locks** [comment]
That error is usually when you try to reach an external API and it returns an HTML error page instead of JSON, which would explain the `<` at position 0, since it would start with `<html doctype>`.

**Comment by ml242** [comment]
@acorncom Same error, thanks for the help.

**Comment by ml242** [comment]
@locks not sure where to begin debugging that.

In short, Ember server still works but ember build then deploy fails.

**Comment by locks** [comment]
Check the network tab when you're booting the deployed application.
If you come by your Slack we'll be able to help you better, not sure it's a problem with the guide :/

**Comment by ml242** [comment]
@locks agreed - probably not a guide issue.

**Comment by locks** [comment]
You can join at https://ember-community-slackin.herokuapp.com/, good luck!
