### ISSUE TITLE
Searching for 'resources' produces broken link

### ISSUE THREAD

**Issue by jacobq** [emberjs/guides#1423]
Reproduction steps:
1. Go to emberjs.com
2. Click 'Guides' link
3. Search for 'resources' in top-right search bar.
4. Click first link ("Managing Dependencies Between Controllers")
5. At this point you will see a 404 error page

https://guides.emberjs.com/v2.5.0/#stq=resources&stp=1 (search page that produces broken link)
https://guides.emberjs.com/controllers/dependencies-between-controllers/ (broken link)

**Comment by acorncom** [comment]
Thanks @jacobq we're actually working on replacing our search system (see #1184) so this issue should go away at that point.  I'll close this for now
