### ISSUE TITLE
At The Component Lifecycle page, 11 hooks are shown, but only some of them are described

### ISSUE THREAD

**Issue by ykaragol** [emberjs/guides#1430]
[At page where the Component Lifecycle is defined](https://guides.emberjs.com/v2.5.0/components/the-component-lifecycle/) there are 11 hooks are shown. But some of them doesn't have any description. 

On Initial Render:

1. **init : No definition**
2. didReceiveAttrs : Defined
3. **willRender : No definition**
4. didInsertElement: Defined, also when to use is described by an example.
5. didRender: Defined with an example

On Re-Render

1. didUpdateAttrs: Defined
2. _didReceiveAttrs: Same with initial render_ (Actually need to express: Is that really the same with initial render?)
3. **willUpdate: No definition**
4. **willRender: No definition**
5. **didUpdate: No definition**
6. _didRender: Same with initial render_

On Component Destroy

1. willDestroyElement: Defined
2. **willClearRender: No definition**
3. **didDestroyElement: No definition**

In a component lifecycle document, there should also be a section about when a binding is established.

**Comment by locks** [comment]
This is mostly by design. The Guides are not exhaustive, and they're mostly driven by use cases. As the [Lifecycle Hook Examples](https://guides.emberjs.com/v2.5.0/components/the-component-lifecycle/#toc_lifecycle-hook-examples) says, they're only some examples of how to use the hooks.

The API docs are the exhaustive ones, though at the moment the lifecycle hooks aren't thoroughly documented for outstanding reasons.

**Comment by ykaragol** [comment]
Sure. But then we need the following use cases:

1. How to set up initial values? 
2. In case of parent component passing undefined as a property value, how to keep stable the state of the component?

Also, is `init` really a hook?

**Comment by locks** [comment]
> 1. How to set up initial values?

`init`, like a regular object and like shown in the code sample you linked.

> 2. In case of parent component passing undefined as a property value, how to keep stable the state of the component?

Sorry, I don't understand this question.

> Also, is `init` really a hook?

Yes, it's a method that's called by JavaScript/Ember that you can override to supply your own additional logic.

**Comment by ykaragol** [comment]
OK. Thank you.

**Comment by locks** [comment]
If you want to discuss this further, and help fleshing out the API documentation, reach us at `#-learning` on the Slack group.
