### ISSUE TITLE
Not enough contrast between links and other text

### ISSUE THREAD

**Issue by carlbennettnz** [emberjs/guides#1450]
I'm very, very mildly color-blind, but I can't distinguish links at all. It all looks the same to me. A higher contrast color combination or a simple underline would help.

**Comment by nathanhammond** [comment]
@carlbennettnz Thank you for bringing this up! Our color stack is on our list of things to address, and we're working toward a resolution over here: https://github.com/ember-a11y/issues/issues/1

For now, we can fix this here: https://github.com/emberjs/guides/blob/a1bbe899a2224449557c4c1b615e12a0a0ffa36f/source/stylesheets/base/_typography.scss#L47

By adding: `.chapter a { text-decoration: underline; }`?

**Comment by carlbennettnz** [comment]
❤️

**Comment by carlbennettnz** [comment]
@nathanhammond Hey, could we reopen this please? We lost the underline again a few months ago. The fix is still on master, but it's missing from the actual site.

**Comment by carlbennettnz** [comment]
Actually, #1458 only added underlines to links in the footer. Not sure this was ever fixed.

**Comment by acorncom** [comment]
@carlbennettnz Just re-opened this.  Would love to get help on this if you have the time.  At the moment, the learning team is pretty crunched on time, but help is gladly accepted!
