### ISSUE TITLE
Super Rentals app doesn't work when deployed with Surge

### ISSUE THREAD

**Issue by sotojuan** [emberjs/guides#1470]
If you follow the guide correctly and deploy to surge, you get a blank screen with these errors in the console:

<img width="582" alt="screen shot 2016-06-07 at 2 32 27 pm" src="https://cloud.githubusercontent.com/assets/8217766/15871959/b1913df4-2cbc-11e6-8fcc-1d95f6873452.png">

**Comment by sotojuan** [comment]
Closing because it works now.

**Comment by locks** [comment]
Glad it resolved :) I reached out on the Slack channel, but you may have missed it.

**Comment by gr2m** [comment]
not working for me? https://calm-shop.surge.sh/ I guess because of the data mocking locally? @sotojuan did you do anything to make it work?

**Comment by sotojuan** [comment]
No, just tried it again later. @GavinJoyce had the same experience, maybe he can help.

**Comment by gr2m** [comment]
`ember build --env=development` did the trick for me

**Comment by sotojuan** [comment]
Maybe that should be added to the docs or looked into? @locks

**Comment by acorncom** [comment]
See #1487  , we've got a PR in for that :-)
