### ISSUE TITLE
Models/Customizing Serializers

### ISSUE THREAD

**Issue by gossi** [emberjs/guides#1472]
Hey guys,

I just copied a malfunction code sample from the guides. It is from: https://guides.emberjs.com/v2.5.0/models/customizing-serializers/

The relevant code sample is:

```
import JSONSerializer from 'ember-data/serializers/json';

export default JSONAPISerializer.extend({
...
```

See the difference between _JSONSerializer_ and _JSON**API**Serializer_, which wouldn't work. There are some examples on this page, that I see are wrong. I'm a beginner, so I don't know which is the proper serializer to use (though I realized `JSONAPISerializer` works =)). I'm sure you know the proper way to correct this.

Thank you guys!

**Comment by locks** [comment]
This is currently addressed in https://github.com/emberjs/guides/pull/1471. Thanks for pointing it out, and sorry about the inconvenience!
