### ISSUE TITLE
Tutorial: Creating a Handlebars Helper – issue with template update

### ISSUE THREAD

**Issue by gr2m** [emberjs/guides#1481]
I started the tutorial yesterday and am continuing today, maybe you changed something or I missed something, but on the [Creating a Handlebars Helper](https://guides.emberjs.com/v2.6.0/tutorial/hbs-helper/) part, the update to `app/templates/components/rental-listing.hbs` breaks things for me.

- For one the code does not show added / removed lines like in the pages before.
- It changes the CSS classes, e.g. `detail owner` to just `detail`, by accident?
- it adds the `location-map` helper which has not been implemented yet

```diff
diff --git a/app/templates/components/rental-listing.hbs b/app/templates/components/rental-listing.hbs
index a343b2f..070cb70 100644
--- a/app/templates/components/rental-listing.hbs
+++ b/app/templates/components/rental-listing.hbs
@@ -4,16 +4,17 @@
 <article class="listing">
   <a {{action 'toggleImageSize'}} class="image {{if isWide "wide"}}">
     <img src="{{rental.image}}" alt="">
     <small>View Larger</small>
   </a>
   <h3>{{rental.title}}</h3>
-  <div class="detail owner">
+  <div class="detail">
     <span>Owner:</span> {{rental.owner}}
   </div>
-  <div class="detail type">
-    <span>Type:</span> {{rental.type}}
+  <div class="detail">
+    <span>Type:</span> {{rental-property-type rental.type}} - {{rental.type}}
   </div>
-  <div class="detail location">
+  <div class="detail">
     <span>Location:</span> {{rental.city}}
   </div>
-  <div class="detail bedrooms">
+  <div class="detail">
     <span>Number of bedrooms:</span> {{rental.bedrooms}}
   </div>
+  {{location-map location=rental.city}}
 </article>
```

If you give me a little guidance I can send a PR to fix it. Thanks!

**Comment by toddjordan** [comment]
hmm.  I'll take a look.  That file should not have been updated yesterday :-(

**Comment by toddjordan** [comment]
ok, I get what's going on...

We made lots of updates to improve the tutorial for style, but the handlebars helper section was not updated.  Plus it was updated when we added the service, but should not have been with the map.

To fix, make the markup similar to what was defined in simple-component.md (except now with the helper callouts) and remove the map component call.

```hbs
  <article class="listing">
    <h3>{{rental.title}}</h3>
    <div class="detail owner">
      <span>Owner:</span> {{rental.owner}}
    </div>
    <div class="detail type">
      <span>Type:</span> {{rental.type}}
      <span>Type:</span> {{rental-property-type rental.type}} - {{rental.type}}
    </div>
    <div class="detail location">
      <span>Location:</span> {{rental.city}}
    </div>
    <div class="detail bedrooms">
      <span>Number of bedrooms:</span> {{rental.bedrooms}}
    </div>
  </article>
```
Then updated the filename at the top of the code block to reflect changed lines, like:
`/app/templates/components/rental-listing.hbs{-7,+8}`

**Comment by gr2m** [comment]
Okay on it, thanks for the advise! I’ll leave in the image, as it was added on the step before:
https://guides.emberjs.com/v2.6.0/tutorial/simple-component/#toc_hiding-and-showing-an-image

**Comment by toddjordan** [comment]
updated the snippet above to add in the image
