### ISSUE TITLE
Tutorial: Building a Complex Compoment not working for me

### ISSUE THREAD

**Issue by gr2m** [emberjs/guides#1482]
After I followed the instructions to add the complex component, no rentals are shown any longer. Here is the diff (together with two steps before, bu they were minor and worked): https://github.com/gr2m/super-rentals/commit/7b03bd67811287c996bd5832964232c5660c7927

![dafuq](https://cloud.githubusercontent.com/assets/39992/15965514/68244602-2eec-11e6-95fe-a533a76cc3ab.gif)

**Comment by toddjordan** [comment]
@gr2m we made some fixes to the tutorial yesterday afternoon and I think one should address that.  Can you verify?

**Comment by toddjordan** [comment]
I'll try the tutorial steps out for this and make sure too.

**Comment by courajs** [comment]
https://github.com/gr2m/super-rentals/commit/7b03bd67811287c996bd5832964232c5660c7927#commitcomment-17822592

**Comment by toddjordan** [comment]
yeap, that's it.  Good find.  That fix didn't make it back.

**Comment by toddjordan** [comment]
@courajs @gr2m can you review the pr and make sure it works for you?

**Comment by gr2m** [comment]
@toddjordan yes, @courajs’ fix makes it work again

**Comment by toddjordan** [comment]
sorry, I meant my PR https://github.com/emberjs/guides/issues/1483

**Comment by gr2m** [comment]
done. I applied the exact change to my local code and it fixed it: https://github.com/gr2m/super-rentals/commit/f71b880275d1c6d62b99e7de57d6e73d840ccbb1

**Comment by toddjordan** [comment]
Thank you so much for reporting this.  We'll try to get it back on the site asap

**Comment by toddjordan** [comment]
fix merged... closing issue.
