### ISSUE TITLE
Why use a component (Tutorial)

### ISSUE THREAD

**Issue by jsmestad** [emberjs/guides#1485]
I was reading the updated [simple-components](https://github.com/emberjs/guides/blob/master/source/localizable/tutorial/simple-component.md) tutorial which is a great improvement. There is something going unsaid though. 
- What functionality makes a good candidate for a component exactly?
- What functionality is too minor or small in scope to justify moving to a component?
- Can using a component too often lead to over-architecting a solution?

It is minor, but the guides as a whole never address this (that I've seen thus far). If there is a 3rd party resource on the subject i think even a link to that would be helpful.

/cc @acorncom

**Comment by acorncom** [comment]
@toddjordan Got any thoughts here?

**Comment by locks** [comment]
> What functionality makes a good candidate for a component exactly?

It's the only way to abstract a piece of your template. In other words, it's the only way to give a piece of your template a name.

> What functionality is too minor or small in scope to justify moving to a component?

None.

> Can using a component too often lead to over-architecting a solution?

Yes, as with anything.

**Comment by theroncross** [comment]
I would say any structure that is both repeated and has data/interaction-dependent behavior should probably be a component.

**Comment by toddjordan** [comment]
In the last revision of this page (~march) we added some additional intro text around the first component tutorial page: https://guides.emberjs.com/v2.13.0/tutorial/simple-component/

Going to close this issue as resolved.  Thanks for reporting.
