### ISSUE TITLE
application.hbs missing from quick-start tutorial

### ISSUE THREAD

**Issue by atsheehan** [emberjs/guides#1491]
I'm new to Ember so I'm not sure if I'm missing something obvious, but I ran into a slight snag during the quick-start tutorial at [https://guides.emberjs.com/v2.6.0/getting-started/quick-start/](https://guides.emberjs.com/v2.6.0/getting-started/quick-start/).

In the [Create a New Application](https://github.com/emberjs/guides/blob/a20a8f57d12e1f2b1e49c21630dcbe5fb895d1a4/source/localizable/getting-started/quick-start.md#create-a-new-application) section, it references the `app/templates/application.hbs` file:

> Switch to your editor and open app/templates/application.hbs. This is called the application template and it is always on screen while the user has your application loaded.

> In your editor, change the text inside the &lt;h2&gt; from Welcome to Ember to PeopleTracker and save the file.

This file didn't exist in the newly created application. The `templates` directory just contained a `components` subdirectory:

```
$ tree app/templates
app/templates
└── components
```

I created a simple `app/templates/application.hbs` file with the following contents:

```
<h2>PeopleTracker</h2>
```

That seemed to work, but when adding the `/scientists` route I had to add `{{outlet}}` to the file for the additional markup to appear:

```
<h2>PeopleTracker</h2>

{{outlet}}
```

This also worked, but I don't know if that's what the `app/templates/application.hbs` file should contain. It seems that the tutorial assumes the `app/templates/application.hbs` file already existed. It would be helpful if it contained an example of what the complete file should look like.

## Versions

```
$ node --version
v6.2.1

$ npm --version
3.9.3

$ npm install -g ember-cli@2.6
$ ember --version

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.6.1
node: 6.2.1
os: darwin x64

$ ember new ember-quickstart
$ cd ember-quickstart
$ ember server
```

**Comment by vjrngn** [comment]
You're right. I'm going through the guide as well and don't see the Application.hbs file.

**Comment by acorncom** [comment]
Confirmed. That's a new change in 2.6 that we haven't put in yet. For now, do a "ember g template application" and you should be set

**Comment by thardraved** [comment]
Typing "ember g template application" not working

```
$ ember g template application 
/usr/lib/node_modules/ember-cli/bin/ember:11
  basedir: process.cwd()
                   ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.<anonymous> (/usr/lib/node_modules/ember-cli/bin/ember:11:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

**Comment by jamesskyoung** [comment]
Looking at Angular 2 vs Ember.  Started the tutorial and ran into this.  First impressions are important.  You'd be amazed at how such a small thing can influence people.

**Comment by locks** [comment]
@jamesskyoung we are doing the best we can, but we're only human

**Comment by keinchy** [comment]
ran into the same issue but ran into this thread with answer fairly quickly. Maybe less then 5 minutes... no complains here.

**Comment by ladyleet** [comment]
this thread was super helpful! almost had a panic attack and thought something drastic had changed after upgrading to 2.7.0!! hahaha :)
