### ISSUE TITLE
"Creating your app" step is a little outdated

### ISSUE THREAD

**Issue by jzaefferer** [emberjs/guides#1498]
At the end of https://guides.emberjs.com/v2.6.0/tutorial/ember-cli/ the guide says: "If we navigate to localhost:4200, we'll see our brand new app displaying the text "Welcome to Ember"."

Instead, in Ember(-cli) 2.6.0, it shows the Ember mascot with a hardhat and "Congratulations, you made it!" and some more text. Also `app/templates/application.hbs` is gone (the quickstart guide relies on that file).

PS: Hope someone appreciates these tickets, there's probably more coming as I make my way through the tutorial.

**Comment by acorncom** [comment]
@jzaefferer Thanks, it's something we've known was in there, but hadn't had a chance to fix yet.  Would you be able to send in a PR with a note about creating the application.hbs file?

And yes, all tickets are helpful, PRs are even better ;-)

**Comment by jzaefferer** [comment]
So ember-cli doesn't create that template anymore, but the user should create it as part of the tutorial?

**Comment by acorncom** [comment]
Correct.  There is a new add-on that we added to Ember-CLI (https://github.com/ember-cli/ember-welcome-page).  As part of that, the standard `templates/application.hbs` was removed from Ember-CLI's standard blueprint.

**Comment by acorncom** [comment]
This was closed by the PR referenced above ...
