### ISSUE TITLE
Suggestion: Example showing defaultValue as a function in defining-models

### ISSUE THREAD

**Issue by fredguth** [emberjs/guides#1512]
In:
https://github.com/emberjs/guides/blob/master/source/localizable/models/defining-models.md

there should be an example showing that default value can also be a function.  As in: http://emberjs.com/api/data/classes/DS.html#method_attr

**Comment by locks** [comment]
@fredguth why? the API documentation seems like the proper place for it

**Comment by fredguth** [comment]
@locks: Only because when you want to set the defaultValue of an attr without transform, it is not clear that the options is not the second parameter, but the only param. 

Maybe the right place is the API, anyway, or there could be a link from this guide to http://emberjs.com/api/data/classes/DS.html#method_attr

**Comment by acorncom** [comment]
@fredguth We just put in a link to `attr`, thanks for the suggestion
