### ISSUE TITLE
Inconsistent localhost links

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/guides#1514]
I've noticed some inconsistencies with the way `localhost` links are presented in the guides, and I'd like to do a quick PR to make them consistent. Just wanted to see if anyone had a preference first. The two styles I've seen are:

1. Not linked, `http://` not shown, backticks, e.g. `localhost:4200/about`
2. Linked, `http://` shown, no backticks, e.g. [http://localhost:4200/about](http://localhost:4200/about)

I could do either of those, or a third option:

3. Linked, `http://` shown, with backticks, e.g. [`http://localhost:4200/about`](http://localhost:4200/about)

Preferences?

**Comment by rwjblue** [comment]
I personally like the last option, but any consistency is better than mixed...
