### ISSUE TITLE
Fix links to Ember Inflector source code in API docs

### ISSUE THREAD

**Issue by thomascchen** [emberjs/guides#1538]
The links to the Ember Inflector source code in the API docs are broken. This is true for all of the methods on the [Ember.Inflector](http://emberjs.com/api/data/classes/Ember.Inflector.html) page and the [Ember.HTMLBars.helpers](http://emberjs.com/api/data/classes/Ember.HTMLBars.helpers.html) page.

Clicking on the link, for example, to [node_modules/ember-inflector/addon/lib/system/inflector.js:154](https://github.com/emberjs/data/tree/v2.6.0/node_modules/ember-inflector/addon/lib/system/inflector.js#L154) for the `disableCache` method leads to a 404.

<img width="403" alt="screen shot 2016-06-26 at 8 54 25 pm" src="https://cloud.githubusercontent.com/assets/11340361/16366137/40d72abe-3be0-11e6-9377-2f230b2dd12d.png">

**Comment by locks** [comment]
Thank you for bringing this to our attention @thomascchen, but this should be filed under https://github.com/emberjs/ember.js, as the API documentation, and related links, are extracted from inline JSDoc comments.
I've moved the issue there and mentioned you.

**Comment by thomascchen** [comment]
Thank you @locks !
