### ISSUE TITLE
a 404 error page of  guides

### ISSUE THREAD

**Issue by zhengjunwei** [emberjs/guides#154]
[see this page of understanding ember.js](http://guides.emberjs.com/understanding-ember/keeping-templates-up-to-date)

**Comment by trek** [comment]
Can you tell us where you the link that lead there? The 404 in itself isn't actionable as that page does exist correctly in the each revision of a guide: http://guides.emberjs.com/v1.10.0/understanding-ember/keeping-templates-up-to-date/
