### ISSUE TITLE
Google Maps requires API key - tutorial broken

### ISSUE THREAD

**Issue by EvanKnowles** [emberjs/guides#1554]
The tutorial is currently broken, with the message:

testem.js:785 This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

It seems that, in general, the Google Maps API should be loaded from Google and not cached locally in  any case.

**Comment by toddjordan** [comment]
@EvanKnowles The tutorial seems to work for me, but I do get the message you mention above.  I believe this is because Google will give you a certain number of map lookups without a key for your server (and then requires you to pay them).  For the purpose of an intro tutorial, I'm ok with that limitation.  

It will probably be simpler for people downloading the tutorial source to just have a link to google for the library.  We went the vendor route at first to introduce that concept to new users.  It worth holding this open for now to explore alternatives.

**Comment by ve3** [comment]
I confirm this error. Does anyone show an example how to set the Google Maps API key?

**Comment by toddjordan** [comment]
@ve3 I/you do not need the api key to get the tutorial working locally.  You'll get a warning but the maps should show.  If the maps do not show you may need to re-run the curl command.  You shouldn't need a key for the purposes of initial running the tutorial.  The curl approach may not be the best way to incorporate the google maps library, but it was done to demonstrate how one might include a third party vendor library.  We'll research alternatives that are more intuitive for tutorial followers.

**Comment by ve3** [comment]
If no API key, the maps do not show. Re-run curl nothing change.
For me, it needs API key.

**Comment by toddjordan** [comment]
odd.  historically you've been allowed to use the api without a key up to a per day limit.  I just tried it on a local copy of the super-rentals repo and map display works still.  will have to research some more.  An alternative would be to update index.html with maps in one of the script tags and delete the js file from vendor.  You can see this in the super-rentals repo: https://github.com/ember-learn/super-rentals

**Comment by pmaisonnave** [comment]
If think ve3 is right: as announced by Google Geo Developpers, keyless access is no longer supported (but I was said it might still be the case for some "trusted" hosts) : see the following link:

[Building for Scale: Updates to Google Maps APIs Standard Plan](https://googlegeodevelopers.blogspot.fr/2016/06/building-for-scale-updates-to-google.html
)

**Comment by serproqnx** [comment]
Same error, can't complete tutorial :(

**Comment by mtrenkmann** [comment]
The last two days I worked through the entire tutorial (v2.10.0) and initially had the same issue that the maps were not displayed. Strangely, while following the last step of the tutorial (Adding Nested Routes) the maps showed up - and still I do not use any API key. I cannot tell for sure, but the only explanation to me is that I just forgot to Ctrl-S all of my open files - really annoying, can't believe it. So check that first.

**Comment by kennyadsl** [comment]
I had the same issue with a `gmaps.js` file I downloaded (with curl following the tutorial code) some days before using it. I think it also has some timing limit because downloading the file again fixed the javascript errors for me.

**Comment by joewoodhouse** [comment]
I think it is quite clearly against Google's terms & conditions to download the javascript library as the tutorial recommends, so I would suggest this be updated?

**Comment by toddjordan** [comment]
yes.  in plan to change the way we incorporate maps.  

Originally we took the vender approach to show how to integrate 3rd party libraries.  I think we would like to keep a similar approach, so we will approach the issues as follows:

* Investigate other map solutions to see if there is an alternative to google maps that we can download the client with.
* If none exist, we will change the approach, probably to either add the gmaps script definition to index.html.

**Comment by getaclue** [comment]
@toddjordan just my 2 cents... how about a third option (for now)? leave the curl as it is with a small modification ala
```
https://maps.googleapis.com/maps/api/js?v=3&key=YOUR_API_KEY
```
and then have a notice that you have to go into the `vendors/gmaps.js` to replace `YOUR_API_KEY` string with your API key?

This way, if they mess up a step somewhere in this section of the tutorial then they will at least know which file they have to go and modify (and which string to look for). I don't think it is too much work for an end user for now?

Cheers,
ALex

**Comment by toddjordan** [comment]
Update:  Currently working on a solution.  What we have now works on localhost, but with gmaps now you need the key to deploy it somewhere remotely.  doing some deployment-related work for the tutorial that this will be a prereq for.

**Comment by danaoira** [comment]
I feel like the tutorial adding the Google Maps API key is not very clear...

I am trying to add Google Maps API Key through CMD line, so I put this into the console.

![image](https://user-images.githubusercontent.com/2514403/28455106-ae7d1574-6db2-11e7-8734-313500daf6bf.png)

Instead, I get this error:
![image](https://user-images.githubusercontent.com/2514403/28455093-a394c01c-6db2-11e7-80a3-8221f63142ae.png)

Is there something I'm missing? Should I be putting the API key in the environment.js file? I also am not sure how to do that since there are no references on doing so.

Thanks in advance.

**Comment by toddjordan** [comment]
@danaoira the tutorial is describing the command you would run in a unix environment.  For windows we need to run `set GOOGLE_MAPS_API_KEY <your key>`

will create a new issue to update the text to accomodate windows users as well.

**Comment by curgery** [comment]
Thank you Mr. Jordan......
RLG
