### ISSUE TITLE
New greens for hbs code are hard to read

### ISSUE THREAD

**Issue by shawnam** [emberjs/guides#1566]
The greens in the handlebars templates are hard to read against white. I think this changed relatively recently? Though I looked through the latest merged PRs and didn't find an obvious change for this in particular off hand.

![screen shot 2016-07-18 at 9 06 35 am](https://cloud.githubusercontent.com/assets/747707/16917377/f8f48082-4cc6-11e6-8007-1536de715c71.png)

**Comment by toddjordan** [comment]
seems to be more a problem with the API doc than the guides (which use a black background), but yeah, yuck.

**Comment by toddjordan** [comment]
Seems to be related to some new styles brought in to support search.  will need to tweak the styles.  https://github.com/emberjs/website/commit/8d509c72a393670cb12e1bf2666d0aae4df53c0f

**Comment by shawnam** [comment]
Thanks, Todd. Should I re-file my issue over in the other repo, then?

**Comment by toddjordan** [comment]
already fixed https://github.com/emberjs/website/pull/2646  You should see it better now on the site
