### ISSUE TITLE
Tutorial Services and Utilities: Unit Tests Don't Pass for location-map

### ISSUE THREAD

**Issue by ryanolsonx** [emberjs/guides#1568]
In the beginning of the [Fetching Maps With a Service](https://guides.emberjs.com/v2.6.0/tutorial/service/#toc_fetching-maps-with-a-service) section, the tutorial mentions that "Now we have a passing component integration test" we can continue on.  The test for this component isn't working for me, even after I copy and paste the test code and component code to ensure accuracy.  All of my other tests are passing.

Given that I'm new to Ember, I don't know how to correct this. I don't know anything about services (or mock services).

For reference, you can check out my current place in the tutorial at my [github project](https://github.com/ryanolsonx/super-rentals) for it or for this section of the tutorial, [this commit](https://github.com/ryanolsonx/super-rentals/commit/d1fad1bd6ee3ee670ce5b36bdd97c21311ad5a1b) that I made with the changes listed in this section.

**Comment by locks** [comment]
Can you paste the message of the failing test please?

**Comment by ryanolsonx** [comment]
Sorry, I meant to add that.. here it is: 

> Global error: TypeError: undefined is not an object (evaluating 'this.get('maps'
> ).getMapElement') at http://localhost:7357/assets/super-rentals.js, line 69

**Comment by toddjordan** [comment]
@ryanolsonx the tutorial is in github at https://github.com/emberjs/super-rentals and all tests pass.  Hopefully that can give you some insight into what's going wrong.

**Comment by toddjordan** [comment]
I'll also try to see if there's a discrepancy between the github repo and guides

**Comment by Serabe** [comment]
The failing test is the acceptance test. That test is fixed later in the section [Stubbing services in acceptance tests](https://guides.emberjs.com/v2.6.0/tutorial/service/#toc_stubbing-services-in-acceptance-tests).

The paragraph you link states:

> Now we have a passing component integration test, but no maps showing up when we view our web page.

But does not say that the acceptance test now is failing. Maybe adding a few words about it would make it clearer. What do you think, @toddjordan, @locks ?

**Comment by toddjordan** [comment]
Thanks @Serabe !  Yeah I'm for clarifying there.  We can keep this issue open to track making this clearer.

**Comment by ryanolsonx** [comment]
OK this makes sense. Thanks for looking into this @Serabe . It just really confused me and I would imagine that it could confuse others as well.  I think that it would make things much more clear to mention that our other test will be failing now.

**Comment by toddjordan** [comment]
closing as fixed...
