### ISSUE TITLE
Clarify RSVP use in an Ember app

### ISSUE THREAD

**Issue by pixelhandler** [emberjs/guides#1585]
When reading the API Docs and the Guides, the ready has to take a leap regarding the use of RSVP… the API docs don't mention "Ember.RSVP" only "RSVP" and the guides sprinkle in "Ember.RSVP" so when you look at the API docs you have to insert "Ember." when you read if you know to do so.

Per chat in Slack, We should `import RSVP from 'rsvp'` (or whatever it is) and remove "`Ember.`" from "`Ember.RSVP`"

**Comment by yawboakye** [comment]
@pixelhandler I'm glad to take up this work. But first I need to confirm that Ember doesn't change `RSVP` in any way that makes it not a good idea to use `RSVP` right out of `rsvp` package. I'm looking at https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/rsvp.js and comment on [#L93](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/index.js#L93) and it looks like we could lose significant configuration that way. I think it needs core's attention.
cc/ @stefanpenner @rwjblue

**Comment by pixelhandler** [comment]
@yawboakye we had a chat discussion on this issue on slack last Friday. @locks liked the idea of removing the "Ember." from the RSVP use in guides.

See: https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/index.js#L209

The comment you mentioned `import RSVP from 'ember-runtime/ext/rsvp';     // just for side effect of extending Ember.RSVP` I think means `Ember.RSVP = RSVP;`  

The confutation of RSVP in Ember would still happen regardless of how developers import RSVP or use Ember.RSVP, e.g. https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/rsvp.js#L9-L15 would not be impacted by a developer using `import * as RSVP from 'rsvp';` then just using `RSVP` instead of `Ember.RSVP` via `import Ember from 'ember';` since `Ember.RSVP = RSVP;`

**Comment by pixelhandler** [comment]
@locks @yawboakye here is an example of a change I'm making to an addon based on this "clarification" https://github.com/pixelhandler/ember-jsonapi-resources/pull/90/files (tests are passing via Travis builds use Ember v1.13 - Canary v2.9) and running the branch in my app works fine)

**Comment by yawboakye** [comment]
:+1: @pixelhandler I'll have the changes pending while I wait for comments from core. Then the PR will be on its way :smile:

**Comment by pixelhandler** [comment]
@yawboakye See #1590 I commented on a few places we can use imports for `RSVP`.

**Comment by yawboakye** [comment]
@pixelhandler Seen. They should go in separate PRs though
cc/ @locks

**Comment by pixelhandler** [comment]
@stefanpenner @rwjblue can you please confirm we should use imports for RSVP use in the guides cc/ locks, @yawboakye would like confirmation.

**Comment by pixelhandler** [comment]
@yawboakye thanks!

**Comment by pixelhandler** [comment]
Fixed by #1591
