### ISSUE TITLE
Redo the DS import lines

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1597]
We had an Ember Data mixup that made it into the guides.  We need to clean things up at this point:

Revert the changes:
- [x] 2.3 (https://github.com/emberjs/guides/pull/1595)
- [x] 2.4 (https://github.com/emberjs/guides/pull/1594)
- [x] 2.5 (https://github.com/emberjs/guides/pull/1596)
- [x] 2.6 (already done)

Rebuild the docs and commit changes to the guides.emberjs.com repo
- [x] 2.3
- [x] 2.4
- [x] 2.5
- [ ] 2.6

**Comment by ryanlitalien** [comment]
@acorncom Got here from the deprecation warning. Should I be using `DS.Model` or just `Model`?

**Comment by acorncom** [comment]
@ryanlitalien Use `DS.Model`.  Examples shown at https://guides.emberjs.com/v2.10.0/models/defining-models/ are accurate for all the latest point releases of Ember Data
