### ISSUE TITLE
Compile CSS issue: cannot compile css due to source/images/about/header-text.png being missing

### ISSUE THREAD

**Issue by nicolechung** [emberjs/guides#16]
I am getting the above error when compiling CSS. However that image does not exist in the source.

**Comment by jbrown** [comment]
@nicolechung I've had the same issue since 3cfdd0c9cebf21032dad5fa94a3325f1328cad2b

**Comment by nicolechung** [comment]
Did that folder just get deleted by accident? It looks like images/about/ "images" are still being used on the live site.

**Comment by jbrown** [comment]
@nicolechung I would think it's intentional, this repo is only meant for the guides. I think that commit just missed the corresponding css.

**Comment by trek** [comment]
@nicolechung you might just need to `git pull`. I think this got fixed earlier today.

**Comment by nicolechung** [comment]
That works, thanks.
