### ISSUE TITLE
A code example has incorrect language for syntax highlighting selection

### ISSUE THREAD

**Issue by mrosata** [emberjs/guides#1618]
At LN 55 in the file `the-component-lifecycle.md`, there is a handlebars example that is demonstrated in a code fence labeled as javascript.

`/app/templates/components/profile-editor.hbs`
\`\`\`js  

rather than 

`/app/templates/components/profile-editor.hbs`
\`\`\`hbs

The same error is present in `components-lifecycle.de-DE.md` file, but I didn't make a change to that because `CONTRIBUTING.md` states only to edit english files.

**Comment by acorncom** [comment]
Closed by #1619
