### ISSUE TITLE
Do we need the mirage namespace in v2.8.0?

### ISSUE THREAD

**Issue by Letladi** [emberjs/guides#1642]
Hi guys, I just started exploring ember yesterday and I'm currently doing the super rentals tutorial. In the 'Installing Addons' section, the reader is instructed to install the 'mirage' add-on and add the following code to 'mirage/config.js';
```js
export default function() {
  this.namespace = '/api';

  this.get('/rentals', function() {
    return {
      data: [/** the data to return **/]
    };
  });
}
```
... with the following comment;
> This configures Mirage so that whenever Ember Data makes a GET request to `/api/rentals`, Mirage will return this JavaScript object as JSON. In order for this to work, we need our application to default to making requests to the namespace of `/api`. Without this change, navigation to `/rentals` in our application would conflict with Mirage.

And the reader is instructed to generate an adapter, which I did. Unfortunately this causes the following error;
```
Your Ember app tried to GET '/rentals',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file. Did you forget to add your namespace?
```

removing the namespace definition;
```js
export default function() {
  this.get('/rentals', function() {
    return {
      data: [/** the data to return **/]
    };
  });
}
```
and also removing it from 'app/adapters/application.js';
```js
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  //namespace: 'api'
});
```
removes the above error and the page loads as expected. Any clarification here would be appreciated. 
These guides are the most well-written I've ever read and gone through. Thank you.

**Comment by Serabe** [comment]
Hello, @letladi. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Thank you!

**Comment by Serabe** [comment]
(BTW, my nick is the same in Slack :+1:)

**Comment by Serabe** [comment]
Wrong repo, my bad.

**Comment by Letladi** [comment]
Thank you Serabe, I will do that!

**Comment by Serabe** [comment]
Solved the issue in Slack. It started working after a hard-reload of the page.
