### ISSUE TITLE
emq.globalize() reference is no longer valid

### ISSUE THREAD

**Issue by ryanmurakami** [emberjs/guides#165]
The current version of Ember-Qunit no longer uses the .globalize() function:
https://github.com/rwjblue/ember-qunit/commit/8b586de3a36d1ea52d9d82d9de848166f07eb2fd

Currently in both 1.11 & 1.10, the Unit Test Helpers article still instructs users to call this function:
http://guides.emberjs.com/v1.10.0/testing/unit-test-helpers/
http://guides.emberjs.com/v1.11.0/testing/unit-test-helpers/

This instruction should be removed. 

Would it make sense to reference specific Ember-Qunit versions in the guides?

**Comment by rwjblue** [comment]
Thanks for the pull requests! We also need `master` updated...

**Comment by ryanmurakami** [comment]
Ready to go!

**Comment by rwjblue** [comment]
Fixed in all branches, closing now....
