### ISSUE TITLE
Question: did emberjs 1.6.1 have a guide

### ISSUE THREAD

**Issue by vedraan** [emberjs/guides#1658]
The oldest guide branch I could find was 1.10, so just wanted to check if there was even an emberjs guide prior to 1.10?

If yes, where could I dig it out since I'm working on a project which uses that version? Would help a lot. Thanks!

**Comment by acorncom** [comment]
@vedraan There were guides at that time, but they weren't versioned until 1.10.  So you'll need to go dig up the old docs by hand.  The best way to do that would be to clone down the `emberjs/website` repo (guides were a part of that repo at the time) and checkout this commit (which was when 1.6.1 was released): https://github.com/emberjs/website/tree/c9a169efa76dac70979509b73ddb24481313c7b4

Have fun spelunking! 😀

**Comment by vedraan** [comment]
@acorncom Thank's a lot! My spelunking expedition was a great success. Was able to recreate the entire Ember 1.6.1 website using `bundle exec middleman` and then scrape it for easy access.
