### ISSUE TITLE
Problems encountered in Adding Nested Routes

### ISSUE THREAD

**Issue by gnowoel** [emberjs/guides#1661]
I had some small problems when following the [Adding Nested Routes](https://guides.emberjs.com/v2.8.0/tutorial/subroutes/) section of the tutorial.

### Generating a Nested Index Route

> If you open up your Router (app/router) you may notice that nothing has updated.

This seems no longer true. After running the `ember g route rentals/index` command, the route entry for `rentals` would be changed from:

    this.route('rentals');

to this:

    this.route('rentals', function() {});

### Setting up Data for the Nested Detail Route

We've added `description` fields in the rentals data. But to make them work, we may also need to update the model:

    export default DS.Model.extend({
      // ...
      description: DS.attr()
    });

### Linking to a Specific Rental

In [the acceptance tests](https://guides.emberjs.com/v2.8.0/tutorial/acceptance-test/), there's a line specifying that rental descriptions should be showing:

    assert.equal(find('.description').length, 1, 'should list a description of the property');

The test case would fail because we missed the `description` class in the template of the show route. We need to update the following line:

    <p>{{model.description}}</p>

to look like this:

    <p class="description">{{model.description}}</p>

**Comment by sbatson5** [comment]
I believe this can be closed @toddjordan

**Comment by locks** [comment]
Appreciated @sbatson5!
