### ISSUE TITLE
❓w.r.t autocomplete-component.md

### ISSUE THREAD

**Issue by sarbbottam** [emberjs/guides#1662]
[autocomplete-component.md](https://github.com/emberjs/guides/blob/master/source/localizable/tutorial/autocomplete-component.md) suggests the following.

>To implement these actions, we'll create the index controller for the application. The index controller is executed when the user goes to the base (index) route for the application.

>Generate a controller for the `index` page by running the following:

>
```
ember g controller rentals
```

---

Is it `index` controller or `rentals` controller. 

If it is `index` controller, could there a little explanation why is it called so.  

_Please excuse my ignorance, I have just started w/ ember_

Thanks!

**Comment by sbatson5** [comment]
Nice catch! That was revised as part of the subroutes tutorial, where we intended to make the `rentals` route the default route.  It looks like the text should be revised to show this.
