### ISSUE TITLE
autocomplete-component.md instruction needs to be updated.

### ISSUE THREAD

**Issue by sarbbottam** [emberjs/guides#1669]
https://github.com/emberjs/guides/pull/1668 has introduced a discrepancy. 

<img width="747" alt="controller" src="https://cloud.githubusercontent.com/assets/949380/18936772/26f833e6-859f-11e6-8431-03f1544d18a4.png">

Also, it needs to be `controllers/rentals.js` and not `controllers/index.js`. 

```
ember g controller index
```

and updating `controllers/index.js` breaks the application. 

---

I guess https://github.com/emberjs/guides/pull/1668 needs to be reverted.

cc/ @toddjordan  @locks

**Comment by toddjordan** [comment]
fixed by #1674 and #1675
