### ISSUE TITLE
missing/weird links in guides v1.11.0

### ISSUE THREAD

**Issue by alexblakemore** [emberjs/guides#169]
First, it would be helpful if the installing ember page in the guides had a link to http://www.ember-cli.com

That's a very important site with documentation that isn't available elsewhere. I'd mention it right up top when talking about installing ember-cli, but you could put it a little further on. Figuring out ember-cli from the --help text alone is pretty cryptic.

Second, in the same section, there is a link tied to NPM but it points back to the same paragraph that contains the link. A little strange and confusing. You can click it all day long and nothing seems to happen :-) Unless you are trying to play tricks on people, you might want to either actually link to a page about nom or remove the link.

**Comment by michaelrkn** [comment]
I agree that there's not enough info on ember-cli yet. I think the plan is to move all of the ember-cli.com info over to the docs. There are already a couple open issues and pull requests beginning to address this.

The link to NPM should jump you down to the bottom of the page, where there is a bit more info about how to install Node.

**Comment by locks** [comment]
I've submitted a PR to address the lack of hyperlink to the website. The non-functioning anchor tag should be make a separate issue.

**Comment by locks** [comment]
I have fixed the anchor hyperlink in the PR referenced.
