### ISSUE TITLE
IN simple-component page, wrong lines are marked as added and removed in app/templates/rentals.hbs snippet

### ISSUE THREAD

**Issue by shatran** [emberjs/guides#1690]
In [simple-component page](https://guides.emberjs.com/v2.8.0/tutorial/simple-component/) in app/templates/rentals.hbs snippet. It's not really a problem with the markup code, It's a problem with the way it's being displayed. Line 12 is not shown as added (+) and line 30 is not shown as removed (-) although in the markup code they are. this mentioned snippet:
```app/templates/rentals.hbs{+12,+13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,-29}
<div class="jumbo">
  <div class="right tomster"></div>
  <h2>Welcome!</h2>
  <p>
    We hope you find exactly what you're looking for in a place to stay.
  </p>
  {{#link-to 'about' class="button"}}
    About Us
  {{/link-to}}
</div>

{{#each model as |rentalUnit|}}
  {{rental-listing rental=rentalUnit}}
{{#each model as |rental|}}
  <article class="listing">
    <h3>{{rental.title}}</h3>
    <div class="detail owner">
      <span>Owner:</span> {{rental.owner}}
    </div>
    <div class="detail type">
      <span>Type:</span> {{rental.type}}
    </div>
    <div class="detail location">
      <span>Location:</span> {{rental.city}}
    </div>
    <div class="detail bedrooms">
      <span>Number of bedrooms:</span> {{rental.bedrooms}}
    </div>
  </article>
{{/each}}
```

**Comment by locks** [comment]
@shatran can you send a PR for the relevant section, please?

**Comment by shatran** [comment]
I can send but I'm afraid it will be just a hack around it.

**Comment by locks** [comment]
This was fixed by https://github.com/emberjs/guides/commit/d472ce95c9ff2bd64828395622b587d698e85007#diff-3edfc48f157f70b0c0c757a3d1c49ace, just not deployed yet. Thanks for reporting!
