### ISSUE TITLE
Two additional patterns for {{action (mut ... ) }}

### ISSUE THREAD

**Issue by mike-north** [emberjs/guides#1713]
Looking at the documentation, a few very handy patterns for `{{mut}}` do not seem to be covered anywhere other than reading through the source code for the helper itself.

#### setting the value of a property to some **literal** value
```hbs
{{#if myToggle}}
   {{!-- Clicking this will set myToggle to false --}}   
   <button onClick={{action (mut myToggle) false}}>Hide</button>
{{else}}
   {{!-- Clicking this will set myToggle to true --}}
   <button onClick={{action (mut myToggle) true}}>Show</button>
{{/if}}
```

#### accessing a particular property off of the property change event
```hbs
<input type='range'
   onInput={{action (mut size) value="target.value"}} />
```

For clarity, here examples of both: https://ember-twiddle.com/fc4179799bcf33c58f67d9cdd84111d0?openFiles=templates.application.hbs%2C

**Comment by locks** [comment]
Can you move this to emberjs/ember.js? This documentation should go in the API docs, thanks!
