### ISSUE TITLE
Tutorial TDD

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#1718]
Feedback from new Developers has been that walking through the tutorial using TDD-style approach is a hindrance to learning the brand new technology, because we are essentially starting the reader off with something that by definition doesn't work.  Also, we've heard that testing first requires some knowledge of the system under test or the underlying technology, which a new beginner will not yet possess.  Finally, a lot of new concepts are being introduced at once, and including one more, especially if the user has no experience in testing and TDD, adds to feelings of being overwhelmed.

On the flip side, others have mentioned that there is value in showing a workflow around how one might create an Ember application, and highlight how TDD might work in that context.  This is likely more tailored to developers with some SPA experience and some previous exposure to automated testing.  Earlier feedback suggested that providing examples of TDD workflow in Ember is helpful to developers.

Some Options (so far): 

- Introduce Acceptance testing at the end of the tutorial, after the application is already working.  Same for unit/integration: introduce at the end of the section that they are introduced in. (ex. component integration tests at the end of the components section.
- Have 2 tutorials: One that is tailored to newer developers and that very slowly and intentionally layers basic concepts to get to a basic knowledge of using Ember.  The other would assume more initial knowledge of SPA and development concepts focusing rather on a typical workflow one might use in developing an ember application.
- Keep TDD, but be a lot more deliberate and careful in introducing and explaining it.  Give the user the option (with links) to skip if they want to get directly into app code.

**Comment by mike-north** [comment]
It seems like there are two issues that relate to this discussion

* Should the primary path for teaching those new to ember (in the tutorial) be via TDD?
* Should we provide some material about using TDD workflows with ember?

I don't think anyone disagrees with the idea that TDD should have a place in the guides, but I'm not sure that these are two sides of the same issue.

**Comment by theroncross** [comment]
As a former teacher, I can confirm that attention is VERY limited for beginners and repetition is a major key to learning. My first instinct would be to present every topic twice in the tutorial:
1. First, make a thing,
2. Second (optionally), write tests for the thing,
3. Third, TDD another similar thing.

**Comment by toddjordan** [comment]
Thanks @theroncross , that's really good feedback.  I really like the approach you mention and will take that into consideration when we address this.

**Comment by mike-north** [comment]
I'm curious -- who is the developer (our audience) whose learning of core ember concepts for the first time, is enhanced (rather than muddled) simultaneously learning about testing controllers and ember's testing tools, while learning about controllers for the first time?

I would like to find some example individuals from whatever group the "teach by TDD" approach is aimed to benefit, and test this theory, in an effort to start some motion on this effort.

**Comment by theroncross** [comment]
I taught intro to programming for a few years, including a year with TDD. In theory, it's a wonderful idea to have a high-level sense of the behavior you're expecting. In practice, beginners are too busy making sure they've got the syntax right to having any bandwidth left for such concerns. If taking TDD out of the beginner tutorial is an option (assuming two tracks), I would push for that and put the basic workflows front and center. Leave TDD for a second-level tutorial.

**Comment by toddjordan** [comment]
@mike-north Not everyone that uses the tutorial is a complete newbie to web development.  I think there are different audiences that benefit from the tutorial.  Some have development experience and understand what a controller is (and have used it as a development pattern in the past), but have not used ember and would like a guided example to understand its mechanics.

I hear as much positive feedback on this approach the tutorial as negative (slack, meetups, github comments).  I understand that there is a population of developers (that you have deep experience with) that need a more slow and methodical approach to introducing the basics to.  I think we can move the tutorial and that direction.  I also think we can introduce testing and a less jarring way and still keep the concepts.

**Comment by toddjordan** [comment]
I have another option/proposal:

* Change the name of the acceptance testing page from "Setting up Tests" to "Planning the Application".
* Remove the part of the page where we implement each test, but leave the part where we generate the acceptance test file and convert our list of task into test names.
* The implementation of the first test routing to a page will get tacked on in a section or a page after we get it working in routes and templates.
* This will show how one might go about starting a test driven process, but save learning the actual mechanics of implementing an ember acceptance test until after the tutorial follower implements the page and learns the ember concepts in creating.
* Later on in the tutorial we can challenge the follower to implement a test first based on what they've done previously

**Comment by theroncross** [comment]
Along those lines, is it possible to just break the testing into their own subsections, interspersed in the rest of the tutorial. Make it clear at the beginning that the testing is encouraged, but optional and can always be come back to after completing the section?

**Comment by toddjordan** [comment]
Yes, which is kinda what I proposed above (sorry wasn't clear).  Only the appropriate test would be implemented in each page.  (could be before or after, or start after and switch to before after they've implemented a couple)

**Comment by mike-north** [comment]
> @mike-north Not everyone that benefits from the tutorial is a complete newbie to web development. I think there are different audiences that use the tutorial. Some have development experience and understand what a controller is (and have used it as a development pattern in the past), but have not used ember and would like a guided example to understand its mechanics.

> I hear as much positive feedback on this approach the tutorial as negative (slack, meetups, github comments). I understand that there is a population of developers (that you have deep experience with) that need a more slow and methodical approach to introducing the basics to. I think we can move the tutorial and that direction. I also think we can introduce testing and a less jarring way and still keep the concepts.

I do not represent a group of those new to JavaScript, but a broad swath of developers across the world who have little or no experience with ember. A great many of them have experience with React and/or other frameworks.  The tutorial is their first look at the framework, and is the place where they pass judgement on whether this is a tool that feels right to them. 

Please reference the github comments you're referring to, which indicate that moving the TDD into another place within the guides would be detrimental to their first look at the framework. So far all I've heard to support this POV are abstract claims. This is a point of view I've NEVER heard directly, and I'm interested in learning more. 

If the idea is to evangelize TDD as a best practice, the way is is currently positioned means it's coming at the cost of adoption. Not sure if it's worth this price.

**Comment by toddjordan** [comment]
Hi @mike-north thanks for your interest in the tutorial.  You might notice I did create this issue, and am interested in and active in improving the tutorial experience.  This issue is proposing various options in how to improve the experience around testing.  I'm unsure of what your are proposing.  Would you like to remove testing from the tutorial, address it at the end of each relevant section, or what?  From what I can tell so far I think your vote is to never mention test before a relevant feature, because it detracts from learning Ember.  Is that correct?

**Comment by mike-north** [comment]
> Hi @mike-north thanks for your interest in the tutorial. You might notice I did create this issue, and am interested in and active in improving the tutorial experience also. 

I am happy any time this effort gets attention. What I've seen so far is that less controversial issues have been largely addressed. I really appreciate those efforts. Thank you!

> This issue is proposing various options in how to improve the experience around testing within the tutorial. I'm unsure of what your are proposing.

Apologies if my specific asks have been lost in the multiple tickets. The main theme:
 
**Keep the tutorial focused and oriented, to the highest degree possible, on teaching and showcasing core ember concepts and features, to those relatively (or completely) new to ember.**

The reason they're using the tutorial is because they're kicking the tires of this project. We need to focus and orient the guides toward this audience, and to serve this purpose.

My specific asks, as they pertain to testing:
* **In the guides in general:** Do not ask users to write, or otherwise deal or think about tests before or while they're being taught core framework concepts.
* **In the introductory tutorial:** Do not ask users to write tests at all. Instead, provide them with pre-built tests that they must work to pass.

Please also provide the community with any documented information related to support for the currently implemented approach. I have searched through every learning team meeting notes and even scoured individual commits, to no avail. I do not believe that the information is there, or it's incredibly difficult to find. It's difficult to have a constructive discussion about this when faced with vague and non-specific reports of favor for the current state of the guides.

The reason I'm interested in this information is because I have literally never spoke with someone who sees asking a student to write a controller test before they know what a controller is, as an effective teaching methodology.

I meet tons of people who love TDD and want to learn about it, and their needs can be met without detracting from the conceptual "entry point" for prospective adopters (i.e., a separate TDD section or dedicated TDD tutorial). Either I'm missing something huge, or this issue is getting a bit muddled (i.e., maybe people are thinking I'm advocating for removing TDD or testing from the guides entirely?)

**Comment by toddjordan** [comment]
ok, thanks.  We've got your proposal as a valid option to consider.  It sounds similar to current thinking that we de-emphasize the test driven approach while introducing new concepts.

So if I understand then, you want some kind of documented proof that we wrote the tutorial based off new user testing or research.  I can tell you that it wasn't, at least since I've been contributing.  Its been built by people who love ember and wanted to help others learn the framework and its capabilities.  We got input from other contributors and core team members and reviewed each other's work.  Its not perfect, and that's why we are looking at addressing these issues.  

As far as your demands for proof of positive feedback, you can DM me on slack for my thoughts.

Thanks again for your opinions and contributions.

**Comment by anhari** [comment]
FWIW, I would find a guide that walks through basic CRUD operations or focuses more on serialization/deserialization infinitely more helpful than what I have gained from the TDD portions of Super Rentals.

I understand this requires setting up a backend and is maybe outside of the scope of the offical guides for ember.js.

**Comment by mike-north** [comment]
> So if I understand then, you want some kind of documented proof that we wrote the tutorial based off new user testing or research. I can tell you that it wasn't, at least since I've been contributing. Its been built by people who love ember and wanted to help others learn the framework and its capabilities. We got input from other contributors and core team members and reviewed each other's work. Its not perfect, and that's why we are looking at addressing these issues.

I wouldn't say I'm **demanding** anything. It's just that I've seen statements like this thrown around casually

> I hear as much positive feedback on this approach the tutorial as negative (slack, meetups, github comments).

which do not align well with most of the comments I've seen on this issue, #1708, or the data I've gathered from training and producing content for lots of developers.

**Comment by toddjordan** [comment]
I've reorganized the tutorial some to de-emphasize a test first approach.  I've also tried to make some of the concepts clearer.

Testing still exists in the tutorial. it is just pushed to the last section(s) of each page, and right before the test section of each page, we give the reader the option to either skip the testing part and keep implementing features, or learn to test what they've just done. 

I think the PR is in decent shape now, though I could use a volunteer or two to go through the PR from the beginning with an eye for errors and inconsistencies.

**Comment by lazaridis-com** [comment]
@toddjordan
>ok, thanks. We've got your proposal as a valid option to consider. It sounds similar to current thinking that we de-emphasize the test driven approach while introducing new concept

you should not de-emphasize it. you should drop it, it does not belong in an entry-tutorial. I don't know who has written those tutorial mainly, but he should simply **drop** this task and let someone else do it. 

Listen carefully to those comments:

@anhari - https://github.com/emberjs/guides/issues/1718#issuecomment-274543897
@mike-north - https://github.com/emberjs/guides/issues/1718#issuecomment-274283176

-

General Remark:

I'll give the new version a look, but I don't have any hopes that it is better.

This is **very** disapointing, and show lack of leadership in this project (and **please**, do not start the usual open-source-whining. This is a commercial open-source-project. The central tutorial is a **marketing** instrument, and should be treated as such).

**Comment by toddjordan** [comment]
Addressed by #1818

**Comment by lazaridis-com** [comment]
@toddjordan , can you please reopen #1851, as it addresses the project leadership, which has not yet commented? And the "lock" should be removed, too - no evolution without a good 'fight'.

The changes that you've applied do not address the issue at hand. The tutorial is still far too heavy.

May I send you a reworked version of a page, so you can see how it should/could look?
