### ISSUE TITLE
Testing inconsistency in "Services and Utilities" section

### ISSUE THREAD

**Issue by mdarmetko** [emberjs/guides#1722]
The first paragraph of Fetching Maps With a Service states: "At this point we should have a passing component integration test, but our acceptance test should now fail, unable to find our maps service. In addition to our acceptance test failing, no maps show up when we view our web page."
https://guides.emberjs.com/v2.9.0/tutorial/service/#toc_fetching-maps-with-a-service

The maps in fact don't show up on the web page, but there is no failing acceptance test. Just thought I would point that out for consistency's sake. It causes some confusion working through the tutorial.

Personally I love how TDD is integrated into the tutorial, taking the guesswork out of how to implement testing in a real ember project.

**Comment by toddjordan** [comment]
Thanks @mdarmetko, good catch!

**Comment by theroncross** [comment]
Is this just a simple change to remove the comment about the test, or do we need to add instructions on creating a failing test?

**Comment by toddjordan** [comment]
@theroncross I think for this case we can simply remove the reference to the failing test, since an acceptance test for a google map showing up would be a bit hairy for the tutorial.
