### ISSUE TITLE
Document that inline `{{if}}` helper will evaluate both subexpressions

### ISSUE THREAD

**Issue by Fryie** [emberjs/guides#1737]
It makes total sense that this is the case, but it tripped me up nevertheless: If you have `{{if cond (foo x) (bar y)}}`, both `{{foo x}}` and `{{bar y}}` will always be evaluated.

It seems that this is not documented in [the API docs](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_if) or [the guides](https://guides.emberjs.com/v2.9.0/templates/conditionals/) and I think it might be useful to add a sentence or two describing this behaviour.

**Comment by acorncom** [comment]
@Fryie Good catch.  I would suggest sending in a PR for the additional documentation to the api docs (https://github.com/emberjs/ember.js), as we try to both document a number of items in guides without having them be completely comprehensive ...

**Comment by acorncom** [comment]
@Fryie Any updates here?  I'm inclined to close this issue here, as our goal with guides is to keep them from being a complete resource on everything you might hit, but rather a good thorough introduction to the main things about Ember ...

**Comment by Fryie** [comment]
Since this is something that might trip up people, I think it wouldn't hurt to have it in the guides, too. However, if you feel that it is too detailed, it should probably be in the the API docs at least. Sorry, haven't gotten around to doing a PR yet.
