### ISSUE TITLE
"Quick Start" for v2.10.1 is a 404

### ISSUE THREAD

**Issue by eventualbuddha** [emberjs/guides#1752]
The ember-welcome-page addon has a ["Quick Start" link](https://github.com/ember-cli/ember-welcome-page/blob/743d06b6fc07552a81758ff2a2b4d81afd0afaf2/addon/templates/components/welcome-page.hbs#L12):

```hbs
        <li><a href="https://guides.emberjs.com/v{{emberVersion}}/getting-started/quick-start/">Quick Start</a> - a quick introduction to how Ember works. Learn about defining your first route, writing a UI component and deploying your application.</li>
```

However, the version I just installed (v2.10.1) with a new Ember CLI app links to https://guides.emberjs.com/v2.10.1/getting-started/quick-start/, which is a 404 at the moment.

**Comment by locks** [comment]
I'm not sure how that's possible, we're [explicitly returning 0 for the patch version](https://github.com/ember-cli/ember-welcome-page/blob/743d06b6fc07552a81758ff2a2b4d81afd0afaf2/addon/components/welcome-page.js#L10). Which version of Ember CLI and ember-welcome-page?

**Comment by eventualbuddha** [comment]
It's pretty easy when your version regex only expects single digits for major/minor/patch 😉 

```js
  massageVersionNumber: function(version) {
    return version.replace(/(\d).(\d).\d/, '$1.$2.0');
  }
```

This should be:

```js
  massageVersionNumber: function(version) {
    return version.replace(/(\d+).(\d+).\d+/, '$1.$2.0');
  }
```

That's from ember-welcome-page v1.0.3, which I get with from ember-cli v2.10.0, which I just installed. It looks like the latest release of ember-welcome-page is v2.0.2, which has a [different way of computing the base version](https://github.com/ember-cli/ember-welcome-page/blob/743d06b6fc07552a81758ff2a2b4d81afd0afaf2/addon/components/welcome-page.js#L8-L10). I think the TODO here is to update ember-cli to use this more recent version of ember-welcome-page, which happened in https://github.com/ember-cli/ember-cli/commit/58b7431e0726ba156611893e5cce79a122e5b014. However, that's in v2.11.0-beta1 and so, for now, v2.10.x is borked.d=

**Comment by locks** [comment]
@eventualbuddha 1.0.4 released. Since `package.json` specifies `^` for the `ember-welcome-page` dependency, 1.0.4 with the fix should be installed. Can you confirm?

**Comment by eventualbuddha** [comment]
Yep, works now.

**Comment by locks** [comment]
Sweet 😁 Thanks for reporting!
