### ISSUE TITLE
Components Wrapping content refers to helpers without linking

### ISSUE THREAD

**Issue by theroncross** [emberjs/guides#1781]
The 'Components - Wrapping Content in a Component' is a bit of a tough one to get through for beginners. One small part of that is that it refers to the component and hash helpers, but doesn't include links to the API docs. Although this is probably a bigger issue generally, I figured I could tackle this page quickly unless there's a reason to keep linking to a minimum. I'd be happy to work on more pages if that seems useful.

**Comment by toddjordan** [comment]
hi @theroncross, thank you! I know that @sclatter was doing something along similar lines.  Her initial pr was to add a section on layouts https://github.com/emberjs/guides/pull/1763, and the latest comment is to encorporate that introduction into this page.

That said, the hash helper part certainly use love and is outside the scope of that pr, so if you have some love to give, it would be appreciated ❤️

**Comment by theroncross** [comment]
@toddjordan do you have page in mind for this?

**Comment by toddjordan** [comment]
I actually was referring to the wrapping content page you mention here.  (didn't notice you already had a pr).  What I was trying to say is that there was work happening on the first part of the page round layouts/block components, but you were free to improve the more advanced contexual component piece.

**Comment by theroncross** [comment]
By the time you stare at these docs long enough to change them, you lose sight of what you found difficult, confusing, or lacking in the first place.

**Comment by toddjordan** [comment]
lol, truth

**Comment by toddjordan** [comment]
Closing this issue out as it appears that we've merged content to address it.  lmk if there's more...
