### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR on guides

### ISSUE THREAD

**Issue by alpermutlu** [emberjs/guides#1789]
Hi all,

When I visit https://guides.emberjs.com/ I get an SSL error ERR_SSL_PROTOCOL_ERROR.

This is the curl response:
`curl -L https://guides.emberjs.com`
`curl: (35) Server aborted the SSL handshake`

When we inspect this deeply, we see the results below:
![image](https://cloud.githubusercontent.com/assets/2779319/22288349/989e9ea2-e307-11e6-8c75-6ae05aca2736.png)

![image](https://cloud.githubusercontent.com/assets/2779319/22288397/c8b7c6f4-e307-11e6-958e-9a6be3f3f7e0.png)

I think this is a TLS 1.0 issue. What might be the solution here?

Thanks.

**Comment by locks** [comment]
Thanks for reporting @alpermutlu, I'm glad our migration to a new setup seems to have fixed this :)
