### ISSUE TITLE
https://guides.emberjs.com/v2.11.0/ uses terms ES6 ES2015 and ECMAScript 6

### ISSUE THREAD

**Issue by frunjik** [emberjs/guides#1790]
On the guide index page it mentions:
ES6, ES2015, ECMAScript 6
Without saying that they are all the same ... 
(They are all the same aren't they ?)

**Comment by locks** [comment]
@frunjik "Understanding ECMAScript 6" is the name of the book so we can't change it, but when we land the JavaScript primer I'll add an item to the list saying they're all synonyms, and link to the primer.
