### ISSUE TITLE
Older versions of Quick Guide is not awailable very often 

### ISSUE THREAD

**Issue by ipogoretsky** [emberjs/guides#1809]
Very often older versions of quick guide is not available - 404 page

**Comment by locks** [comment]
@ipogoretsky do you have a suggestion to improve this?

**Comment by acorncom** [comment]
@ipogoretsky Would love to get this fixed if you can send the url in question that you're seeing that has problems ...

**Comment by ipogoretsky** [comment]
@acorncom see for examle https://guides.emberjs.com/v1.10.0/getting-started/quick-start. 
![2017-02-14 18 46 08](https://cloud.githubusercontent.com/assets/8426797/22936233/e8a04ade-f2e5-11e6-85c3-12f13a442957.png)

**Comment by acorncom** [comment]
@ipogoretsky Ah, that's because we hadn't written that page back when the v1.10 guides were released 😀 We don't back-port new pages we write to old versions of the guides, as sometimes our syntax has changed and other aspects of Ember have changed.  Does that answer your question?

**Comment by acorncom** [comment]
I'll close this issue for now, but let's reopen it if there is something we're missing
