### ISSUE TITLE
discourage jQuery clicks from tests in guides/tutorial

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#1815]
See https://github.com/emberjs/ember.js/issues/14867#issuecomment-280341753 for background

I see references in "Testing Components" that should be updated, "Building a Simple Component" (tutorial), and "Building a Complex Component"(tutorial).  Any one finding references elsewhere can list here.

We should also give a brief explanation for initiating events on native elements vs the jQuery object (in "Testing Components"). We can link back from the tutorial.

**Comment by serenaf** [comment]
@toddjordan Hey Todd, would like to give it a try :)

**Comment by toddjordan** [comment]
Hi @serenaf you are welcome to!  A brief warning of the problem in the testing components page and pointing people at ember-native-dom-helpers with a small example should do.

**Comment by toddjordan** [comment]
To clarify (based on -team-learning slack thread), I think native-dom-helpers is eventually becoming wrapped into the out of the box ember test infrastructure, but I don’t know when.  Therefore I suggest we do the following:

1) mention/suggest ember-native-dom-helpers in the testing guide (possibly in this section https://guides.emberjs.com/v2.13.0/testing/testing-components/#toc_testing-user-interaction) 
2) if there are places in the tutorial/other guides where we have onclick={{action…}}, replace with just {{action…}} (as per rwj’s comments)

**Comment by serenaf** [comment]
@toddjordan Hey Todd, is this issue good to close now? :)  The above mentioned PR was merged

**Comment by toddjordan** [comment]
excellent!  Thanks @serenaf
