### ISSUE TITLE
a few issues with the first tutorial page

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#1827]
Walking through the tutorial from scratch and noticed a few things on the first page.  
`/source/localizable/tutorial/ember-cli.md`

1. we should tell the user to cd into the newly created project after calling `new`.  I'm an experienced ember developer and I still get trolled by that.

2. we should remove the "upgrading ember" section since the upgrade task is not straightforward for new devs.  We should instead direct them to installing the latest ember-cli before calling `ember new`: `ember install -g ember-cli`

**Comment by li-xinyang** [comment]
I would love to help to clarify this part what should I do? Just send a new PR and fix the issue?

**Comment by toddjordan** [comment]
Yup.  Thanks!  Looking at the PR...
