### ISSUE TITLE
Documentation for skipping a unit test

### ISSUE THREAD

**Issue by gitaarik** [emberjs/guides#1839]
It's very handy in TDD to be able to temporarily disable tests by skipping them. You can of course also comment out the code but you could then get a lot of "imported but unused" errors in your test results.

From some other GitHub issue I found the way to skip a test is to use the function `skip` instead of test, also imported from `ember-qunit`:

    import { test, skip } from 'ember-qunit';
    
    test('run this test', function(assert) {
        assert.ok(true)
    });
    
    skip('skip this test', function(assert) {
        assert.ok(true)
    });

There is no mention about this in the testing guide though. Would have saved me some time searching if it would, so I would like to put it in there. I was thinking it would be appropriate for the "Unit Testing Basics" chapter: https://guides.emberjs.com/v2.11.0/testing/unit-testing-basics/

**Comment by locks** [comment]
Hi @gitaarik, do you have some time to work on a PR?
