### ISSUE TITLE
Ember.Route#controllerFor api reference seems to be wrong

### ISSUE THREAD

**Issue by feanor07** [emberjs/guides#1844]
http://emberjs.com/api/classes/Ember.Route.html#method_controllerFor

controllerFor api documentation says "Returns the resolved model of the current route, or a parent (or any ancestor) route in a route hierarchy."; this seems to be wrong it returns the associate controller nothing realted with model I guess.

**Comment by locks** [comment]
Can you send a PR to https://github.com/emberjs/ember.js please? The API docs are generated from the source.
