### ISSUE TITLE
Simplify the Newcomer Tutorial

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1848]
The tutorial starts right up with test-driven development, which bombards essentially a newcomer with very much information about acceptance tests.

It would be preferable to have this test-chapter placed at the end, in an "Intermediate" section.

(I'll work through this tutorial tomorrow. If there is interest to simplify it, then I can write-down the relevant points.)

**Comment by locks** [comment]
Thanks for the feedback. This is already being addressed in https://github.com/emberjs/guides/pull/1818, check it out if you're interested in a softer approach to testing :)
