### ISSUE TITLE
[LEADERSHIP] - Please Cleanup the Tutorial Mess

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1851]
There is a Tutorial (https://guides.emberjs.com/v2.12.0/tutorial/ember-cli/)

And there is the question: how long does it take for the Ember Leadership to intervene? I mean, there **is** a leadership, like in any commercially backed project, or not?

So, the Product Manager should take a look at this:

#1708 - Perspective of someone new to SPAs: Large tutorial in guides is incredibly confusing
#1718 - Tutorial TDD
#1818 - More gradual testing intro

And yet, the tutorial is still in a terrible condition.

How much does it take for you to realize: those who have written the tutorial meant good, but did Ember not a favor.

And now the best part:

A contributor volunteered to work on the tutorials, and he has excellent points. It's @mike-north. How long does it take for the leadership to intervene, and to say: "Stop talking and voting, please let @mike-north come up with a suggestion, e.g. a "thin tutorial".

Will you discuss & vote Ember to its death? Personally, I went away from Ember after seeing the tutorial mess. Only because all other frameworks did not pass my evaluation, I'm back to Ember.

**Do you understand this???***

-

Please(!), get over your **bizarre TDD fixation**, and provide a clean simple Tutorial. A little bit "page" a little bit "model" and some of the "CRUD". Simple, concise, so that new users get the feeling "Ember empowers me".

 And then another one, which has TDD workflow within, and all other find things. So the intermediate and expert developers say "Ok, Ember keeps me on a pro level".

Act!

Please Cleanup the Tutorial Mess!

**Comment by toddjordan** [comment]
I don't see any new issue over the ones already linked.  Therefore closing this issue.
