### ISSUE TITLE
Migrate Away from "Middleman", Alternatives.

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1852]
I tried to provide feedback to #1818 whilst reviewing the resulting site, but got stuck whilst installing the (non-JavaScript tool) "middleman". I stopped after hitting the 1 hour mark (problems with SSL certificates during library installations) - more frustrated than before.

I am sure that the JavaScript domain has similar or better tools available. But even if the JS tools for generating a doc site are worser, please use them.

## Requirements

(just to initialize a discussion)

* Should play nice with a repo / *.md files
* Should generate the navigation in an automated manner (avoid hand-assembled navigation trees)

Which are the available alternatives?

**Comment by lazaridis-com** [comment]
A 2nd attempt:

* Installer 2.2.6 32bit (**not** 64bit)
* devkit, get it, extract, rung `ruby dk.rb init` and `ruby dk.rb install`
* fetch latest RubyGems from https://rubygems.org/pages/download, extract, run `ruby setup.rb' within it.
* Changing  `eventmachine (1.0.8)` to `eventmachine (1.0.4)` within Gemfile.lock
* changing http://rails-assets.org/ => http://insecure.rails-assets.org/  within Gemfile.lock (or Gemfile, don't remember)
* After `gem install middleman` and `bundle` had downloaded half of the universe, the installation of 
* http://curl.haxx.se/gknw.net/7.40.0/dist-w32/renamed-curl-7.40.0-devel-mingw32.zip

brought finally up the result.

**Fascinating efficient toolset!!!**

**Comment by locks** [comment]
This is already planned, you can follow along at https://github.com/ember-learn/guias.

**Comment by lazaridis-com** [comment]
@locks , I don't understand "ember-learn", "guias". Are there no ready documentation-tools in the JS domain?

(and can you please avoid closing issues that fast? This is a docu repo anyway. )

**Comment by locks** [comment]
ember-learn is the GitHub organization for the learning team, and guias is an Ember.js application to view guides that intends to replace the current stack. It is part of an ongoing mid-term plan to re-structure our resources, which includes slowly moving resources over to Ember.js. This has the two-fold consequence of us dog fooding our own technology, as well as coming up with maintained open source applications for the community to inspect.

You can read the minutes of our weekly planning calls at https://github.com/emberjs/core-notes if you're curious for more information.

My goal with closing this and the tutorial issue was to redirect you to active issues/projects so you can take part in those conversations, to help keep the discussions focused on moving forward.

**Comment by lazaridis-com** [comment]
> ember-learn is the GitHub
[...]

Ok, I see! You may copy the explanation you gave me to the repo / organization there, thus others see it. I guess this "own dog-food project" is a good way of getting in contact with Ember coding.

(btw: think about renaming the organization to "emberdoc", which can be later become a product-name for a documentation-system (if you finally succeed).

> My goal with closing this and the tutorial issue was to redirect you to active issues/projects so you can take part in those conversations, to help keep the discussions focused on moving forward.

The only thing usually moves forward is me - after people kicking me out. Theyusually react bad with my communication-style ( = my individuality).

I will take a look at your "guias" (Spanish: guide?) project, but first I have to focus now to decide if I use Ember. So, I have now to finish my Getting Started Evaluation first.

Ember is the last framework left, I must find a way to fit in, otherwise I'm damned to use full-commercial tools for my development work, which I want to avoid.

Going into weekly planning calls is far too early for me. And I want to stay out of the way of the core-developers as much as I can. That's why I'm here on the docs repo.

So, cu around!

**Comment by lazaridis-com** [comment]
*weekly planning calls minutes
