### ISSUE TITLE
[HOWTO] Add a Website Template

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1853]
(using the doc repo for this, as this can be used to create a simple "How To" overview)

Is there a way to add a website template to my project? Something like

`$ ember add template standard`

Which would add the standard-template, which would be e.g. a header-footer-left-nav template.

If not, is there anything in the documentation which shows how to do this quickly (e.g. adding a bootstrap template, or some template purchased from a designer) ?

**Comment by locks** [comment]
The closest to this that we do have documented is the [Installing Addons](https://guides.emberjs.com/v2.12.0/tutorial/installing-addons/) section of the tutorial, where we point to the curated addon catalog, [Ember Observer](https://emberobserver.com/), as well as instruct the reader to install an addon that provides styling to the tutorial application.
You also have an `ember-bootstrap` addon that provides various UI elements as Ember components, on top of the CSS stylings, I don't know about whole template blueprints.

There are some Ember-focused themes out there, but I have not used them so I do not know the distribution/installation mechanism. If it's not an addon/engine, the theme would need to provide instructions itself.

As it is currently addressed in the tutorial, even if not optimally, would you agree with closing this issue? To provide some additional context, merging the Ember and Ember CLI documentation into something more unified is in the roadmap, but both teams still have other items to address first.

**Comment by lazaridis-com** [comment]
So the answer is:

fight through the docs and find it out.

ok.

**Comment by rwjblue** [comment]
Hehe, yes. The answer in general to these types of Q/A things is to read the docs. That's what they are for! 😁

**Comment by lazaridis-com** [comment]
To whoever hits on this in future:

http://yoember.com/#ember-bootstrap-sass

Some more decent tutorial resources:

https://ember-cli.com/user-guide/#tutorials
