### ISSUE TITLE
[HOWTO] Enable Template Error Messages by Default

### ISSUE THREAD

**Issue by lazaridis-com** [emberjs/guides#1854]
executing the tutorial:

In the main template (application.hbs), I've  placed this code

```html
<div class="container">
  <div class="menu">
    {{#link-to 'index'}}
      <h1 class="left">
        <em>SuperRentals</em>
      </h1>
    {{/link-to}}
    <div class="left links">
      {{#link-to 'about'}}
        About
      {{/link-to}}
      {{#link-to 'contact'}}
        Contact
      {{/link-to}}
    </div>
  </div>
  <div class="body">
    {{outlet}}
  </div>
</div>
```

The "Contact" page is not yet provided. The result is that possibly the `{{outlet}}` tag is not reached, resulting my `About` page not displaying its content.

Why does Ember not report me such an error by default?

How do I configure Ember to report me such errors, instead of silently ignoring them?

**Comment by rwjblue** [comment]
The error is reported to the console (which, in general, is where these things go).

Also, this issue fracker isn't really meant as general Q/A. You should join the Ember community slack (you can get an invite from [here](https://ember-community-slackin.herokuapp.com/)), lots of us hang out there and answer questions like these.

**Comment by lazaridis-com** [comment]
I guess that even modern kids know that those things go usually there. But not with Ember (at least not in my trial). Just fancy things like this:

```shell
Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
SourceMapConcat: Concat: App (1)              | 156ms
SourceMapConcat: Concat: Addon JS (1)         | 54ms
Funnel: Addon JS (8)                          | 52ms (6 ms)
SimpleConcatConcat: Concat: Addon CSS (1)     | 47ms
broccoli-persistent-filter:Babel > [Ba... (3) | 39ms (13 ms)

file changed templates\application.hbs

Build successful - 629ms.
```

> Also, this issue fracker isn't really meant as general Q/A.

I don't do Q&A. I find spot issues in the documentation (or produce documentation). Essentially, I'm uncovering weaknesses.

> Ember community slack

Chat for analyzing issues? No way. You would block me in record time.

**Comment by rwjblue** [comment]
FYI - I was referring to the browser console. This isn't really an Ember specific thing. All front end frameworks run JS in the browser and therefore when runtime errors occur you will find them in the browser console. 

> I don't do Q&A.

I disagree 😉.

> I spot issues in the documentation (or produce documentation).

Please explain how this is an error in the documentation, I'm not really following you here. 

> Chat for analyzing issues? No way. You would block me in record time.

Higher bandwidth communication often overcomes communication issues, and can provide much quicker guidance than opening issues. It also has the added benefit of not wasting the time of contributors for general questions.

**Comment by lazaridis-com** [comment]
@rwjblue, save your words, wise man.

@locks, @toddjordan - the main issue here are those two questions that can come up from newcomers or tired evaluating-ember-late-night users:

 * Why does Ember not report me such an error by default?
 * How do I configure Ember to report me such errors, instead of silently ignoring them?

The tutorial should point out that one has to look for errors within the browser-console-window (+ how to open, for total newcomers).

(Essentially, a 2nd issue raises here, which is: `provide error-messages within the page itself`, but I leave this to you to decide if you want to open such an issue within the core project.)

**Comment by lazaridis-com** [comment]
Example Section

## New to Frontend Developement?

Some things you possibly do not know if you're new with Frontend Development.

### Error Output

Errors are shown usually within the `browser console`, simply because the JavaScript code you write is execute in the browser. You open the console with:

(firefox, chrome, etc.)

### Data

You can use a local data store, which has several limitation, as it simply is not a server-scale datastore. 

(elaborate a bit on general constructs and EmberData)

**Comment by locks** [comment]
> (Essentially, a 2nd issue raises here, which is: provide error-messages within the page itself, but I leave this to you to decide if you want to open such an issue within the core project.)

There already is.

> [various newcomer mentions]

We establish a baseline at [Assumptions](https://guides.emberjs.com/v2.12.0/#toc_assumptions) for this reason.

Actionable feedback:
- [ ] Reference browser console

**Comment by lazaridis-com** [comment]
@locks , did you finally eat? Me too lazy to cook, finally opened a can.

Actionable feedback:

 [ ] - cook something decent.
