### ISSUE TITLE
404 when opening some links in https://guides.emberjs.com

### ISSUE THREAD

**Issue by mayankyadav** [emberjs/guides#1857]

**Comment by pizza** [comment]
When this issue was opened, I too was getting a 404, but it looks like it's working now: https://guides.emberjs.com/v2.12.0/tutorial/ember-cli/

**Comment by mayankyadav** [comment]
Yep. Works now

**Comment by Arko** [comment]
Had same issue right around OP time. Still 404 from Switzerland

**Comment by acorncom** [comment]
@arko can you keep us updated on whether it continues to be broken for you? Looks like our CDN host may have had issues in Europe for a bit ...

**Comment by Arko** [comment]
Will do!

**Comment by mayankyadav** [comment]
https://guides.emberjs.com/v2.12.0/tutorial/hbs-helper/ broken in France.

**Comment by Arko** [comment]
https://guides.emberjs.com/v2.12.0/tutorial/ember-cli/ back up for me.
https://guides.emberjs.com/v2.12.0/tutorial/hbs-helper/ is still 404

**Comment by locks** [comment]
Moving over to #1858, please gives up updates there!
