### ISSUE TITLE
[CDN Issue - Active] Guides pages missing from tutorial and elsewhere

### ISSUE THREAD

**Issue by cncardoso** [emberjs/guides#1858]
Page missing on 
https://guides.emberjs.com/v2.12.0/tutorial/autocomplete-component/

**Comment by acorncom** [comment]
This seems to be an issue with our CDN provider that started a few hours ago. Will leave this issue open and close others that seem to be the same root issue.

**Comment by acorncom** [comment]
I just re-deployed the latest version of the guides, please let me know if you continue to see issues ...

**Comment by wmena** [comment]
This pages also have the same issue:

https://guides.emberjs.com/v2.12.0/routing/rendering-a-template/
https://guides.emberjs.com/v2.12.0/templates/displaying-the-keys-in-an-object/
https://guides.emberjs.com/v2.12.0/templates/links/
https://guides.emberjs.com/v2.12.0/components/customizing-a-components-element/
https://guides.emberjs.com/v2.12.0/components/block-params/
https://guides.emberjs.com/v2.12.0/models/defining-models/
https://guides.emberjs.com/v2.12.0/models/pushing-records-into-the-store/
https://guides.emberjs.com/v2.12.0/testing/testing-components/

**Comment by locks** [comment]
I was in the affected area, but I am not getting any 404s anymore.

**Comment by mariowilde** [comment]
Same here. The issue seems to be resolved for me.

**Comment by acorncom** [comment]
Sounds good. I'll close this for now, please comment if you are still seeing issues...

**Comment by cncardoso** [comment]
Resolved. Thanks!
