### ISSUE TITLE
Ember Guide for Observers and Bindings are not available for v2.12.0

### ISSUE THREAD

**Issue by corasla** [emberjs/guides#1860]
When going to these URLs, you will get a 404

https://guides.emberjs.com/v2.12.0/object-model/observers/
https://guides.emberjs.com/v2.12.0/object-model/bindings/

**Comment by acorncom** [comment]
Thanks for reporting, this seem to be a CDN issue (in Europe?) as it isn't consistent: https://github.com/emberjs/guides/issues/1858#issuecomment-288082371 I'll close this issue and track info there.
