### ISSUE TITLE
Missing Routing pages in 2.12

### ISSUE THREAD

**Issue by larryh** [emberjs/guides#1862]
Hi,

The following pages are missing in the Routing section for 2.12:
Rendering a Template
Redirecting
Loading/Error Substates

BTW: thanks for all of the work that you do on this!

**Comment by acorncom** [comment]
Thanks for reporting, this seem to be a CDN issue (in Europe?) as it isn't consistent: https://github.com/emberjs/guides/issues/1858#issuecomment-288082371 I'll close this issue and track info there. If you continue to see the issue in a few hours can you write back on that issue? Thanks!

Also, appreciate the kind words, makes it easier to keep doing these things :grinning:
