### ISSUE TITLE
Tutorial "building a complex component" section improvements

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#1868]
In the tutorial section called "Building a Complex Component" (complex-component.md), we should add a small blurb at the beginning describing why the component we are about to build is considered "complex".  I'd say the new component is complex because it takes in input, invokes a function that performs the search (closure action), and then allows the consumer of the component to customize the results of the search (via a block component).

Something along the lines of...

```
As they search for a rental, users might also want to narrow their search to a specific city. Let's build a component that will let them filter rentals by city.
While our initial [rental listing component](../simple-component/) simply displayed rental information to the screen, 
this new filter component will additionally allow the user to provide input in the form of filter criteria and allow for customization of how results are shown.
```
---

In the 4th paragraph, we introduce the concept of a "block component" without saying it.  We should mention that what we are showing is referred to as "block component", and link to the guides explanation of it (../../components/wrapping-content-in-a-component/).

---

Finally, After the list-filter.hbs code snippet, while explaining the input helper, we make a couple of references to bound properties.  We need to explain what data binding is here.  Something like

```
The value property of the input will be [bound](../../object-model/bindings/) to the value property in our component, meaning that when ever the value of the property changes, either by the user typing in the input field, or by assigning a new value to it in our program, the new value of the property is present in both the rendered web page and in the code. 
```

**Comment by mixonic** [comment]
Closed by https://github.com/emberjs/guides/pull/1888
