### ISSUE TITLE
In Simple Component section, explain what an "Actions Hash" is

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#1872]
After the `rental-listing.hbs` code snippet, theres a sentence that states:

"Clicking the anchor element will send the action to the component. Ember will then go into the actions hash and call the toggleImageSize function."

We need to introduce what an actions hash is.

The next sentence might say something like:
```
An "actions hash" is an object in the component that contains functions.
These functions are called when various UI actions occur, stemming mostly from user interaction.
```

**Comment by theroncross** [comment]
Should this be closed?

**Comment by toddjordan** [comment]
yup!  thanks @RyanNerd
