### ISSUE TITLE
Translate to other languages.

### ISSUE THREAD

**Issue by kentaro0919** [emberjs/guides#188]
For non English speaker it is nice to be able to read in your own language.
If we use https://www.transifex.com , we can add translation to the guide.
It is free for open source.

**Comment by trek** [comment]
The idea of translating has come up multiple times over the years but nobody has pitched specifically how this will work. The old guides changed very frequently, an previously translation efforts in the community were not able to keep up.

Versioned guides mitigate this problem somewhat – once a guide is published we leave its content in place – but open up a new problem: The entire set of guides would need to be re-translated every six weeks.

There are also the significant social issues around translations: identifying and vetting translators and their translations. _Many_ effort at translations I've seen are performed by over-eager beginners in a new language or ESL with low English proficiency.  As someone who isn't fluent in Japanese (as an example), who do I :+1: a translation. If two translators disagree about a Finnish translation, how does the core team make an executive decision?

We've never said "no" to the idea of translating the docs. In fact, the core team would **love** this. It would also be a great way for community member with the requisite languages skills to contribute significantly.

However, planning how this process works is significantly more effort than selecting a specific tool or service.

The **call to action** on this is: are _you_ willing to investigate and write up a detailed proposal on how this would work so the core team can easily :+1:? If not, who is this person?

**Comment by trek** [comment]
Closing this for now, as it's known desired feature, we just need a contributor to do the work or write up a plan of action.
