### ISSUE TITLE
Let  https://guides.emberjs.com/tutorial  direct to latest

### ISSUE THREAD

**Issue by sheriffderek** [emberjs/guides#1893]
It would be great for linking to have `https://guides.emberjs.com/tutorial`  direct to the latest tutorial instead of a 404.

**Comment by acorncom** [comment]
@sheriffderek You can use https://guides.emberjs.com/current/tutorial/ember-cli/, does that work?

**Comment by sheriffderek** [comment]
That will certainly work. It's not very intuitive, though. My use case is just for blog articles and times where you want to quickly link to the tutorial. http://emberjs.com/tutorial would probably be the best to redirect. Anyway. Got it! Thanks.
