### ISSUE TITLE
SuperRentals model attribute 'type' may not be JSONAPI spec compliant

### ISSUE THREAD

**Issue by greyhwndz** [emberjs/guides#1894]
If the field names used by the model in SuperRentals tutorial will be adopted by a JSONAPI-spec-compliant backend, we may encounter a problem.

Here is an example backend in Phoenix/ja_serializer with the `type` incorrectly set by the value of the `type` field found in `attributes`:
https://github.com/greyhwndz/phoenix_api#when-i-curl-to-the-api

This behavior may be in compliance of the JSONAPI specs particularly found here:
http://jsonapi.org/format/#document-resource-object-fields

I think the `type` attribute can be renamed to `rentalType` or something better to avoid this problem.

**Comment by jenweber** [comment]
I can work on this. @toddjordan if I fix the guides themselves and screenshots, is there anything else that should be updated (like the canonical, finished app)? I'm also assuming that the other language pages are autogenerated, and I should only worry about changing code blocks in the English pages, right?

I've confirmed that the superRentals example would not be JSONAPI compliant as-is, according
to [this part of the documentation](http://jsonapi.org/format/#document-resource-object-fields) :

> Fields for a resource object MUST share a common namespace with each other
and with type and id. In other words, a resource can not have an attribute and
relationship with the same name, nor can it have an attribute or relationship named type or id.

**Comment by toddjordan** [comment]
Correct.  Just update the the base (English) file. Thanks!!!

**Comment by jenweber** [comment]
PR https://github.com/emberjs/guides/pull/1953
