### ISSUE TITLE
Tutorial 'Building a Complex Component' has a broken link

### ISSUE THREAD

**Issue by wemposd** [emberjs/guides#1908]
Hello,

At chapter 'Building a Complex Component' there is a broken link https://guides.emberjs.com/components/wrapping-content-in-a-component

**Comment by travismchan** [comment]
Are you using the latest guide? If not, which version are you using? Seems to be working on my end.

**Comment by locks** [comment]
I confirm that https://guides.emberjs.com/v2.12.0/tutorial/autocomplete-component/ is working for me too.

**Comment by travismchan** [comment]
Oh, I see what OP is referring to. I've made a pull request for the fix (hopefully it's correct, first contribution). It was in reference to the paragraph with "This is an example of the block form of a component". I was looking at the side links.

**Comment by locks** [comment]
Whoops, I read it as the link to the Building Complex Component guide was wrong.

**Comment by locks** [comment]
PR with the fix has been merged. Thank you!
