### ISSUE TITLE
Add documentation for value property in actions

### ISSUE THREAD

**Issue by NLincoln** [emberjs/guides#1915]
The action helper accepts a value helper. It's useful when the argument passed to the action is a hash, and you're only looking for a certain property on the hash. It's insanely useful, but it's not documented what it does with multiple arguments, anywhere that I can find. It would be amazing if we could add docs about this to the guides, because currently new users see `value="key"` on actions and get confused.

An example of the value helper can be found [here](https://github.com/cibernox/ember-power-calendar/blob/master/tests/dummy/app/templates/snippets/action-handling-1.hbs)

```hbs
{{#power-calendar
  center=center
  onCenterChange=(action (mut center) value="date") as |calendar|}}
  {{calendar.nav}}
  {{calendar.days}}
{{/power-calendar}}
```

**Comment by acorncom** [comment]
@NLincoln One of the things we wrestle with in the guides is how much to provide a ton of detail on the api surface of Ember and how much to encourage folks to explore the api docs for further info.  In this case, the `value` option for the `action` helper is already documented here: https://emberjs.com/api/classes/Ember.Templates.helpers.html#method_action

Would that handle things for you well enough?

**Comment by NLincoln** [comment]
Yes, that will work. I guess I should have looked harder in the guides :+1:
