### ISSUE TITLE
Fix the search box on our 404 page

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#1925]
If folks hit this a 404 page (try this one as an example: https://guides.emberjs.com/v2.12.0/models/working-with-relationships/) you may want to do a search for what you are after.  Sadly, it looks like our current 404 page (https://github.com/emberjs/guides.emberjs.com/blob/master/snapshots/404.html) may be using our older search system.

We'll need to reference the newer JS files (and put in the appropriate HTML) that is built as part of our guides pages these days ...

**Comment by brianhays** [comment]
Submitted PR to fix the 404 page
