### ISSUE TITLE
This Guide one pager to export as .mobi .pdf etc.

### ISSUE THREAD

**Issue by hugovieilledent** [emberjs/guides#193]
This guide is currently on several pages.
Any solution to merge all in one page so I can export this to my Kindle?

Thanks!

**Comment by michaelrkn** [comment]
The Guides are in a [Middleman](http://www.middlemanapp.com/) app, and there doesn't appear to be a PDF exporter in the [extension directory](https://directory.middlemanapp.com/#/extensions/all). You should write one :)

**Comment by trek** [comment]
This currently isn't available. We try to keep Issues to actionable items. If you'd like to write a longer issues describing how this could be implemented, please feel free to open a new issue.
