### ISSUE TITLE
Adding Google maps script to tests/index.html in Services and Utilities section of tutorial

### ISSUE THREAD

**Issue by AlexanderEllis** [emberjs/guides#1931]
I noticed some of my rental listing component integration tests failing after completing this section, and it looks like it was because it wasn't accessing the Google maps script correctly (resulting in "TypeError: Cannot read property 'maps' of undefined" when it attempted to access window.google.maps.  I had added the Google maps script to my app/index.html, but it still wasn't working.  

I checked with the completed code repo, and it looks like the [script was added to tests/index.html as well.](https://github.com/ember-learn/super-rentals/blob/master/tests/index.html#L29)  Once I added the script reference in tests/index.html, the tests passed as expected.

Should the tutorial page mention adding the script to the tests/index.html page as well, or is there something I am overlooking?

Thanks!

**Comment by toddjordan** [comment]
no, we should.  good catch.

**Comment by jakkubu** [comment]
Should it though? Shouldn't maps API be stubbed in all tests?

**Comment by toddjordan** [comment]
@jakkubu is right, we shouldn't have a dependency on google maps.  if we do we need to update the tests to effectively stub the dependency.

**Comment by toddjordan** [comment]
latest super rentals code should require no manual updates to the tests index.html.  checking repo tonight to make sure things are now working as expected.

**Comment by toddjordan** [comment]
no longer an issue with the latest version of guides and super-rentals repo
