### ISSUE TITLE
Block params version of each

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#196]
[Templates: Displaying a List of Items](http://guides.emberjs.com/v1.11.0/templates/displaying-a-list-of-items/) doesn't mention anything about using block params with the `each` helper.

Should the current examples be updated to use block params or should block params be shown in addition to the `each .. in ..` version?

**Comment by rwjblue** [comment]
Each...in is deprecated (or will be very soon) in 1.12.0-beta.2 (along with with..as). We should definitely make sure we are not using the deprecated syntax in these guides.

**Comment by HeroicEric** [comment]
Closing this since those ^^ were merged
