### ISSUE TITLE
[dev] Ruby version 2.3.4-p301 doesn't work in Mac dev env

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#1966]
In order to run the Guides locally, I had to change .ruby-version to 2.3.4 instead of 2.3.4-p301. The version currently specified is not available in rbenv, the tool that is necessary to develop in Ruby on Macs. Rbenv follows the version syntax specified in Ruby's [list of releases](https://www.ruby-lang.org/en/downloads/releases/).

@antonfefilov do you think this will cause any problems to change ruby version to 2.3.4? I don't know much about developing in a ruby environment. What does the "p301" mean?

**Comment by locks** [comment]
The `p` is for patch, which was more frequent in Ruby, but seems like it isn't anymore?
