### ISSUE TITLE
Broken link in the cookbook section (only if you follow a certain order)

### ISSUE THREAD

**Issue by nicolechung** [emberjs/guides#20]
Click Cookbook.

Click introduction.
http://localhost:4567/cookbook/

Scroll down and click the link that says "participating if you know Ember"
http://localhost:4567/cookbook/contributing/participating_if_you_know_ember

Scroll down that page and click the "next-guide" link, 
"Participating if you don't know Ember"

Link does not work, it goes here:
http://localhost:4567/cookbook/participating_if_you_dont_know_ember/

It should go here:
http://localhost:4567/cookbook/contributing/participating_if_you_dont_know_ember

Note: Once you are on a page where the "previous" and "next" links don't work, then the sidebar links stop workiing.

**Comment by trek** [comment]
I can't reproduce this :(

http://guides.emberjs.com/v1.10.0/cookbook/ seems to work in production. Possibly got fixed already?

**Comment by nicolechung** [comment]
Hmm maybe some of the links in the page need to be fixed?

http://guides.emberjs.com/v1.10.0/cookbook/helpers_and_components/

If you click any of the following they are broken:
Creating Reusable Social Share Buttons
A Spinning Button for Asynchronous Actions
Adding Google Analytics Tracking

Links on this page are broken for me:
Incrementing Or Decrementing A Property
Setting Multiple Properties At Once
Continuous Redrawing of Views

Other sections seem to be ok.

**Comment by trek** [comment]
Sorry, I'm a bit confused. Is that related to the original issue?

**Comment by nicolechung** [comment]
Sorry, my bad, it's separate. I think they're just broken links, going to fix them in the PR I have going...

**Comment by trek** [comment]
Ah! Now I get it. A PR would be great. I'd guess the values is data/guides.yml don't match the locations of the markdown files.
