### ISSUE TITLE
Update Managing Dependencies post Ember CLI 2.15

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#2017]
[Section of the guides to update](https://guides.emberjs.com/v2.14.0/addons-and-dependencies/managing-dependencies/)

Ember CLI 2.15 has a new feature that allows using `app.import` of npm module assets in the same way that was done with Bower assets.

**To do:**
- [ ] remove references to Bower
- [ ] add instructions for app.import of node modules assets
- [ ] Describe app.import caveats in a beginner-friendly way
- [ ] Give better clues about how to handle npm resources that are not `app.import()`-able

A gotcha of app.import is that it only works for single files, not like with browserify etc. that resolves `require()` statements of an entire module. It will be able to replace Bower, but it will not work for any random npm package. You can import specific assets (CSS, for example) or built npm packages that have browser-ready files.

This page of the guides should not mention any 3rd party addons by name.

**Resources**
Deeper explanation of [pre-2.15 approach to npm modules](https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli.html)

**Comment by serenaf** [comment]
@jenweber I will give this a try :)
