### ISSUE TITLE
change routing to use /current for latest version to improve google search results

### ISSUE THREAD

**Issue by HaithamMaya** [emberjs/guides#2068]
Often times when searching on google, links to the docs end up going to previous versions. If the latest documentation used `/current` instead of just re-routing, older links indexed by google can still go to the latest version of the documentation.

Example:
A search for [ember routing](https://www.google.com/search?q=ember+routing&rlz=1C5CHFA_enUS758US758&oq=ember+routing
), results in:

![screen shot 2017-09-18 at 10 22 25 am](https://user-images.githubusercontent.com/8363383/30546743-6f20d474-9c5b-11e7-9705-9aae1ebd72c4.png)

So if the first result linked to https://guides.emberjs.com/current/routing/ instead of https://guides.emberjs.com/v2.14.0/routing/, we would see v2.15 docs for routing.

**Comment by yawboakye** [comment]
@HaithamMaya There's an ongoing issue here https://github.com/emberjs/guides/issues/1816. Feel free to follow and/or contribute over there. Thank you.

**Comment by locks** [comment]
I'm closing this issue, let's track it in #1816 like @yawboakye mentioned. Thanks for your concern @HaithamMaya, SEO for versioned documentation is a pain.
