### ISSUE TITLE
API links are somehow broken

### ISSUE THREAD

**Issue by sly7-7** [emberjs/guides#2082]
I don't know what's happening, but clinking on a link pointing to an api method end up to a wrong url in the browser. 

For example: http://emberjs.com/api/classes/Ember.Router.html#method_map is transformed to 
https://emberjs.com/api/classes/Ember.Router.html/methods/map?anchor=map&show=inherited,protected,private,deprecated

**Comment by jenweber** [comment]
Hey, thanks for reporting this. We're working to fix it!

Related: https://github.com/ember-learn/ember-api-docs/issues/355

**Comment by toddjordan** [comment]
the link in question should work now.
