### ISSUE TITLE
version 1.11.x absent

### ISSUE THREAD

**Issue by ahnbizcad** [emberjs/guides#213]
I git cloned, and git pulled, but when I open the app in localhost, only 1.10.0 and 1.9.0 are available.

**Comment by varblob** [comment]
Look at the branches.
The whole repo gets snapshotted and put into https://github.com/emberjs/guides.emberjs.com and then served from there.

**Comment by trek** [comment]
@varblob is correct. We store snapshots elsewhere. The stub JSON file for versions is just so developers can contribute to the code around versions switching.
