### ISSUE TITLE
Code highlighting either extends past codeblock or doesn't cover code

### ISSUE THREAD

**Issue by codypearce** [emberjs/guides#2151]
The code highlighting width either extends past the code block

![extending-past](https://user-images.githubusercontent.com/12564956/34320142-e1ae38e6-e7c0-11e7-8c6b-0280fa996302.png)

![extending-past-2](https://user-images.githubusercontent.com/12564956/34320143-e42bde70-e7c0-11e7-86bf-e6d04fbe489e.png)

or doesn't cover the code it should

![not-covering](https://user-images.githubusercontent.com/12564956/34320145-ec91b800-e7c0-11e7-916e-86c69b3ca384.png)

These examples are from https://guides.emberjs.com/v2.17.0/tutorial/routes-and-templates/

**Comment by jenweber** [comment]
@codypearce thanks for reporting!

Looks like `width: 98%` might fix it.

**Comment by michaelfich** [comment]
@jenweber I'll take a shot at this one

**Comment by acorncom** [comment]
Closed by #2159
