### ISSUE TITLE
Error "registry error parsing json" creating new quickstart app

### ISSUE THREAD

**Issue by susannakosic** [emberjs/guides#2154]
Hi! I m kicking off a pet project using Ember. I m following guidelines described in [getting started](https://guides.emberjs.com/v2.17.0/getting-started/quick-start/).

Dependencies are ok according to [installing ember](https://guides.emberjs.com/v2.17.0/getting-started/):
node v6.12.2
npm v3.10.10
ember-cli: 2.17.2

When I run:
`ember new ember-quickstart` 
I get the following error: 
`Error creating new application. Removing generated directory "./ember-quickstart"
Command failed: npm install --no-optional --loglevel error
npm ERR! registry error parsing json`

Is this a known issue?

**Comment by jenweber** [comment]
Hi @susannakosic, sorry to hear you are having trouble. That is not a known issue. Would you try updating your npm installation and let me know if it persists? Thank you!

Also I want to let you know about the Ember Community Slack. You can drop by the #help channel for immediate Q&A if you run into any issues in the future (not just bugs). https://ember-community-slackin.herokuapp.com/

**Comment by susannakosic** [comment]
Hi @jenweber - After installing bower globally the issue disappeared.    :7

**Comment by jenweber** [comment]
Glad it's fixed! Thanks for the update.
