### ISSUE TITLE
Need to update `welcome-page` screenshots

### ISSUE THREAD

**Issue by locks** [emberjs/guides#2167]
The instructions on how to remove the addon have changes since the screenshot:

https://guides.emberjs.com/v2.18.0/tutorial/ember-cli/#toc_the-development-server
https://github.com/ember-cli/ember-welcome-page/blob/master/addon/templates/components/welcome-page.hbs#L18

**Comment by williamhaley** [comment]
@locks I created a with a screenshot reflecting the latest text from the welcome component using ember-cli@2.18.0
