### ISSUE TITLE
The "edit" button may lead to a 404

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#222]
If a page has been renamed or moved since a release, the "edit" button that looks like a pencil in the upper right corner will lead to a 404, eg http://guides.emberjs.com/v1.11.0/ember-cli/.

**Comment by raindev** [comment]
I've encountered the same errors. However it looks like the link has been fixed in the `master` already and the app just hasn't been deployed since then. See [here](https://github.com/emberjs/guides/blob/master/lib/toc.rb#L98).

**Comment by mixonic** [comment]
This is pretty bad.

**Comment by michaelrkn** [comment]
We could do a little AJAX HEAD check that the link doesn't lead to a 404, something like:

```javascript
var exists = $.ajax({type: 'HEAD', url: url});

if (exists === 200) {
  window.location = url;
} else {
  if (confirm("This page doesn't exist in the most recent revision of the guides. Click OK to go to the main guides repository so you can look for the file to edit, or Cancel to stay on the current page.")) {
    window.location = "https://github.com/emberjs/guides/tree/master/source";
  }
}
```

Does that seem okay?
