### ISSUE TITLE
404 on Application Tests

### ISSUE THREAD

**Issue by chris-aeviator** [emberjs/guides#2234]
currently a visit on https://guides.emberjs.com/v3.0.0/acceptance – found as **Application Tests** on https://guides.emberjs.com/v3.0.0/testing/ returns as a 404

**Comment by jenweber** [comment]
Thanks for reporting, Chris!

If any contributors want to help out, the link to fix is on [this page in the guides](https://guides.emberjs.com/v3.0.0/testing/) and [this file in the GitHub repo](https://github.com/emberjs/guides/blob/master/source/testing/index.md):

>For tests that require a full application setup we can use the setupApplicationTest helper. You can read more about how to create these kinds of tests in the [Application tests]() section.

It should be changed to `https://guides.emberjs.com/current/testing/acceptance/` (not sure about the trailing slash - check to see how other links are done)
