### ISSUE TITLE
Components page doesn't say what a component is for

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#2259]
Currently, the [component section of the Guides](https://guides.emberjs.com/v3.0.0/components/defining-a-component/) does not fully express what a component is or is used for.

A very short (3 sentences or less) description of what a component is should be added to the beginning of the above section of the Guides.

Check through the [Super Rentals Tutorial](https://guides.emberjs.com/v3.0.0/tutorial/ember-cli/) for ideas, [plus the API docs](https://emberjs.com/api/ember/release/classes/Component). We want to use language consistent with what is already in place across the Guides and API docs.

If this is your first contribution to the Ember Guides, please review [our contributing guidelines](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md) before submitting any changes.

_Note, this issue is set aside for the EmberConf contributors workshop on 3/12. If it's not claimed by the end of that day, feel free to grab it!_

**Comment by AshlenPrice** [comment]
I think I'll take a stab at this.

**Comment by jenweber** [comment]
closed via PR #2275
