### ISSUE TITLE
Need to explain what a hook is

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#2261]
In the Guides, we talk about `hooks` [here](https://guides.emberjs.com/v3.0.0/routing/specifying-a-routes-model/), [here](https://guides.emberjs.com/v3.0.0/tutorial/model-hook/) and [here](https://guides.emberjs.com/v3.0.0/components/the-component-lifecycle/), but new developers are often not familiar with this term. 

Find where `hook` is mentioned in the Guides and Super Rentals tutorial, pick the best place(s) to define `hook` and propose a definition.

_Note, this issue is set aside for the EmberConf contributors workshop on 3/12. If it's not claimed by the end of that day, feel free to grab it!_

**Comment by jasonworden** [comment]
@jenweber @locks Can we close this issue now that the PR is merged? :)))

**Comment by acorncom** [comment]
@jasonworden sure can, thanks! 😀
