### ISSUE TITLE
Computed properties need a clearer warning about when they get updated

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#2263]
https://guides.emberjs.com/v3.0.0/object-model/computed-properties/

Computed properties need a clearer warning that they only get updated when you call them or when they are being used in the markdown of an active template. This has probably bitten every Ember developer. Check this section over and see if it needs something stronger/clearer.

_Note, this issue is set aside for the EmberConf contributors workshop on 3/12. If it's not claimed by the end of that day, feel free to grab it!_

**Comment by Bestra** [comment]
I'll pick this up.
