### ISSUE TITLE
In ember tutorials: acceptance tests now fail after Mirage is added

### ISSUE THREAD

**Issue by algo74** [emberjs/guides#2272]
Mirage does not start by default during tests.

I had to add `setupMirage(hooks);` to make it work again

some helpful info: https://stackoverflow.com/questions/49215315/mirage-responds-404-on-acceptances-tests

**Comment by toddjordan** [comment]
Good catch... The tutorial was made with 0.4.1, which worked as is, but it looks like 0.4.2 requires the extra call.

**Comment by acorncom** [comment]
Fixed by #2290
