### ISSUE TITLE
Explain `.[]` before `.@each` in "Computed Properties and Aggregate Data"

### ISSUE THREAD

**Issue by locks** [emberjs/guides#2273]
Guide: https://guides.emberjs.com/v3.0.0/object-model/computed-properties-and-aggregate-data/

This guide explains `@each`, and then compares it to `[]` but there is no explanation of what `[]` is, making the property confusing.
There are also many cases where `[]` is the appropriate API to use, but people only know about `@each`.

**Comment by Bestra** [comment]
I'll plan on picking this up some time this week, but if anyone else is burning to take it from me let me know!

**Comment by acorncom** [comment]
Closed by #2282
