### ISSUE TITLE
Brace expansion on non-nested properties?

### ISSUE THREAD

**Issue by sbatson5** [emberjs/guides#2291]
I was looking at the guides for computed properties and saw the section talking about brace expansion for dependent keys.  The example shown is:

```
  fullName: computed('{firstName,lastName}', function() {
    let firstName = this.get('firstName');
    let lastName = this.get('lastName');

    return `${firstName} ${lastName}`;
  })
```

I had always thought it was bad practice to do brace expansion on `this`.  I.e.
`person.{firstName,lastName}` would be fine but `{firstName,lastName}` isn't.  I feel like otherwise, you would never _not_ use brace expansion.  You could do things like:
`{someService.foo.bar,person.firstName,income,etc}`

**Comment by acorncom** [comment]
@sbatson5 I would tend to concur. Would you mind sending in a PR and we’ll fix it?

**Comment by sbatson5** [comment]
PR here: https://github.com/emberjs/guides/pull/2294 @acorncom
