### ISSUE TITLE
More clear polymorphism example code

### ISSUE THREAD

**Issue by rickypowell** [emberjs/guides#2297]
As I was reading through [Models: Relationships Polymorphism](https://guides.emberjs.com/v3.0.0/models/relationships/#toc_polymorphism) section, I noticed that the `app/models/payment-method-cc.js` is missing the `last4: DS.attr()` declaration. The immediate following example, `app/models/payment-method-paypal.js`, there is the `linkedEmail: DS.attr()`. This is an error in the code example because `last4` must be declared in order for this code example to actually work when run in an Ember project. This may have been an over site from the initial commit of this example. 

For consistency sake and aid people getting started to Ember, I suggest we declare `last4` for the code snippet. This way,`this.get('last4')` can return the expected value.

**Comment by jenweber** [comment]
Closed with #2298 

Thanks!!!
