### ISSUE TITLE
creating records with relationships needs more detail

### ISSUE THREAD

**Issue by jenweber** [emberjs/guides#2307]
The explanation for creating belongsTo/HasMany records is [a bit sparse](https://guides.emberjs.com/v3.0.0/models/relationships/#toc_creating-records). Could use more detail about the order the records need to be created in and how they're being associated.

**Comment by karan-pathak** [comment]
@jenweber I restructured the documentation and added some things in https://github.com/emberjs/guides/pull/2318, dont know for sure if this is what you wanted.

**Comment by jenweber** [comment]
Closed with #2318 😄
