### ISSUE TITLE
Actions.md broken links

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/guides#235]
Didn't know quite the right place to report this.

This is giving a 404:
http://guides.emberjs.com/images/template-guide/action-bubbling.png

This link is dead:
http://guides.emberjs.com/guides/understanding-ember/the-view-layer/#toc_adding-new-events

**Comment by IanVS** [comment]
That same dead link is also on http://guides.emberjs.com/v1.11.0/templates/actions/#toc_specifying-the-type-of-event

**Comment by nicolechung** [comment]
I'd like to fix this, but I'm a little confused about where (i.e. tag or master) to fix these.

**Comment by trek** [comment]
Master.

**Comment by nicolechung** [comment]
Ok will do. Give me the weekend.

**Comment by jpadilla** [comment]
Those dead links should probably link to http://emberjs.com/api/classes/Ember.View.html#toc_event-names now

**Comment by mostwanted1976** [comment]
still broken:

http://guides.emberjs.com/v1.10.0/templates/actions/ > "listed in the View guide"

**Comment by prikhi** [comment]
This was fixed & can be closed? Just needs #325 so that it'll show up.

**Comment by rwjblue** [comment]
Thanks for confirming!
