### ISSUE TITLE
getting-started/glossary.md broken link

### ISSUE THREAD

**Issue by dpdawson** [emberjs/guides#236]
I'm not sure where the issue lies, because the markdown seems to be parsed correctly on Github, but the following link is broken at http://guides.emberjs.com/v1.11.0/ember-cli/glossary/:

* [ES6 support](http://kangax.github.io/compat-table/es6/)

It has a double quotation mark (%22 actually) appended to the end of the linked url.

**Comment by Dhaulagiri** [comment]
This was fixed by #113

**Comment by dpdawson** [comment]
My bad. The file was renamed and I didn't see that commit in the history.

**Comment by Dhaulagiri** [comment]
Yeah, it confused me too for a second there as well @dpdawson
