### ISSUE TITLE
Clarification Needed on Testing Setup

### ISSUE THREAD

**Issue by jdhines** [emberjs/guides#238]
Maybe it's just because I'm having what feels like an unreasonably hard time understanding how to get testing started, but in reference to the [Integration Tests](http://guides.emberjs.com/v1.10.0/testing/integration/) page, where do those first three things, starting with `App.rootElement = ...` go? It doesn't say, and maybe it's obvious to a long-time user, but to someone like me reading the guides, I don't know.
I'm looking at start-app.js in a brand-new ember-cli 0.2.3 app, and I'm trying to recreate the examples in Testing Components, and I see `application.setupForTesting();` and `application.injectTestHelpers();` but no `App.rootElement`. The docs use `App.` but ember-cli uses `application.` Anyway, in my test I apparently can't use `find()` or `click()` as I get an error saying they're undefined, which indicates the test helpers are not actually being injected, and I can't find something in the guides that will help me figure out what to do.

**My test (unit/components/my-foo-test.js):**
````
import {
  moduleForComponent,
  test
} from 'ember-qunit';

moduleForComponent('my-foo','MyFooComponent');
test('clicking link updates the title', function(assert) {
  // creates the component instance
  var component = this.subject();
  assert.equal(this.$().find('h2').text(), 'Hello World');
  //perform click action
  click('button');
  assert.equal(this.$().find('h2').text(), 'Hello Ember World');
});
````

**Comment by jdhines** [comment]
Is App.rootElement not needed in 1.11?

**Comment by Serabe** [comment]
1.10 guide wasn't migrated to ember cli yet.

**Comment by michaelrkn** [comment]
This is no longer needed in present versions, and since old versions of guides aren't maintained, this should be closed. cc @rwjblue
