### ISSUE TITLE
Missing understanding-ember/keeping-templates-up-to-date (404)

### ISSUE THREAD

**Issue by dpdawson** [emberjs/guides#242]
http://guides.emberjs.com/understanding-ember/keeping-templates-up-to-date is returning a 404 and is missing from the repo.

**Comment by trek** [comment]
Can you tell us where you found a link to this?

**Comment by dpdawson** [comment]
Under Understanding Ember.js in the sidebar of every page.

**Comment by trek** [comment]
For which versions?

**Comment by dpdawson** [comment]
1.11.0

**Comment by trek** [comment]
Was fixed on master. I've fixed on v1.11.0 and republished.
