### ISSUE TITLE
Extra quotes on ES6 link (leads to 404)

### ISSUE THREAD

**Issue by markhealey** [emberjs/guides#247]
Small one: found a [link](http://guides.emberjs.com/v1.11.0/ember-cli/glossary/#toc_es3-es5-es5-1-es6-aka-es2015-etc) that leads to a 404 because it is malformed. Looks correct in the [Markdown source](https://github.com/emberjs/guides/blob/master/source/getting-started/glossary.md#es3-es5-es51-es6-aka-es2015-etc), however. 

![screen shot 2015-04-20 at 12 29 22 pm](https://cloud.githubusercontent.com/assets/22938/7237503/25c51420-e759-11e4-99e3-1309cd9841f4.png)

The "ES6 Support" link is broken:

`http://kangax.github.io/compat-table/es6/"`

**Comment by Dhaulagiri** [comment]
This was fixed by #113.  I'm not sure what the delay is in seeing these changes deployed to the live docs (maybe related versioning?), so maybe @trek can comment on that?

**Comment by trek** [comment]
They're on master, which will become the 1.12 guides. our goal is to avoid needing to make corrections to past guides
