### ISSUE TITLE
app.js introduced but not explained in naming-conventions.md

### ISSUE THREAD

**Issue by eostrom** [emberjs/guides#251]
http://guides.emberjs.com/v1.11.0/concepts/naming-conventions/ says that on boot Ember looks for three modules, including `app/app.js`. The other two modules are then described by the text, but `app.js` is not. The text does describe `app/routes/application.js`, which should probably be included in the list of modules.

My guess is that `app/app.js` should just be changed to `app/routes/application.js`, but I'm just learning, so I don't know.

**Comment by kpfefferle** [comment]
@eostrom `app/app.js` is auto-generated by ember-cli when creating a new project:
```
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';

Ember.MODEL_FACTORY_INJECTIONS = true;

var App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;
```

**Comment by eostrom** [comment]
Thanks. In this context, the document is talking about what Ember looks for at boot time, and what it does with what it finds. It renders the template in `application.hbs`, and instantiates the controller in `application.js` (if any). I think if the documentation mentions `app.js`, it should say something about what it's for; maybe just say it's the Application, and link to the Application page.

If that makes sense, I'll submit a pull request to add that, and add the route to the list of application-level modules.

**Comment by michaelrkn** [comment]
Thanks for opening this issue, @eostrom!

I appreciate that maybe this leaves an open question, but the guides aren't meant to be comprehensive, and I'm not sure there's a lot to be gained by explaining `app.js` given that it's usually just boilerplate. If anything, I'd suggest we take out "Ember will look for the objects exported by these modules in your project: app/app.js, app/controllers/application.js, app/templates/application.hbs" so it reads "When your application boots, Ember.js will render the application template...". I've opened #424 to do so. 

@rwjblue, can you close this out, unless anybody else thinks differently?
