### ISSUE TITLE
JSBIN not working on specifying a routes model

### ISSUE THREAD

**Issue by laantorchaweb** [emberjs/guides#277]
If you enter this page (v1.10 or v1.11):

http://guides.emberjs.com/v1.11.0/routing/specifying-a-routes-model/

The first JSBIN on the page is trying to get this script:

http://builds.emberjs.com/ember-latest.js

![ember_js_-_routing__specifying_a_route_s_model](https://cloud.githubusercontent.com/assets/930943/7439862/907da20c-f067-11e4-9829-e9e389cea971.jpg)

But this URL is throwing a 404.

![404_not_found](https://cloud.githubusercontent.com/assets/930943/7439861/87944b00-f067-11e4-816f-3bf45d4b1c52.jpg)

The second JSBIN on the page is specifying assets using http but JSBIN is being loaded though https, it should be loading the assets using https or just let the browser handle the request using ```src="//"``` because some browsers will refuse to load insecure assets.

Because the issue is on the JSBIN files and not in the repository I can't make a PR for this, but if I can help with something let me know.

**Comment by michaelrkn** [comment]
@trek @rwjblue any idea whose jsbins these are?

Also, the policy is not to maintain guides for old versions, but this feels like maybe an okay exception to that rule since it's on a third-party site.

**Comment by michaelrkn** [comment]
JS Bin on http://guides.emberjs.com/v1.12.0/routing/query-params/ is also broken - thanks to @iharsuvorau for pointing out.

**Comment by michaelrkn** [comment]
@billybonks can you update http://jsbin.com/lihenu/1/edit?html,js,output to load Ember from http://builds.emberjs.com/tags/v1.11.3/ember.debug.js, and all of the examples at the bottom of http://guides.emberjs.com/v1.11.0/routing/query-params/ to load Ember from http://builds.emberjs.com/tags/v1.13.4/ember.js?

@bsclifton can you change http://jsbin.com/sefuv/2/edit?html,js,output to load assets over the relative protocol?

Thanks!!

**Comment by billybonks** [comment]
@michaelrkn can do but from what i last heard was that the jsbins where being removed from the site

**Comment by michaelrkn** [comment]
They are but we might as well fix old versions of the guides when it's so
easy to do so. Thanks!

**Comment by michaelrkn** [comment]
@billybonks do you think you could work on this at some point this week?

@bsclifton ping

**Comment by michaelrkn** [comment]
Closed in favor of #483. But it would still be great to get the existing jsbins fixed :)

**Comment by billybonks** [comment]
I'll try fix them this week when I find some downtime

**Comment by michaelrkn** [comment]
Thank you!!!

**Comment by bsclifton** [comment]
Hey there, sorry @michaelrkn - I've been out of the Ember game for a while :( Had a great time contributing and hope to be able to come back (taking a siesta for a bit). Thanks for hanging in there and making great changes :smile:

**Comment by locks** [comment]
@bsclifton check the need help tag and ping us in the documentation channel on the Slack community

**Comment by michaelrkn** [comment]
@bsclifton rest up and we can't wait to have you back!

**Comment by locks** [comment]
@michaelrkn said! I misread and thought you were coming back now, hence my advice.
