### ISSUE TITLE
Missing Tags and Package.json

### ISSUE THREAD

**Issue by cromwellryan** [emberjs/guides#279]
I'm looking into auto publishing guides via travis and divshot cli.  I noticed that two parts of the docs in `master` seem a bit off.  Trying to figure out if I can rely on them.

First, [publishing](https://github.com/emberjs/guides#publishing) suggests tags are created for each release of guides.  I'm not seeing [any tags](https://github.com/emberjs/guides/tags).

Second, it looks like there is a publishing script for `npm stage`.  I'm not seeing a `package.json` file at all.  To make this work, we'll need `divshot-cli` in the devDependencies.

**Comment by trek** [comment]
I think what you're looking for is on the publication repo https://github.com/emberjs/guides.emberjs.com?

from the readme:

> To publish a new Guide version, you'll also need a copy of the Guides site repo:
> https://github.com/emberjs/guides.emberjs.com
