### ISSUE TITLE
Update Dependency Injection and Service Lookup with 1.10 features

### ISSUE THREAD

**Issue by nicolechung** [emberjs/guides#282]
1. It would be nice to see examples of how to create and use Ember services, kind of like in this post:
http://stackoverflow.com/questions/27932790/how-to-do-dependency-injection-in-ember-with-ember-cli

2. Also nice to see more examples of how to inject services, in particular the ```Ember.inject.service()``` from 1.10:
http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html

**Comment by mixonic** [comment]
Several updates are in this PR https://github.com/emberjs/guides/pull/420 closing this in favor of that.
