### ISSUE TITLE
templates/development-helpers - breakpoint and helper attributes and get function

### ISSUE THREAD

**Issue by baijum** [emberjs/guides#287]
When using `{{debugger}}` helper inside template, the browser console get two helper attributes and `get` function. This message is displayed in the console:

```
Use `view`, `context`, and `get(<path>)` to debug this template.
```

However, the current document gives different attribute names: `templateContext` & `typeOfTemplateContext`

**Comment by michaelrkn** [comment]
Fixed by #417. @rwjblue can you please close?
