### ISSUE TITLE
The anchor link image to headers is broken

### ISSUE THREAD

**Issue by rinti** [emberjs/guides#288]
I recently wanted to link to a specific part in the guides, but couldn't find an anchor link anywhere.
After futher investigation there is one, but the image is broken.

`a.toc-anchor` has `background: url("/images/link.png") no-repeat;` but the image is now in `/images/<specific ember version>/link.png` like so: http://guides.emberjs.com/v1.11.0/images/link.png

**Comment by rwjblue** [comment]
Would you mind making a PR to make the link relative?
