### ISSUE TITLE
installation guide improvement

### ISSUE THREAD

**Issue by pedrojvrccosta** [emberjs/guides#294]
Installation instructions needing update.

I just finished installing Ember following the instructions provided in the site and I faced an issue related to the version of nodejs to be installed. There is said to have the 0.10.xx and the steps to get it are there. Then is the installation of ember-cli and other tools. And here, the nodejs version required is 0.12.xx. Not knowing what was happening, I eventually had it ok, but I had to reinstall everything.

Now, let's see if I get what I hope from Ember.

BR

guide's link:
http://guides.emberjs.com/v1.11.0/ember-cli/

**Comment by hugopeixoto** [comment]
It seems that you're using the guides for an old version of ember.
The current one is http://guides.emberjs.com/v1.12.0/getting-started/

**Comment by michaelrkn** [comment]
@rwjblue can you please close?
