### ISSUE TITLE
a broken link

### ISSUE THREAD

**Issue by dd1994** [emberjs/guides#295]
In page http://guides.emberjs.com/v1.11.0/models/  

> See [Specifying a Route's Model](http://guides.emberjs.com/routing/specifying-a-routes-model)  for more information on setting a route's model.

the link to "Specifying a Route's Model" is broken.

**Comment by prikhi** [comment]
This can be closed, it was fixed in 5266b4d8

**Comment by rwjblue** [comment]
Thanks!
