### ISSUE TITLE
Use fenced code metadata to annotate both file location and language

### ISSUE THREAD

**Issue by trek** [emberjs/guides#30]
From the common mark spec:
> The line with the opening code fence may optionally contain some text following the code fence; this is trimmed of leading and trailing spaces and called the info string. The info string may not contain any backtick characters. (The reason for this restriction is that otherwise some inline code would be incorrectly interpreted as the beginning of a fenced code block.)

Where we annotate the code's language
~~~
```javascript
var someCode;
~~~

We can annotate filename and extension:
~~~
```app/templates/foo.hbs
{{rock-on}}
~~~

We have a [custom highlighter](https://github.com/emberjs/guides/blob/0c9a158855a3495ed4413c1512cb984c954adc1c/lib/highlighter.rb) that outputs particular markup/styles for specific languages.

A PR that addresses this Issue will:

- [ ] continue to detect bare named language fences
- [ ] begin to detect language name from file path fences
- [ ] output nice markup/style that decorates an HTML code block something that shows file location

@danmcclain has a [sample markup/design](https://github.com/emberjs/guides/issues/12#issuecomment-77424950)

**Comment by nicolechung** [comment]
Should I update my current PRs to the guide, or wait until this new change has been made?

**Comment by trek** [comment]
I'd update current PRs and Issue this can be a blocker for merging those

**Comment by danmcclain** [comment]
@trek Anyone covering the new custom highlighter? If not, I can take a stab at it, seems reasonable. We're going to really need to detect 2 different file types, js and hbs, right? Or are there css and html fences needed too?

**Comment by rwjblue** [comment]
@danmcclain - Its all yours :)

**Comment by danmcclain** [comment]
@rwjblue Can you confirm file types in guides? I'll try to get something in place this weekend

**Comment by rwjblue** [comment]
@danmcclain `.hbs`, `.js`, and `.html` should cover 90% of what we need, but it is possible that we want `.css` at some point also...

**Comment by joostdevries** [comment]
And considering the CLI portion, `.json` might also be a good idea (`package.json`, `bower.json`)

**Comment by nicolechung** [comment]
For the JS files, is it going to be in this format?

```javascript
```app/components/my-component.js
// javascript goes here
```
