### ISSUE TITLE
Broken Glossary Link to ES6 Support

### ISSUE THREAD

**Issue by AndrewC73** [emberjs/guides#301]
There is a typo in the link for ES6 Support in the "ES3, ES5, ES5.1, ES6 (aka ES2015), etc" section on this page:

http://guides.emberjs.com/v1.11.0/ember-cli/glossary/

The link has a trailing " on the end of it that needs to be removed. The current link is:

http://kangax.github.io/compat-table/es6/"

The actual link has no " on the end:

http://kangax.github.io/compat-table/es6/

**Comment by prikhi** [comment]
This can be closed, it was fixed in a9153d29

**Comment by rwjblue** [comment]
Thank you!
