### ISSUE TITLE
Search doesn't work.

### ISSUE THREAD

**Issue by erbridge** [emberjs/guides#309]
Go to http://guides.emberjs.com/v1.11.0/, type something into the search bar, and hit return. The page refreshes and the url changes to http://guides.emberjs.com/v1.11.0/?, but no searching happens.

**Comment by nicolechung** [comment]
To me the search works, but there is a *huge delay* (it takes about 30 seconds before the autosuggest starts populating with results).

**Comment by jdbo** [comment]
I tried this a few weeks ago and was seeing the same error as above - trying again this morning it's  now *mostly* working for me (and with no long delays), 

I did notice the following error in the console (which didn't appear to correspond to any issues with using the search), but was not able to reproduce it:

[Error] TypeError: undefined is not a function (evaluating 'jQuery21309352085902355611_1435671119771')
	(anonymous function) (suggest.json, line 1)

**Comment by michaelrkn** [comment]
I believe this is fixed on master. @locks can you confirm?

**Comment by michaelrkn** [comment]
As far as I can tell, this is working now. @rwjblue can you please close? Thanks!
