### ISSUE TITLE
Observers are "synchronous" but with a caveat.

### ISSUE THREAD

**Issue by jclem** [emberjs/guides#313]
Take this jsbin as an example: http://jsbin.com/fisuxucoko/1/edit

The guides state that [observers are synchronous](https://github.com/emberjs/guides/blob/b5b2f5194823c2030eedd43eb472c1751caf898b/source/object-model/observers.md#observers-and-asynchrony), but kind of skip over how they actually behave inside of a run loop.

Say I'm developing an addon that makes use of observers, but doesn't really care about the run loop. I'll write my tests outside of run loops, and my tests all pass. Then, I use my addon in a project and a method happens to be called inside of a scheduled function call in the run loop. Suddenly, my observers are called in a totally different order than I expect them to be called in.

The docs imply that this is how things behave if my observers call `Ember.run.once(this, 'myMethod')`, but skip over the fact that they still are only called at the end of any run loop they're inside of.

**Edit:** Turns out this is only the case when scheduling things inside of the `sync` queue, which is apparently a no-no. Either way, I think this is a possible source of confusion for others.

**Comment by mixonic** [comment]
Observers are indeed synchronous- I think perhaps you were using a binding?

I'm going to close this, and I'm unsure what action we should take to improve the observer section of the guides based on this feedback. Please feel free to reopen if I've missed anything.
