### ISSUE TITLE
Correct input helper guide information on actions.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/guides#314]
https://github.com/emberjs/guides/blob/master/source/templates/input-helpers.md#actions should be updated, and not suggest `on="foo-event" action="blahActionName"`.

We should instead recommend:

```hbs
{{input foo-event="blahActionName"}}
```

**Comment by oskarrough** [comment]
In that case, how do you specify the type of event inline?

**Comment by prikhi** [comment]
@oskarrough I'm guessing you can use `{{input submit="blahActionName" }}`. A full list is [on the API docs](http://emberjs.com/api/classes/Ember.View.html#toc_event-names)

**Comment by rwjblue** [comment]
Confirm
