### ISSUE TITLE
Broken link in Installing ember guide

### ISSUE THREAD

**Issue by gowikel** [emberjs/guides#323]
The installer ember guide (http://guides.emberjs.com/v1.11.0/ember-cli/) have a link at the botton called Ember.js guides, that must go to (http://guides.emberjs.com/v1.11.0/) but it goes to (http://guides.emberjs.com/index/.html).

**Comment by GregPK** [comment]
I have also encountered this. Tried to fix it, but the bug is not there when running middleman on localhost (master branch).

**Comment by michaelrkn** [comment]
Fixed by #383. @rwjblue can you please close?
