### ISSUE TITLE
TodoMVC tutorial is hard to find for newcomers

### ISSUE THREAD

**Issue by adamniedzielski** [emberjs/guides#324]
I wanted to re-read TodoMVC tutorial, but had difficulties when trying to find it. 

http://guides.emberjs.com redirects to http://guides.emberjs.com/v1.11.0/ and there is nothing about the tutorial in "Getting started" section. You have to change to version 1.10.0 to find the tutorial.

I believe that this tutorial was a primary learning resource for beginners. It can be worth to point to 1.10.0 version of the tutorial in 1.11.0 docs until the tutorial is updated.

**Comment by trek** [comment]
We don't plan to update the TodoMVC tutorial for newer versions of Ember.js. Some people have started work on different getting started guide for 2.0, it is just taking them longer than was anticipated.
