### ISSUE TITLE
v1.12.0 of the guides not deployed

### ISSUE THREAD

**Issue by benkonrath** [emberjs/guides#325]
Are there any plans to deploy v1.12.0 of the guides?

**Comment by F21** [comment]
Would love to see it deployed too.

**Comment by locks** [comment]
This has been fixed.
![screenshot 2015-06-08 12 42 51](https://cloud.githubusercontent.com/assets/32344/8034030/ef0889e0-0ddb-11e5-8472-081f3d53a4fe.png)

**Comment by benkonrath** [comment]
Thanks!
