### ISSUE TITLE
Broken Links on Cookbook / Helpers and Components Page

### ISSUE THREAD

**Issue by joshross4** [emberjs/guides#33]
http://guides.emberjs.com/v1.10.0/cookbook/helpers_and_components/

Has thee broken links, like this one:

http://guides.emberjs.com/guides/cookbook/helpers_and_components/creating_reusable_social_share_buttons

Which should go to here?

http://guides.emberjs.com/v1.10.0/cookbook/helpers_and_components/creating_reusable_social_share_buttons/

**Comment by joshross4** [comment]
Also in the cookbook, the links here:

http://guides.emberjs.com/v1.10.0/cookbook/user_interface_and_interaction/

**Comment by nicolechung** [comment]
This is fixed in my PR https://github.com/emberjs/guides/commit/096b219625b9c644a7a2523723531fcb300bda80

**Comment by trek** [comment]
Closing, waiting for PR so we can republish. @nicolechung are you auditing all the links?

**Comment by nicolechung** [comment]
@trek I think I'll take another look at the user_interface_and_interaction...I fixed links in two other sections other than that

**Comment by nicolechung** [comment]
Fixed the user interface section https://github.com/nicolechung/guides/commit/1b47d4dad777792fad440f8f7b900e2e98c412ef

**Comment by trek** [comment]
I don't see a PR for this. Are you blocked on it for some reason?

**Comment by nicolechung** [comment]
It's https://github.com/emberjs/guides/pull/25...maybe it's still under review? Just fixed those last links just now.

**Comment by rwjblue** [comment]
I think you meant: https://github.com/emberjs/guides/pull/25

**Comment by nicolechung** [comment]
I think I put the dots too near to the link yes!

**Comment by trek** [comment]
Ah, I meant just a PR for the broken links (which we can apply to 1.10 docs), not one that is both broken links + new stuff.

**Comment by nicolechung** [comment]
I can totally do that. Is there a 1.10 tag in this repo or do I go to the ember website repo? Getting a little confused as to where things are...

**Comment by nicolechung** [comment]
NVM found it...fixing now
