### ISSUE TITLE
Add section about initializers

### ISSUE THREAD

**Issue by wvteijlingen** [emberjs/guides#336]
With the advent of instance initializers, I was surprised that there was no mention of initializers in the main guides. The only thing I could find was a small section in the API documentation for Ember.Application.

Maybe adding a section about this to the guides would be nice.

**Comment by michaelrkn** [comment]
@locks what do you think?

**Comment by locks** [comment]
@michaelrkn I think we should document the why in the guides, especially with application/instance initializers, and then punt most of the how to the API docs (like `before`, `after`)

**Comment by michaelrkn** [comment]
It looks like this will be part of #442 sooner or later, so I'm going to close it out now.
