### ISSUE TITLE
Suggestion for "Computed properties and aggregate data with @each"

### ISSUE THREAD

**Issue by nruth** [emberjs/guides#341]
I think the current example is useful, but there should be a simpler one before it that only looks at the elements (or loading state?) of the array/association.

For example, if I have this in a model:

```coffee
questions: DS.hasMany('question')
question: (->
      @get('questions').objectAt(@get('position'))
  ).property('position', 'questions.@each')
```

Do I need the `@each` and what does it do?
What happens if I only observe questions?
Should I observe length or `@each.ids` instead?

I just found the [docs for Array `@each` property](http://emberjs.com/api/classes/Ember.Array.html#property__each) and it seems like I should write this instead:

```coffee
questions: DS.hasMany('question')
question: (->
      @get('questions').objectAt(@get('position'))
  ).property('position', 'questions.[])
```

Would this be a useful addition if I write it up?

**Comment by michaelrkn** [comment]
Hey @nruth! Were you able to sort out the right way to do this? I'm not totally following what you're trying to do here, but I'm not sure it's the right use case for a computed property. 

I'm helping clean up open issues, so I'm going to ask @rwjblue to close this for now, but feel free to reply if you'd like to keep the conversation going.

**Comment by nruth** [comment]
I don't think this should be closed. Maybe you can get a second opinion? I'll try to clarify what I mean later.

**Comment by locks** [comment]
the `.[]` macro is indeed missing from the computed properties section of the guides as far as I could tell, but the whole section needs some rethinking so I wouldn't worry about it.
I think it can be closed as well, thanks for your input @nruth.

**Comment by michaelrkn** [comment]
@nruth I'm going to close this for now, but maybe you could open a PR. The worst thing that happens is it's decided that it doesn't need to be covered in the guides, and you can turn it into a blog post :)
