### ISSUE TITLE
Make it clearer that jsonapi.org is must-read to use ember.data rest (to create objects)

### ISSUE THREAD

**Issue by nruth** [emberjs/guides#347]
The following things confused me when trying to create a new record, but are actually specified in http://jsonapi.org/format/#crud

The trouble is, I didn't find that link for some hours. "Creating and Deleting records" and "Persisting records" don't mention it. Instead I had to look in the adapters part, out of desperation, since that's (intuitively?) the section to read when you're doing strange things, not adopting defaults.

These were the particular confusions, when creating a record. They're all basically the same question: *how, upon issuing save(), do we replace the partial record in the ember store with the api-created record*

- when/how does ember.data get an id from the back-end (active-record adapter)? Does save update the record or does it need reloading?
- does save() return any useful data, e.g. the created record, because the guide/api show no parameters for the success promise?
- why doesn't save and reload work with head :no_content ? (rails) (*no model id, don't know what to reload*)
- how do we replace our new model in the store with the one the API really saved (after transforming it, at least adding the ID, but probably doing other things too like adding associations, setting timestamps, etc); do we use reload (doesn't work, no ID present) or do we use the save promise (which specifies no params, so there's nothing to use)?

The answer is in http://jsonapi.org/format/#crud-creating

> The response MUST also include a document that contains the primary resource created.

So I assume that ember.data uses this to update the store. It would be useful if the save() docs and/or the guide examples said so.

**Comment by michaelrkn** [comment]
This is now fixed on master. @rwjblue can you please close?
