### ISSUE TITLE
Installing Ember topic -- failure when creating and test new app

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [emberjs/guides#370]
The Installing Ember topic has a section called "Testing Your Installation". If those instructions are followed then after entering the command "ember new my-app", I see the following error:

```
~/trash/ember$
ember new my-app
version: 0.2.7
0.2.7

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
ENOENT, open '/Users/datihein/trash/ember/package.json'
Error: ENOENT, open '/Users/datihein/trash/ember/package.json'
    at Error (native)
```
I suspect that the path **should have been** `/Users/datihein/trash/ember/my-app/package.json`.

If I push past that and enter the command "ember server", I get the following error.

```
~/trash/ember/my-app$
ember server
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/datihein/trash/ember/my-app/Brocfile.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I worked around that (after some Googling) by installing bower (`npm install -g bower`) and then, in the `my-app` directory, doing an `npm install` and a `bower install`.

This is on OS X 10.9.5 (Mavericks) with node 0.12.4, npm 2.11.3, ember 0.2.7, and bower 1.4.1.

Perhaps if the first defect hadn't happened, then the second would also not have happened. 

Also, nothing in the install guide mentions bower, so I"m not sure whether I needed to install bower.

**Comment by JeNeSuisPasDave** [comment]
I opened a similar issue against ember-cli. 

https://github.com/ember-cli/ember-cli/issues/4320

Maybe the only issue for the guide is to mention the need (if any) for having bower installed.

**Comment by JeNeSuisPasDave** [comment]
OK, the issues seems to be that a working ember-cli on OS X requires node and npm to have been installed without sudo. More specifically, the node and npm directories need to have permissions that allows the user to modify them.  See https://github.com/ember-cli/ember-cli/issues/4320 for details and my workaround.

I think the installation section of the guides should mention this permissions issue, especially since it is cited in the ember-cli 'common issues' section of the ember-cli guide: http://www.ember-cli.com/#commonissues

**Comment by michaelrkn** [comment]
It's true, I've seen this happen to many people. I believe the problem is that the Node installer uses sudo, and so the permissions are wrong. Maybe someone can open a PR against the installer so that it gives correct permissions for the installing user.
