### ISSUE TITLE
Should there be a global index/landing page for all guides

### ISSUE THREAD

**Issue by eccegordo** [emberjs/guides#385]
I find the experience of jumping into a guide and shifting version context a little too subtle.

For example:

Navigate to here: http://guides.emberjs.com/v1.10.0/views/built-in-views/
Click version pulldown and select v1.12.0

I would expect to go to: http://guides.emberjs.com/v1.12.0/views/built-in-views/

But you are instead redirected to the start of the guides for that version (1.12.0). This is the part that is confusing.

With an independent index/home page we could be smarter about how we route users when a version context shift happens. And perhaps use referrer info to get them to the right place, or a warning telling them that specific section of the guides no longer applies in the version they wish to select.

Besides making the missing link experience better, It strikes me that we could also do some useful things with a dynamic index/home page for all guides.

- talk about guide versioning up front and center for those whom this point is not obvious

- provide a jumping off point for each version of guides (global guides home page should not have side bar but be more like a landing page with hero element and indexy type information)

- links to what is trending/new/recent in the guides (recurring visitors should have a shortcut to the freshest content without having to pore over stuff already written.)

- provide a build page and or release cycle status page like the ember builds. Let people know what is on the train and where to go if they want to QA, beta test, or help out.

- downloadable bundles or offline guides, perhaps even dash library or PDFs or other forms of documentation should any of these be published.

- link to other external resources (docs for popular addons, Ember CLI docs, API documentation diffs, or other high quality sources of information that supplement "official" documentation.)

Just some thoughts.

**Comment by rwjblue** [comment]
SO MANY WORDS :smiley_cat: 

> But you are instead redirected to the start of the guides for that version (1.12.0). This is the part that is confusing.

This is fixed on master, and as of 1.13 guides you will be redirected to he same page you started on in the new version (assuming that exists).

**Comment by eccegordo** [comment]
:+1: I will work on my verbosity. :smile:

**Comment by michaelrkn** [comment]
@rwjblue can you close this out?

**Comment by rwjblue** [comment]
I feel like there are other points here that may or may not have been addressed. Can you double check before I close?

**Comment by michaelrkn** [comment]
Pulling the trigger too fast :) The bullet points seem like great ideas to me. @eccegordo would you be up to open a PR?

**Comment by michaelrkn** [comment]
I'm going to close this out, but PRs are welcome :)

* Guide versioning: Switching is implemented. Understanding that there are versions is not confusion I've heard elsewhere.
* Trending, downloadable version: Both sound difficult to maintain, but I'm open to a more fleshed-out suggestions.
* Build page: http://emberjs.com/builds/ is pretty easy to find, plus we are encouraging people to use ember-cli and have install instructions for that route.
* Links: There is discussion of adding some more to http://emberjs.com/community/, as well as sprinkling them throughout the Guides.
