### ISSUE TITLE
Examples at jsbin.com don't work

### ISSUE THREAD

**Issue by iharsuvorau** [emberjs/guides#386]
Examples in the topic [Routing → Query Params](http://guides.emberjs.com/v1.12.0/routing/query-params/) at the bottom of the page don't work. The error in the console:

    "ReferenceError: Ember is not defined at http://null.jsbin.com/runner:1:1476

**Comment by vire** [comment]
because currently `http://builds.emberjs.com/ember-latest.js` doesn't work.

You can include there ember version you need from a cdn and re-run the jsbin.

**Comment by iharsuvorau** [comment]
Yes, thank you. Now it works. I had to include `http://builds.emberjs.com/release/ember-template-compiler.js` too.

**Comment by michaelrkn** [comment]
Dup of #277. @rwjblue can you please close?
