### ISSUE TITLE
Guides have old helper syntax documentation. 

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/guides#400]
The guide here: http://guides.emberjs.com/v1.12.0/templates/writing-helpers/

is still using the outdated `Ember.Handlebars` syntax that doesn't match ember-cli's `Ember.HTMLBars`

**Comment by rwjblue** [comment]
Yep, I agree, this definitely needs some work for 1.13 syntax.

**Comment by michaelrkn** [comment]
#407 is working on this.
