### ISSUE TITLE
No mention of where to put inject for services

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/guides#401]
We used to use `App` globally (including templates, I know shame on us) when upgrading we had to switch to a service as outline in the code snippet below

```javascript
Ember.Application.initializer({
  name: "registerDependancies",
  initialize: function( registry, application ) {
    application.register( 'service:GlobalApp', App.GlobalApp );
  }
});
 
Ember.Application.initializer({
  name: "injectDependancies",
  after: "registerDependancies",
  initialize: function( registry, application ) {
    application.inject( 'controller', 'GlobalApp', 'service:GlobalApp' );
    application.inject( 'component', 'GlobalApp', 'service:GlobalApp' );
    application.inject( 'view', 'GlobalApp', 'service:GlobalApp' );
  }
});
 
var App = Ember.Application.create({});
 
App.GlobalApp = Ember.Service.extend({
  App: Ember.computed('App', function(){ return App; })
});
```

However we get the deprecation warnings as noted [here](http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers) and there is no mention as to where to move the application.inject to.

I'm sorry if this isn't the right repo (where the deprecations are) but I think it is worthwhile including in the guides

**Comment by mixonic** [comment]
The deprecation guide should address this. It is maintained in the [website](https://github.com/emberjs/website) repo. Current docs on the change to initializers are [here](http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers).

I agree the deprecation guide could be improved. Please consider opening an issue or PR on the website repo though, the guides should not be addressing how to migrate deprecated code.
