### ISSUE TITLE
1.13 Guides - missing content

### ISSUE THREAD

**Issue by trek** [emberjs/guides#408]
1.13 Guides are unpublished because many new features didn't get any documentation love in the 1.13/2.0 deadline rush:

We're missing (list not exhaustive)

Release. These need to be written ASAP by or with the involvement of the feature authors:

- [ ] Closure Actions (@mixonic)
- [x] Helper API (@mixonic and @rwjblue)
- [ ] Component Block (@mmun and @rwjblue)

Beta. These features will be voted NO-GO for 2.0 unless there is an accompanying guides PR:

- [x] `{{each-in}}` helper (@tomdale)
- [x] `{{get}}` helper (@jmurphyau and @mmun)

Canary. These features will not be enabled in a beta until there is an accompanying guides PR:

- [ ] Query params migrated to Routes (@trek)

**Comment by tomdale** [comment]
> Component Lifecycle Hooks

I don't think these block release of the guides. We are working on angle bracket components where these are critical. All of the old component APIs continue to work, and we can hold off on documenting the new hooks until angle bracket components land (where they become important).

**Comment by tomdale** [comment]
I have a WIP updated helper guide here: https://github.com/emberjs/guides/pull/407

I will finish it up as soon as possible, but if someone wants to grab it and update in the meantime, please be my guest. @locks @michaelrkn?

**Comment by trek** [comment]
>  All of the old component APIs continue to work,

All of 1.12 continues to work :stuck_out_tongue: 

The question is "should people use these hooks in 1.13? If yes, they're blocking publication. If not, should they have remained on beta?

**Comment by tomdale** [comment]
> If not, should they have remained on beta?

Probably, but we thought angle brackets were going to land.

**Comment by rwjblue** [comment]
`{{each-in}}` guides added in https://github.com/emberjs/guides/pull/357 and revised in https://github.com/emberjs/guides/pull/358.

**Comment by michaelrkn** [comment]
@tomdale I won't have time until Friday at the earliest

**Comment by tomdale** [comment]
https://github.com/emberjs/guides/pull/407 contains an updated Handlebars helper guide, please review at your earliest convenience.

**Comment by locks** [comment]
People have been raising questions about what to do with routable `Views`, do we have a story for that?

**Comment by mixonic** [comment]
@locks that seems like material for the deprecation guide, not the guides.

To summarize, there is only a single use-case unsupported without views: Adding a class to the application view's div. All other cases can be handled by a component or element at the root of a view's template. The one unsupported use-case will unfortunately remain unsupported until routable components.

**Comment by locks** [comment]
@mixonic I thought the deprecations guide were in this repo as well :X

The issue raised was exactly that, adding a class to a routable `View` without introducing an extra `div`.

**Comment by mixonic** [comment]
Yeah, there a bazillion things that need improved deprecation content though. I do not think adding them to this list of undocumented **features** is ideal.

**Comment by locks** [comment]
:+1:

**Comment by jmurphyau** [comment]
I should find some time over there weekend to complete the {{get}} helper one

**Comment by tomdale** [comment]
Per today's core team call, I've removed documenting the new component lifecycle hooks. We will incorporate that documentation into the guides for angle bracket components.

**Comment by tomdale** [comment]
@jmurphyau What's the status of `{{get}}` docs?

**Comment by jmurphyau** [comment]
I'm going to try get this done in the next few hours.. Sorry about that

**Comment by jmurphyau** [comment]
PR #438 adds the {{get}} helper to the guides. I thought after the {{input}} helpers was the most appropriate place to demonstrate using the two together..

I had trouble getting `bundle` to work (I'm running an El Capitan beta) and couldn't figure it out - so I ended up doing the PR blindly - which I'm not completely happy with but it gets it done quicker.. Hopefully there's no technical issues with it

**Comment by knownasilya** [comment]
I'd love to help with the component block guide updates, ping @mmun @rwjblue
