### ISSUE TITLE
store.push(type, data) is deprecated 

### ISSUE THREAD

**Issue by nicolas-dular** [emberjs/guides#426]
Since I got `DEPRECATION: store.push(type, data) has been deprecated. Please provide a JSON-API document object as the first and only argument to store.push.` but couldn't find anything in the [guides](http://guides.emberjs.com/v1.12.0/models/pushing-records-into-the-store/) it would be great to explain that you now need to `normalize` the Object if it's not JSON-API Standard.

A good explaination about this topic was given here: https://github.com/emberjs/data/issues/3402

**Comment by michaelrkn** [comment]
@locks are you going to take the lead on the models/ember data stuff? if so, maybe you can open an issue that outlines the work that needs to be done (including this), and ask people with ember data issues/suggestions to comment on that one issue so we get everything in a centralized place.

**Comment by michaelrkn** [comment]
Closing in favor of #449.
