### ISSUE TITLE
Add guide for form handling.

### ISSUE THREAD

**Issue by maxcal** [emberjs/guides#437]
I'm just learning Ember.js and I have trying to do a just a plain sign up form. While I have been able to find tutorials like this one on [Smashing Magazine](http://www.smashingmagazine.com/2013/11/07/an-in-depth-introduction-to-ember-js/#create_a_user) most are badly out of date and I'm quite confused about how to acheive this with a routing component instead of a controller. 

It would be pretty nice to have a somewhat holistic guide (but still not a tutorial) which shows how to bind a handler to a form and how it links up with a model, route and component. And more important the accepted best practice.

 This would be a complement to the [input helpers guide](http://guides.emberjs.com/v1.12.0/templates/input-helpers/) which is decent as API documentation but does not really show how the model binding works or how the parts fit together.

**Comment by michaelrkn** [comment]
Agreed - the guides are currently sorely lacking an explanation of how to do this. There used to be a tutorial at the beginning of the guide that showed how to build a simple app from start to finish, and covered this kind of content. We're working on making a new tutorial, and this will definitely be one of the topics covered!
