### ISSUE TITLE
Relative API-doc links are broken

### ISSUE THREAD

**Issue by kimroen** [emberjs/guides#44]
For instace, the "Event Names" link at the bottom of this page doesn't work:

http://guides.emberjs.com/v1.10.0/views/handling-events/

**Comment by rwjblue** [comment]
Yes, links to `api` docs are all going to be wrong at this point because `/api/*` is not present here.

We could:

* update them to be full paths
* change divshot config to proxy to `emberjs.com/api` for now, and then change that once `api.emberjs.com` is a thing
* other smart things?

@trek - What is your preferred solution?

**Comment by trek** [comment]
I think we should change them all to full links. When we move to `api.emberjs.com` they will redirect, so we won't need to come back and fix them. @kimroen want to audit and fix all of them?

**Comment by kimroen** [comment]
@trek It's on my todo-list.

**Comment by trek** [comment]
@kimroen any ETA on this? If not, it's blocking and I'd like to hand it someone else who can get to it ASAP.

**Comment by trek** [comment]
Possible @michaelrkn/@erezny who both mentioned at EmberConf they wanted to help

**Comment by kimroen** [comment]
I won't get to this today, I was thinking this weekend. Sorry about that.

**Comment by johnotander** [comment]
@trek I can go through them all today and change them to full links.

**Comment by jagthedrummer** [comment]
@johnotander Just saw your comment, but already have changes made locally here. Can PR immediately if you're not already in progress.

**Comment by johnotander** [comment]
Go ahead and PR if you've already made the changes : )

All I've done is forked and bundle installed, haven't begun making changes. So, I'll be ready to help out with the next thing that pops up.

**Comment by kimroen** [comment]
Great work!
