### ISSUE TITLE
Missing language only raises exception when building

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#441]
If you don't put a language by your code fences, nothing bad happens in development (`middleman server`). But when you try to build (`middleman build`), you get the exception "Code blocks must be fenced with proper language designated. If you don't know what language to use, specify ```text```". 

That exception should be raised in every environment, so we don't only catch it when trying to deploy.

**Comment by acorncom** [comment]
@michaelrkn Any further details on how to replicate this issue?  I've just tried the following and both seem to be working:

`bundle exec middleman server`

`bundle exec middleman build`

I'm not seeing the exception you mention ...

**Comment by michaelrkn** [comment]
Yeah, just add this code to a file:

```
hi, i'm a code sample that doesn't have a language or filename after the triple backtick code fence.
```

Nothing bad will happen with `middleman s`, but when you try to build, you will get an error.

**Comment by acorncom** [comment]
> If you don't put a language by your code fences, nothing bad happens in development (middleman server)

Just tested this and this isn't exactly accurate.  If you don't have a language specified for your code blocks, if you visit the offending page, you will get an error at the top of the page:

![screen shot 2015-08-25 at 10 46 52 am](https://cloud.githubusercontent.com/assets/802505/9473172/9f1b7a8c-4b16-11e5-9013-48c474ec05f3.png)

However, if you don't navigate to the page, you'll get the error when a `middleman build` is run.

Based on what I'm seeing of how Middleman is setup, I think we should close this issue, as I don't think there is a way around it in code ...

@locks

**Comment by rwjblue** [comment]
Since we have Travis setup to run `bundle exec middleman build --verbose`, we can basically ensure that PR's don't introduce issues for us here (as long as we wait until they are green).

**Comment by michaelrkn** [comment]
Right you are. I opened this before we had Travis and the build failed when we tried to deploy because somebody didn't put the language in. Don't know how they missed the exception, but we shouldn't have this problem again. Thanks for figuring this out, @acorncom!
