### ISSUE TITLE
Add a guide for Services

### ISSUE THREAD

**Issue by mattw59** [emberjs/guides#442]
This should include roughly the following: 
- [ ] What is a service
- [ ] When to use a service, and when not to use one
- [ ] Discuss factories
- [ ] Using initializers with services
- [ ] Using Ember.inject.service()
- [ ] Common types of services (session, user, persistent state rather than temporary state)
- [ ] Fold in existing guide on dependency injection: http://guides.emberjs.com/v1.12.0/understanding-ember/dependency-injection-and-service-lookup/
- [ ] Caution: don't overuse services, this can lead to monoliths of brittle and interdependent code

**Comment by pixelhandler** [comment]
@mattw59 how about adding "How to inject a service into another object", here is an example I've used: https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/tests/dummy/app/models/post.js#L7 sometimes its great to use `application.inject()` with an initializer https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/tests/dummy/app/initializers/post.js#L20 and other times it works to use `Ember.inject.service()` when defining a prototype.

**Comment by mattw59** [comment]
@pixelhandler Sounds good, added a task for this.

**Comment by michaelrkn** [comment]
@mattw59 - We have a goal of getting the 2.0 guides together by Monday, August 3. Do you think you'll be able to have this section ready by then?

**Comment by mattw59** [comment]
@michaelrkn Yes, I'll be sure that something is ready for the team to review by then, preferably before since I'll be on a family vacation Aug 2-4.

**Comment by michaelrkn** [comment]
Awesome!

**Comment by Poorchop** [comment]
I think utils should be mentioned as well. I know that services and utils are two different things, but there are instances where they can both provide a similar means to an end. Utils should probably get their own section so as to avoid confusion, but they could be a subsection of services at the very least.

**Comment by elbeezy** [comment]
@poorchop I disagree that utils should be included in the services section, even in the interim. They belong with helpers IMO as general tooling.

**Comment by Poorchop** [comment]
Yeah that makes sense. I just want to ensure that some mention is made of them because I think that they are a pretty important piece of the framework.

**Comment by locks** [comment]
Isn't a "util" just a module?

**Comment by MiguelMadero** [comment]
@locks I think there's some confusion about when to simply use a module or use services. This is something I've had to clarify multiple times. I think it's important to clarify in the "When not to use services" section that a good alternative is often a module.

@Poorchop aren't `helpers` for registering Handlebars helpers? We normally have them on  `utils` folder and simply import them as any other module, but moved away from using the `helpers` folder to avoid this confusion.

**Comment by Poorchop** [comment]
What ever one may choose to call them, it's important to mention that plain JavaScript modules can be used in Ember. When I was going through the guides, I got the impression that all logic needed to be squeezed into routes, controllers, and views, and I didn't know where to put arbitrary functions.

I just refer to them as utils because that's what Ember CLI does. I also agree that modules should be discussed a bit in the "When not to use services" section.
