### ISSUE TITLE
Link to ember-cli version of TodoMVC?

### ISSUE THREAD

**Issue by chrislopresto** [emberjs/guides#45]
I was reviewing some things the other night and couldn't find a repository with a current ember-cli version of the TodoMVC app. So I put this together: [https://github.com/chrislopresto/todomvc-embercli](https://github.com/chrislopresto/todomvc-embercli)

Each commit corresponds to a single step in the v1.10 [Getting Started](http://guides.emberjs.com/v1.10.0/getting-started/) guide. The [README](https://github.com/chrislopresto/todomvc-embercli/blob/master/README.md) lists each step along with any corresponding [ember-cli generator](http://www.ember-cli.com/#generators-and-blueprints) and [addon](http://www.emberaddons.com/) install commands.

As we shift all docs and demos to ember-cli...

- Is this semi-useful to folks in its current state? 
- Should we link to it from the guides?
- Would anyone like anything added or changed?

**Comment by trek** [comment]
Thanks! This is awesome however: there's work a new Getting Started Guide that better reflects Ember's strengths. We won't be going with TodoMVC, so the plan for 1.11 is to remove the GSG and link to some of the great community resources until a new guide is completed.

**Comment by chrislopresto** [comment]
:+1:
