### ISSUE TITLE
Encourage decorator-style Ember.computed/Ember.observer

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#455]
There seems to be general consensus that we should encourage people to use decorator-style methods instead of prototype extensions, except in the case of Array extensions. We should change all places in the guides that use `.property` to `Ember.computed`, and `.observes` to `Ember.observer`. For example, this:

```javascript
var president = Ember.Object.create({
  firstName: "Barack",
  lastName: "Obama",

  fullName: function() {
    return this.get('firstName') + ' ' + this.get('lastName');
  }).property()
});
```

becomes:

```javascript
var president = Ember.Object.create({
  firstName: "Barack",
  lastName: "Obama",

  fullName: Ember.computed(function() {
    return this.get('firstName') + ' ' + this.get('lastName');
  })
});
```

**Comment by trek** [comment]
:+1:
