### ISSUE TITLE
Update introduction of Components section

### ISSUE THREAD

**Issue by wvteijlingen** [emberjs/guides#460]
At the moment the Components introduction really doesn't tell you anything useful imho. It talks a bit about Web Components, and then links to the long technical 'Custom Elements' spec of the W3C.

I think this can be improved by adding a more sane explanation including the rationale behind components, what they offer, and when to use them.

**Comment by michaelrkn** [comment]
Totally agreed! Components are going to need a big re-working for routable components in 2.1. I'm sure there will be some re-writing of the intro then, but if you'd like to suggest an update in the meantime, feel free to open a PR.
