### ISSUE TITLE
Improve Stateful Helpers explanation

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#464]
At https://github.com/emberjs/guides/blob/master/source/templates/writing-helpers.md#stateful-helpers, the explanation of stateful helpers simply translates a stateless helper into a stateful helper. We should add an explanation and examples of when you might want to use a stateful vs stateless helper. 

I remember somebody on Slack saying that translations was a good use case for stateful helpers, in case that helps.

**Comment by mmun** [comment]
Calling them stateful helpers seems _very_ bad. I don't want to promote state on helpers. The primary purpose has nothing to do with state -- they're primary use case is for hooking up to services. If anything, they should be called service helpers.

**Comment by thriqon** [comment]
The paragraph below ("Adding Services") introduces just that... I can go ahead and merge them together, promoting their primary use case. I think a single paragraph will help people understand the reasoning better and at the same time decrease the chance of developers to misuse them.

**Comment by michaelrkn** [comment]
@thriqon Sorry for the delayed reply - can you do that? Thanks!!
