### ISSUE TITLE
Improve run loop documentation

### ISSUE THREAD

**Issue by locks** [emberjs/guides#472]
As discussed in #431, the run loop documentation is currently confusing and inadequate. I'm opening this issue to serve as meta so we can discuss the way forward.

- [x] Discuss where run loop documentation should go
  - [ ] Improve run loop guides section
  - [ ] Improve API documentation
- [ ] Link to https://github.com/ebryn/backburner.js/

@michaelrkn @ksin

**Comment by michaelrkn** [comment]
@locks can you outline in more detail what needs to be done here?

**Comment by michaelrkn** [comment]
I've opened #679 to add appropriate links to more info. I'm going to close this out for now since it feels like an extremely low priority, but feel free to re-open with more detail about what needs to be done if you feel it's appropriate.

**Comment by locks** [comment]
The only thing left is the API documentation methinks, something like https://github.com/emberjs/ember.js/pull/12211

**Comment by rwjblue** [comment]
@locks the Ember public API surface for Backburner is *much* reduced from Backburner's own public API.  We should ensure that all the `Ember.run` and `Ember.run.*` family of methods are fully documented (including return values, params, callback args, etc).
