### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by montaniasystemab** [emberjs/guides#477]
It seems that search is broken when using guides.emberjs.com as domain, Chrome inspector logs: 

````
swiftype_nocode-5190fccc6a3c7dcff96a2c6aad0e53dd.js:18 
Uncaught TypeError: Cannot read property 'query' of undefined
````

Tested URLs: http://guides.emberjs.com/v1.13.0/components/sending-actions-from-components-to-your-application/ & http://guides.emberjs.com/v1.13.0/
UA: Chrome 44 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36

**Comment by michaelrkn** [comment]
This should be fixed when we re-release 1.13 shortly.
