### ISSUE TITLE
Remove JSBins

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#483]
Rationales: They can't be PR'd, there is no indication if they get broken, it's not obvious when they are out of date, and they are either owned by somebody who might be hard to track down or need a shared login that doesn't currently exist. 

We need to go through the Guides and remove all JSBins, replacing with code examples where appropriate.

# Checklist

- [x] https://github.com/emberjs/guides/blob/master/source/components/passing-properties-to-a-component.md - https://github.com/emberjs/guides/pull/489
- [x] https://github.com/emberjs/guides/blob/master/source/components/wrapping-content-in-a-component.md - https://github.com/emberjs/guides/pull/490
- [x] https://github.com/emberjs/guides/blob/master/source/components/handling-user-interaction-with-actions.md - https://github.com/emberjs/guides/pull/491
- [x] https://github.com/emberjs/guides/blob/master/source/components/index.md - https://github.com/emberjs/guides/pull/492
- [x] https://github.com/emberjs/guides/blob/master/source/components/customizing-a-components-element.md - https://github.com/emberjs/guides/pull/488
- [x] https://github.com/emberjs/guides/blob/master/source/components/sending-actions-from-components-to-your-application.md - https://github.com/emberjs/guides/pull/493
- [x] https://github.com/emberjs/guides/blob/master/source/routing/specifying-a-routes-model.md - https://github.com/emberjs/guides/pull/495
- [x] https://github.com/emberjs/guides/blob/master/source/components/defining-a-component.md - https://github.com/emberjs/guides/pull/494

# More checklist

* [ ] There is a script in the layout file that has sth to do with jsbins, probably can be removed once this gets merged – didn't see any difference locally after removing it. [link](https://github.com/emberjs/guides/blob/6d1ba3eefa223fa3ba056f1c219b09cc0cdceba7/source/layout.erb#L114)
* [x] There is a link to a broken JSBin here in the guide for loading and error substates: [link](https://github.com/emberjs/guides/blob/4ddd8393466609b45e40492e7dc0b11c75bd400e/source/routing/loading-and-error-substates.md#L240) (https://github.com/emberjs/guides/pull/510)
* [ ] There's also a long list of JSBin examples in the guide for query params: [link](https://github.com/emberjs/guides/blob/dcf3c6ca0e139d9b68338dae3d862bc214351199/source/routing/query-params.md#L328)
* [ ] The css files also mention jsbin for some reason (I don't know the story) [link](https://github.com/emberjs/guides/blob/2a089a792fe9f1634b62d2365bb969407bd4e1d0/source/stylesheets/guides.css.scss#L37)

**Comment by trek** [comment]
:+1: better to have them gone than wrong.

**Comment by locks** [comment]
For anyone interested in contributing: please break up your PRs by section, otherwise it gets hard to review

**Comment by mamut** [comment]
Did a quick search of the repo, looks like there are eight sections with jsbins: https://github.com/emberjs/guides/search?q=jsbin-embed&type=Code&utf8=%E2%9C%93

* https://github.com/emberjs/guides/blob/master/source/components/passing-properties-to-a-component.md
* https://github.com/emberjs/guides/blob/master/source/components/wrapping-content-in-a-component.md
* https://github.com/emberjs/guides/blob/master/source/components/handling-user-interaction-with-actions.md
* https://github.com/emberjs/guides/blob/master/source/components/index.md
* https://github.com/emberjs/guides/blob/master/source/components/customizing-a-components-element.md
* https://github.com/emberjs/guides/blob/master/source/components/sending-actions-from-components-to-your-application.md
* https://github.com/emberjs/guides/blob/master/source/routing/specifying-a-routes-model.md
* https://github.com/emberjs/guides/blob/master/source/components/defining-a-component.md

**Comment by mamut** [comment]
I'll start from the top

**Comment by mamut** [comment]
* [ ] There is a script in the layout file that has sth to do with jsbins, probably can be removed once this gets merged – didn't see any difference locally after removing it. [link](https://github.com/emberjs/guides/blob/6d1ba3eefa223fa3ba056f1c219b09cc0cdceba7/source/layout.erb#L114)
* [ ] There is a link to a broken JSBin here in the guide for loading and error substates: [link](https://github.com/emberjs/guides/blob/4ddd8393466609b45e40492e7dc0b11c75bd400e/source/routing/loading-and-error-substates.md#L240)
* [ ] There's also a long list of JSBin examples in the guide for query params: [link](https://github.com/emberjs/guides/blob/dcf3c6ca0e139d9b68338dae3d862bc214351199/source/routing/query-params.md#L328)
* [ ] The css files also mention jsbin for some reason (I don't know the story) [link](https://github.com/emberjs/guides/blob/2a089a792fe9f1634b62d2365bb969407bd4e1d0/source/stylesheets/guides.css.scss#L37)

**Comment by mamut** [comment]
This is it from me for the time being, might find some more time to help tomorrow after work, no promises though, cheers!

**Comment by acorncom** [comment]
Checked the top checklist.  My pull request above fixes one of the two, the second checkbox (for `components/sending-actions-from-components-to-your-application.md`) is inaccurate (the work has already been done).

**Comment by locks** [comment]
@acorncom I merged but didn't update

**Comment by acorncom** [comment]
Think I need to bow out as well, will try to check back in over the next week+ to help out more.  Appreciate all your hard work guys, the docs are noticeably easier to use this week compared to last.

**Comment by locks** [comment]
@mamut stole your checklist to the OP so we get number tracking in the issue list

**Comment by acorncom** [comment]
May be worth breaking out the query-params JSBINs into separate items, there are 13 items there, each of which may take some time:

- Search queries 
- Sort: client-side, no refiring of model hook
- Sort: server-side, refire model hook
- Pagination + Sorting
- Boolean values. False value removes QP from URL
- Global query params on app route
- Opt-in to full transition via refresh()
- update query params by changing controller QP property
- update query params with replaceState by changing controller QP property
- w/ {{partial}} helper for easy tabbing
- link-to with no route name, only QP change
- Complex: serializing textarea content into URL (and subexpressions))
- Arrays
