### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by villeneuve-michael** [emberjs/guides#485]
Hey guys,

For some reason the section of 1.1.13

> Components / Defining a components

Has a redirect loop.

EDIT: it looks like the page adds a / at the end of the URL then removes it then adds it...

**Comment by srk9** [comment]
This is true, came here to say the same.

**Comment by lmatiolis** [comment]
+1

**Comment by michaelrkn** [comment]
Thanks for reporting. I'm putting in a support ticket with our website host.

**Comment by michaelrkn** [comment]
Support has asked me to gather browser and OS information - can any of you report?

**Comment by rwjblue** [comment]
Chrome Version 44.0.2403.107 (64-bit)
OSX 10.9.5

**Comment by srk9** [comment]
Chrome Version 43.0.2357.134 (64-bit)
Ubuntu 15.04

**Comment by lmatiolis** [comment]
Chrome Version 42.0.2311.90 (64-bit)
Ubuntu 12.04

**Comment by rwjblue** [comment]
I believe this was fixed by the DivShot folks.  http://guides.emberjs.com/v1.13.0/components/defining-a-component/ is working now without a redirect loop, closing....

**Comment by srk9** [comment]
Confirmed. The page is now working, thank you!

On Thu, Jul 30, 2015 at 2:50 PM, Robert Jackson <notifications@github.com>
wrote:

> Closed #485 <https://github.com/emberjs/guides/issues/485>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/guides/issues/485#event-369783662>.
>



-- 
Warmest Regards,

Dustin M. Gelegonya
Business Technology Consultant
484-903-8070 | *dustin@srk9.com <dustin@srk9.com>*
