### ISSUE TITLE
Remove uses of `render` and `partial`

### ISSUE THREAD

**Issue by rwjblue** [emberjs/guides#498]
http://guides.emberjs.com/v1.13.0/templates/rendering-with-helpers/

Both `{{render}}` and `{{partial}}` should be avoided: they are both likely to be deprecated sometime in the 2.x cycle, and we should not recommend folks to use them in 2.0.0...

- [ ] Remove `/templates/rendering-with-helpers/`
- [ ] Audit for any usages of `{{render}}`
- [ ] Audit for any usages of `{{partial}}`

**Comment by trek** [comment]
In addition to that page, the PR should audit the remaining guides for uses of `render` and `partial`, removing or replacing with component use where appropriate.
