### ISSUE TITLE
Documentation for isEvery is not clear 

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/guides#505]
http://emberjs.com/api/classes/Ember.Enumerable.html#method_isEvery

Returns true if the passed property resolves to the value of the second argument for all items in the enumerable. This method is often simpler/faster than using a callback.
Expectation (based on definition) for [].isEvery('name', 'olivier') was false. 
Result is true.

While the isEvery method follows the implementation of javascript .every iterator, the definition in Ember doc could be a bit better.

**Comment by michaelrkn** [comment]
Can you be more concrete about how this could be better? Also, this is the issues for the guides, and you are looking at an API doc - I believe you should open an issue on https://github.com/emberjs/ember.js instead. Thanks!

**Comment by olivierlesnicki** [comment]
@michaelrkn I did https://github.com/emberjs/ember.js/issues/11916#issuecomment-126502686

it says it returns true if the property resolves to the value of the second argument for ALL items.
This is not what it does. A good example is running it against an empty array. The property never resolves to the value of the second argument (since there is no item), yet true is returned.

**Comment by olivierlesnicki** [comment]
Also, for performance reaosns, the .isEvery method actually doesn't conduct a "positive" check but a "negative" one. It checks that it can't find one item for which the property doesn't resolve to the second argument.

**Comment by jhilden** [comment]
We were also bitten by this issue :(

Looking deeper, the Ember behavior seems to be in accordance with the underlying functionality in Javscript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every):

> every acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns true. (It is vacuously true that all elements of the empty set satisfy any given condition.)

Even if the behavior might be "correct" (in some hard to understand way), I strongly think that it is semantically counter-intuitive and therefore should be explicitly mentioned in the API docs for `isEvery` and `every`.  Something like:

----

**Gotcha**:  Beware that this method will always return `true` for an empty enumberable (in accordance to the implementation of `every` in [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)), which might often not be what you are looking for.

---

**Comment by acorncom** [comment]
@jhilden this isn't something we would document in guides (as it's too specific) but might be worth putting into API guides.  Would you open an issue on for this repo: https://github.com/emberjs/ember.js (prefix the title with [DOC]) and we can see what the core team thinks?  Thanks!

**Comment by alechirsch** [comment]
+1 for putting this in the API guide, we just got hit by this as well
