### ISSUE TITLE
Add warning to page if it is an old version

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#506]
This should be done with JavaScript. #114 is a PR that starts this work but has stalled out. It would be great if somebody could pick up where @wagenet left off (or if @wagenet wants to pick that up, that would be great too!).

**Comment by HeroicEric** [comment]
for reference https://github.com/emberjs/guides/pull/114

**Comment by locks** [comment]
https://github.com/emberjs/guides/pull/114/files#diff-fecc04b4c692688a162cc19a0fd54b0aR2 wouldn't this not work in older versions of the guides?

**Comment by wagenet** [comment]
@locks is there anything preventing us from redeploying the old versions with the necessary fixes?

**Comment by rwjblue** [comment]
@wagenet - its kind of a PITA to do

**Comment by wagenet** [comment]
@rwjblue understood. I wasn't proposing that it be done regularly. However, for this to be useful, we'd have to deploy it on old versions too. Hopefully, it would be a one time thing.

**Comment by wagenet** [comment]
The big concern is that a lot of Google results still point to old version of the guides.

**Comment by michaelrkn** [comment]
Why would we deploy guides for beta releases anyways? So far, we've struggled to get docs out on time for stable releases - I can't imagine we're going to have anything ready for betas.

**Comment by eccegordo** [comment]
@michaelrkn I would think that going forward in ember 2.0 it is absolutely critical to publish beta guides along with the betas. Force the lockstep of releases and docs. People should be testing the beta guides content just as much as they are testing the beta features.

Just need to figure out a way to brand the guides as beta content and subject to change until release is final. Once something is out of beta and released only then does it get locked down and become immutable.

Rails has their "edge" guides. I think a similar strategy is warranted here.

**Comment by michaelrkn** [comment]
What would the release schedule be for the beta guides? Keep in mind that Rails gets a new release every several months; we get a new release every 6-8 weeks or so.

**Comment by eccegordo** [comment]
I would think that guides would be mostly stable and that publishing process would be integrated with featured flags somehow. Maybe there is just a canary version of guides that are continually published as the beta progresses. As features land the corresponding guides changes need to be written/updated/removed.

When the go/no go decisions are made for features, similar decisions are made about guides content.

It would definitely mean that there would have to be a change around the publishing process.

I think it would just be something like
beta-guides.emberjs.com 
and that they wouldn't necessarily be versioned beta1, beta2, etc. But the understanding would be that these guides are continually published as the beta progresses.

People landing features probably need to own periodic review of guides content to make sure their feature is sufficiently addressed in guides.

**Comment by eccegordo** [comment]
Maybe I have canary and beta backwards. So perhaps it is canary code / canary guides that both just correspond to master branches and that the beta cycle is the period to review and lock down things.

Presumably most of the hard work would be done day to day as canary is progressing. And by the time beta hits guides are (hopefully) mostly stable for that version/release and the beta cycle is the opportunity for final polishing of guides before release.

**Comment by michaelrkn** [comment]
That all sounds like great ideas, but it will require some big changes to the current publishing process (see https://github.com/emberjs/guides.emberjs.com). Given how short Ember's release cycles are and that the content authoring process is so discrete from the feature process (which could be argued is a problem), I'm not sure it's worth the effort to build a system around that. But I'm personally open to the idea! I think we'd need a lot more detail about both the technical and human side of things. You're welcome to champion the effort, but I'm skeptical you'll find much traction, especially now when we're scrambling to catch up the Guides content with what's currently released, not to mention improve the quality of what's currently written. If I were you, I'd hang onto the idea until maybe another couple releases when things have settled out a bit more. (The 2.0 release is about getting the structure of the Guides sane and about actually having content for everything that's released, I think 2.1 will be about improving the quality of the content, and so you might want to float this around 2.2.)

**Comment by eccegordo** [comment]
Gotcha. This is mostly refinement and process after guides are relatively stable. So 2.2 timeframe makes sense. Master is master branch so anybody can download and run via middle man. Perhaps on technical terms there just needs to be a continual nightly dump of guides content somewhere that is stripped of the normal publishing apparatus and normal formatting but still readable (and diffable).

My main point is you want people landing feature to be cognizant of developments in the guides so that efforts are nicely sync'd up when release time come around.

**Comment by michaelrkn** [comment]
Agreed - that's been a major problem with the Guides recently, as features have been released without documentation.

**Comment by locks** [comment]
If we decide to do beta docs, I vote they're not searchable.
