### ISSUE TITLE
Update Guides with closure actions

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#507]
@mixonic is on this!

**Comment by locks** [comment]
Doesn't "Composing components" address closure actions as well?

**Comment by michaelrkn** [comment]
Peeps on the docs call said this is something that should be updated throughout the guides... I have no idea what closure actions even are :)

**Comment by locks** [comment]
:+1:

**Comment by michaelrkn** [comment]
@mixonic any progress here?

**Comment by mixonic** [comment]
Yup. Still plowing through the sections leading up to it to get the high-level things in place. Nearly there.

**Comment by michaelrkn** [comment]
Sweet!
