### ISSUE TITLE
The way the guides suggest you iterate over the controller together with ember-cli disabling ArrayControllers is really confusing for beginners.

### ISSUE THREAD

**Issue by kitsunde** [emberjs/guides#527]
I've been bit by this at least once before, and a beginner couldn't understand why the Ember guide code wouldn't work:
https://stackoverflow.com/questions/31778253/why-does-this-example-from-the-ember-js-guides-not-work/31778883#31778883

Can't we replace all instances of

```handlebars
{{#each controller as |foo|}}
{{/each}}
```

with

```handlebars
{{#each model as |foo|}}
{{/each}}
```

**Comment by michaelrkn** [comment]
Thanks for filing this issue! This is actually already done on master, perhaps after the last release was cut.
