### ISSUE TITLE
Page jump on mouse hover next and previous link of guide

### ISSUE THREAD

**Issue by ritesh-pandey** [emberjs/guides#533]
![screenshot from 2015-08-03 22 02 35](https://cloud.githubusercontent.com/assets/1433681/9042291/5ed52294-3a2b-11e5-905c-40ad24ee3877.png)

Hover over `Core concepts` (the next article in guide link in attached screenshot)
You will see that the page jumps a bit.
It happens because of `border-bottom` being added on element `hover`

**Comment by locks** [comment]
Closed by #534. Thank you!
