### ISSUE TITLE
Add location type to the router in "Simple Routes" guide

### ISSUE THREAD

**Issue by frank06** [emberjs/guides#537]
Someone unfamiliar with Ember was perusing the guide: http://guides.emberjs.com/v1.13.0/getting-started/naming-conventions/#toc_simple-routes

Following the examples, [he was frustrated](https://stackoverflow.com/questions/31778253/why-does-this-example-from-the-ember-js-guides-not-work/31795284) as he couldn't see any data in his own sample app when he navigated to `http://localhost:4200/favorites`.

**It must be made clear that the router with no `location` requires prepending the `#`** as in `http://localhost:4200/#/favorites`.

Alternatively, configure the router to `auto` for the history API.

```js
var Router = Ember.Router.extend({
  location: 'auto'
});

Router.map(function(){
  this.route('favorites');
});

export default Router;
```

**Comment by locks** [comment]
It does in http://guides.emberjs.com/v1.13.0/routing/specifying-the-location-api/ :\
Think a link pointing there would suffice? "For more info on routes, check link" sort of thing.

**Comment by frank06** [comment]
Makes sense!  That one link could prevent newbies seeing a blank page when trying it out

**Comment by frank06** [comment]
But let theme know in the "simple routes" section to navigate to `http://localhost:4200/#/favorites` if following the guide. And then the link to the location api docs

**Comment by garethbjohnson** [comment]
@locks As the newbie who ran into the problem, I can tell you that such a link would probably not have helped much. It would help to precede the URLs with `/#` in the examples in that section, as @frank06 suggests, or to have an info box somewhere before this example to tell beginners to prepend it to all URLs by default.

**Comment by locks** [comment]
@garethbjohnson Hm, the guides are written with a focus on the happy path, which in this situation would be `location: auto` as generated by default by ember-cli. This is to say I prefer @frank06's suggestion of adding the location type.

**Comment by locks** [comment]
I just realized something, `naming-conventions.md` is gone from master. ^_^;  https://github.com/emberjs/guides/pull/508
I will fix it there instead!

**Comment by frank06** [comment]
@locks cool.

I don't even know why `location: auto` is not the default

**Comment by locks** [comment]
@frank06 quite possibly legacy reasons. I think when router.js popped up support went back to IE6.

**Comment by garethbjohnson** [comment]
@locks Okay, I am happy with Frank's solution. Thanks for your help!

I have a quick question, though: will edits to `master` appear in the `v1.13.0` guides, or will I have to wait for a new version to see the difference?

**Comment by locks** [comment]
Usually you will only see edits to master in a new version, as it's currently a lot of hassle to update old branches.
`v1.13.0` is slightly special because it's the last of the Ember `1.x` branch, so we might still deploy some more changes to it.

**Comment by michaelrkn** [comment]
I'm going to close this out, since this is not an issue when following the Ember CLI happy path. @frank06 and @garethbjohnson let us know if you come across anything else that's confusing!

**Comment by garethbjohnson** [comment]
@michaelrkn Sorry, I have a newbie question: what is the Ember CLI happy path, and how do I follow it? I have just been following the `emberjs.com` Guides section from the beginning.

**Comment by michaelrkn** [comment]
The happy path is the one with the rainbows above it and the unicorns dancing alongside :)

Jokes aside, the Guides are not in a state where a newbie can follow them from beginning to end and come out an Ember developer. We are working hard to change that, but we are an all-volunteer team and there is a lot of work to do. The next Guides release for 2.0 in a couple weeks should be much, much better, but I think there will still be a lot of big gaps for newbies. I'm hoping 2.1 will be in a state where it is more like what you're looking for.

**Comment by locks** [comment]
In another words, happy path means that you follow along without errors or distractions. "What if instead of using Ember Data I want to use Ember Model?" "What about EmberScript?" Not the happy path. It allows us to keep the guides focused and lean on API docs and community resources to fill in the rest.

**Comment by garethbjohnson** [comment]
@locks To be clear, I following the guides quite strictly, from the first page to this one. Is this not the happy path?

I'm sorry if I'm causing any trouble with my lack of Ember.js knowledge. I can try a third-party guide instead if this is a problem.

**Comment by michaelrkn** [comment]
The current state of the Guides is that they do not take you on the happy path. Our goal is to make the guides take you on the happy path, but they are not there yet. Honestly, I'm not sure the Guides are the best place to start for a relatively inexperience dev, although I'm not sure any other resource is particularly great either ;) My hope is that the Guides will be the best place to start within a couple months.

If you stick with the Guides, let us know what's working and what's not, and where you get stuck! The issue was helpful for us to identify a problem and fix it.

**Comment by frank06** [comment]
@michaelrkn  

> The issue was helpful for us to identify a problem and fix it.

What have you fixed?

The real issue though is Ember's Router. Why on earth isn't `auto` the default? Who uses `/#/`?

**Comment by michaelrkn** [comment]
Fixed: https://github.com/emberjs/guides/pull/540

Why: https://github.com/emberjs/guides/issues/537#issuecomment-127405131

**Comment by garethbjohnson** [comment]
@michaelrkn Okay, that makes sense. Thanks to you and @locks for all your help! I will find a tutorial elsewhere, but I wish you the best for the guides.

**Comment by frank06** [comment]
@michaelrkn Oh yea, IE6 :) Thanks for #540

**Comment by michaelrkn** [comment]
:+1:
