### ISSUE TITLE
bundle install error: repository not found (Fetching git://github.com/bsclifton/middleman-swiftype.git)

### ISSUE THREAD

**Issue by nicolechung** [emberjs/guides#54]
This repo doesn't appear to exist:
https://github.com/bsclifton/middleman-swiftype

**Comment by trek** [comment]
@bsclifton ?

**Comment by bsclifton** [comment]
Oh shoot, sorry, I deleted it after changed were merged upstream

**Comment by bsclifton** [comment]
Can we update to https://github.com/LeonB/middleman-swiftype? Out and about at the moment, but can submit a PR in an hour or so
