### ISSUE TITLE
Make it obvious to use KVO-compliant Array methods

### ISSUE THREAD

**Issue by xudaiqing** [emberjs/guides#543]
With help from the forum i finally find out how to use array in ember. 
Most important, how to use addObject and others. And the information of prototype extension of native array.
Maybe it's just because as i have used ember more than a year ago, i didn't read though the guide carefully.
But i believe it shouldn't that hard.
I think use array is a common case in develop a application and guide should cover that clearly. 
Currently I can't find enough information when i first enconter the problem.

http://guides.emberjs.com/v1.13.0/templates/displaying-a-list-of-items/
have cover it a little but [].pushObject seems come out of nowhere and when follow the link to the http://emberjs.com/api/classes/Ember.MutableArray.html 
It only says concrete implementations of this class include ArrayProxy and ArrayController.

**Comment by michaelrkn** [comment]
I agree. We should make it really obvious in http://guides.emberjs.com/v1.13.0/object-model/enumerables/ that you can't use `push`, that you need to use `pushObject` (and the other KVO-compliant methods).

**Comment by michaelrkn** [comment]
Closed by #555.
