### ISSUE TITLE
Give more context and background for The Object Model section

### ISSUE THREAD

**Issue by sajt** [emberjs/guides#554]
In the /object-model/classes-and-instances.md the first example is not clear for me.

If I put this:

```javascript
Person = Ember.Object.extend({
  say(thing) {
    alert(thing);
  }
});
```

To my routes js I get the following error:

    routes/posts.js: line 10, col 1, 'Person' is not defined.

but if I use 
```javascript
Ember.Person = Ember.Object.extend({
```

What is the perfect solution or where can I define classes?

**Comment by michaelrkn** [comment]
You're right, this isn't totally clear. I'm going to work on better explaining this section.

Check out http://guides.emberjs.com/v1.13.0/models/defining-models/ for the answer to your question.

**Comment by sajt** [comment]
thanks
