### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#557]
There is a lot of inconsistency in the Guides, including naming, writing style, examples, and presentation. We need a style guide so that there is some consistency in the way we write and present information.

Here is a list of things that we should discuss:

## Naming conventions
- [x] Ember vs Ember.js
- [ ] When to use Ember CLI and when to use just Ember (or Ember.js)
- [ ] Should we use `let` and `const`, and when to use each
- [ ] Capitalize Guides

## Organization

- [ ] Strive for guides that are fewer than X number of words - what should X be?
- [x] Should we make all examples consistent, eg about a blog app?
- [ ] Some rule of thumb like "Each page should be about one discrete topic"
- [ ] Each section should start with the most basic concepts and move to more advanced

## Code
- [x] When to use ES6 syntax?
- [x] Always use double quotes for strings?
- [x] Omit boilerplate in code blocks (eg `import Ember from 'ember'`)

## Minor style stuff

- [ ] Do list items end with a period or not?
- [ ] Headings should be title cased
- [ ] When to use H1, H2, H3, etc.
- [x] Should we have some basic grammar rules of thumb written out, like "Write in complete sentences"?
- [ ] Should we defer grammar and writing-style decisions to an established style guide, like the [APA guide](http://flash1r.apa.org/apastyle/basics/index.htm), [Economist guide](http://www.economist.com/styleguide/introduction), [BBC guide](http://www2.media.uoa.gr/lectures/linguistic_archives/academic_papers0506/notes/stylesheets_3.pdf), or [Wikipedia guide](https://en.wikipedia.org/wiki/Wikipedia%3aManual_of_Style)?
- [x] Or should we just keep it to something simple, like the Rails Guides: "Write simple, declarative sentences. Brevity is a plus: get to the point." And maybe discourage people from opening grammar/writing style PRs unless something is truly confusing.

As discussion continues on this issue, we can add to this list.

For reference, the [Rails API Documentation Guide](http://guides.rubyonrails.org/api_documentation_guidelines.html)

**Comment by michaelrkn** [comment]
We need a style guide, and this is only one small piece of the discussion. Personally, I don't think we should get bogged down in that when we have [more pressing outstanding issues](https://github.com/emberjs/guides/issues?utf8=%E2%9C%93&q=is%3Aopen+-label%3Acode+label%3A%22help+wanted%22), but maybe I'm just being grouchy :)

**Comment by michaelrkn** [comment]
Actually, this kind of stuff has come up enough that I'm going to change this into an issue for creating a style guide, so we at least have an open issue for it to begin discussion of what should be in it and what the timeframe should be for deciding and implementing it.

**Comment by HeroicEric** [comment]
I think this one would be a pretty easy change though, no?

**Comment by michaelrkn** [comment]
Yes, and many of the style guide things will be too, but 1) there are a lot of little things, 2) it will be an effort to get consensus on all of them, and 3) all together it will be a big effort.

**Comment by HeroicEric** [comment]
@michaelrkn :+1:

**Comment by locks** [comment]
My suggestion: open a PR adding a styleguide.md file, we can address the points in the diff. Quick rapidfire:

> Ember vs Ember.js

Ember.

> When to use Ember CLI and when to use just Ember (or Ember.js)

Ember CLI when we're referring to the CLI, Ember when we're referring to the framework.

> Should we use let and const, and when to use each

Yes; we can argue that later (cc @wycats)

> Should we make all examples consistent, eg about a blog app?

No, one application cannot sufficiently provide use cases for all of the guides unless they're exceedingly contrived, or the app too complex.

> When to use ES6 syntax?

Always.

To me "Minor style stuff" is less important at the moment until we nail down the other stuff, but it'll still be useful if/when we do a full review in the future.

**Comment by michaelrkn** [comment]
Sweet, will do before Thursday.

**Comment by michaelrkn** [comment]
See #591.
