### ISSUE TITLE
Section on Manipulating Model Relationships

### ISSUE THREAD

**Issue by kagemusha** [emberjs/guides#560]
Was thinking it would be helpful to have a section explaining how to relate objects to one another, particularly usage of addObject and removeObject.

Could either be a Model subpage, something like 'Working with Relationships", or a subsection of the 'Working with Records' page.

If people think this would be helpful, I can take a first stab at it.

**Comment by michaelrkn** [comment]
This should be part of the #449 effort.

**Comment by greyhwndz** [comment]
@kagemusha: I agree this would be helpful since I could see lots of questions regarding this on forums. I was just wondering if a title like "Manipulating Models thru their Relationships" would make this easily understandable?
