### ISSUE TITLE
Move "The Run Loop"

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#570]
It is the only page left in "Understand Ember", a section that probably shouldn't exist, especially if it only has one page. Where should "The Run Loop" go?

**Comment by michaelrkn** [comment]
Maybe under Components, since that seems to be the most common use case?

**Comment by acorncom** [comment]
:+1: on putting it under Components for now.  Long-term, I think it would be helpful to have some "High-level Ember Architecture" sections of some sort (sort of a "start here when digging into the internal guts of Ember").  That's what the "Understand Ember" section seemed to be beforehand, but I could see putting docs about FastBoot there as well in the future ...

**Comment by michaelrkn** [comment]
Closed via #573.
