### ISSUE TITLE
2.0 release blockers

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#571]
- [x] #570 
- [x] #545
- [x] #561 
- [x] #569
- [x] #574

**Comment by acorncom** [comment]
@michaelrkn @locks #561 is ready to be merged.

**Comment by acorncom** [comment]
Looks like #569 was merged and then removed.  So we're no longer blocked, correct?

**Comment by michaelrkn** [comment]
We have a PR coming as an alternative to #569. Should be ready to release in about 5 minutes!
