### ISSUE TITLE
Version picker doesn't work from v2.0.0 pages

### ISSUE THREAD

**Issue by cllns** [emberjs/guides#581]
Steps to reproduce: 

1. Visit http://guides.emberjs.com/v2.0.0
2. Click on any of the pages on the right, let's say: http://guides.emberjs.com/v2.0.0/getting-started/first-app/
3. Try to change the version in the top left, to any version (even v2.0.0). It'll try to visit http://guides.emberjs.com/v2.0.0/getting-started/v1.13.0 (with the last digits being whatever you clicked) and that gives you a 404.

This only happens from v2.0.0 though.  (Note that it *doesn't* happen from just http://guides.emberjs.com/v2.0.0, but only pages further down in the URL than that)
I tried taking a look at this locally, but I can't figure out how to get `versions.json` to work in dev.

**Comment by swr** [comment]
Looks like versions.json gets generated on deploy. You can see current version at: http://guides.emberjs.com/versions.json

Then replace dev copy of "Versions will appear here when deployed" with the proper json.

**Comment by cllns** [comment]
Yup, I tried that. It just tries to go to `v1.13.0` as the full URL (no http, etc), rather than relatively.

It's because the JS for [version-select](https://github.com/emberjs/guides/blob/master/source/javascripts/app/guides/version-select.js.erb#L7) assumes the URL looks like it does in production, not in dev.

 `guides.emberjs.com` redirects to `guides.emberjs.org/v2.0.0/`, where as `localhost:4567` is shows the v2.0.0 guides, and going to `localhost:4567/v2.0.0/` doesn't work.

**Comment by swr** [comment]
@michaelrkn Fixed it. Looks like version-select.js was indexing the slugs from the end. He switched it to go from the beginning/left.

**Comment by locks** [comment]
I confirm that @michaelrkn's fix is deployed. Thanks for opening the issue :)

**Comment by locks** [comment]
It seems the version switcher isn't completely fixed (switching from http://guides.emberjs.com/v2.0.0/getting-started/first-app/ will still give you a 404), but this specific issue is resolved.

**Comment by swr** [comment]
I think the current code may cause problems when the other versions of the guides don't have the same sections. Hence why the older versions just switched to the root level of the guides.

For instance go here: http://guides.emberjs.com/v2.0.0/object-model/ and then switch to v1.10.0

So I guess the best thing to do is just have it switch to the root of the version you are switching to rather than a sub section.

**Comment by jimbeaudoin** [comment]
The switcher need to switch to the root of the desired guide every time. not to the page it was before in another version.

**Comment by locks** [comment]
@jimbeaudoin that is not the intended behaviour for the switcher. it will switch to the nearest root if the current page is not available.

**Comment by jimbeaudoin** [comment]
@locks nice and better! :+1:

**Comment by michaelrkn** [comment]
> it will switch to the nearest root if the current page is not available.

That's news to me :) Sounds like a great feature though!

**Comment by locks** [comment]
@michaelrkn http://hood.ie/blog/the-hoodie-why-1-we-have-a-dreamcode.html ;)
