### ISSUE TITLE
JavaScript folder is a mess

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#582]
* Why is `swiftype.js.erb` not in the `app` folder?
* Why is there a `guides` subfolder in the `app` folder?
* Is `back-to-top.js` actually used anywhere?
* Why is there a separate manifest `guides.js` instead of just being part of `common-all.js`?
* Is `highlight.js` actually used anywhere? It's not `require`d in the manifests.

I *think* that all app-specific JS should be in the `app` folder without nesting, `back-to-top.js` and `highlight.js` should die, and `guides.js` should be folded into `common-all.js`. But maybe there is some method to this madness that I don't know.

**Comment by michaelrkn** [comment]
@trek @rwjblue Do either of you know anything about this?

**Comment by trek** [comment]
Guides were extracted from the main website repo, so a lot of assets remain in the location that made sense in _that_ project.

**Comment by michaelrkn** [comment]
Ah, I see. Does it make sense for me to process as outlined above?

**Comment by trek** [comment]
If you think it's the most critical next thing, the folder could clearly use a cleanup

**Comment by michaelrkn** [comment]
It caused me to waste 2 hours the other day trying to track down why version switching wasn't working because I didn't realize I was editing a file that wasn't used in production. Should take me 5 minutes to clean up and save the next person 2 hours.
