### ISSUE TITLE
Core Concepts

### ISSUE THREAD

**Issue by MarkMT** [emberjs/guides#585]
I've seen comments in various places suggesting that the learning curve on Ember is very steep and that the documentation is not as helpful to new developers as it could be. I'm completely new to Ember myself (long time Rails/jQuery developer) and I found that I had to read through all of the guides several times before I felt I could piece together a clear view of what seemed to be the main concepts. 

As an aid to help me organize my own thinking I've written an alternative version of the Core Concepts guide that captures what I found to be important for me to grasp as a new developer: https://github.com/MarkMT/guides/tree/concepts

If it's useful to others I'm happy for it to be used however anyone wants. Happy to provide a PR if that's useful or just have it used as food for thought.

The existing section describes the major components more or less independently, which is also the pattern that the Guides as a whole takes. For me, I found it helpful to take a more thematic approach and try to show more explicitly how the various parts fit together - YMMV. It's necessarily a lot longer, but it provides an overall perspective that I was missing.

I'm anything but an Ember expert so there may well be some mistakes or misunderstandings. Happy to take comments/corrections.

**Comment by locks** [comment]
While it would be more helpful to open a PR for this, big rewrites are also harder for us to deal with. The docs team has discussed an approach similar to yours, but we've had to put out some fires meanwhile.
I will bring this up in today's meeting and let you know the response.

**Comment by locks** [comment]
Stylistically speaking there would have to be some editing to bring your prose more inline with the guides. Thanks for sharing your effort!

**Comment by MarkMT** [comment]
However you decide to move forward is fine with me. If it's useful to your thought process that's great. I needed to write it just to help get some ideas clear in my own mind. My background is probably a little different from the average developer - more in architecture and technology strategy, so I tend to look for the key abstractions more than how-to's and code examples.

**Comment by michaelrkn** [comment]
Hey, I really like many of the ideas in your version!

**Comment by michaelrkn** [comment]
For others to check out, it's easiest to read at https://github.com/MarkMT/guides/blob/8cde513b1a56cc15dcff1a28167722ba8def5e0d/source/getting-started/core-concepts.md.

**Comment by locks** [comment]
I brought it up at the meeting (https://github.com/locks/core-notes/blob/august-13/docs-team/2015-08/august-13.md)

**Comment by locks** [comment]
I'm closing this issue since we've discussed the topic and decided on our way forward. Thanks for the feedback @MarkMT :)

**Comment by MarkMT** [comment]
Best wishes :)
