### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by MSch** [emberjs/guides#586]
We'd love to adopt a similar format to the Ember guides for [our product](http://pspdfkit.com/) as well.

The license says

> Code examples and Guides content are licensed under the MIT license
> Other content is not included in this license. This includes: The Ember.js
name and logo, as well as illustrations (other than diagrams in the guides).

Can you clarify under which license the non-Ember specific and not Ember-branded Ruby/HTML/CSS/JS parts are? Basically, may we fork the repo, remove the Ember-branding and use it to publish our own documentation?

Thanks!

**Comment by locks** [comment]
You can find more info at http://emberjs.com/legal/, and possibly contact @wifelette for specifics.

**Comment by locks** [comment]
I'm closing this as it is not an issue with the guides per se. Good luck :)
