### ISSUE TITLE
Setting Computed Properties section still refers to checking arity of function to treat as a setter instead of ES6 style setter like the example does

### ISSUE THREAD

**Issue by gjastrab** [emberjs/guides#592]
(referring to 2.0.0 of the guides)

The final paragraph of this page includes:

> so if you want to use a computed property as a setter, you'll need to check the number of arguments to determine whether it is being called as a getter or a setter

But the code example uses 

```
fullName: Ember.computed('firstName', 'lastName', {
  get(key) {
    return this.get('firstName') + ' ' + this.get('lastName');
  },
  set(key, value) {
    var [ firstName, lastName ] = value.split(/\s+/);
    this.set('firstName', firstName);
    this.set('lastName',  lastName);
  }
})
```

inconsistent?

**Comment by rwjblue** [comment]
Yep, we definitely need to fix the prose.
