### ISSUE TITLE
Flip version ordering in the version drop down 

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#600]
Over time it seems to make more sense to have older versions of the guides at the bottom of the versions menu instead of at the top ...

**Comment by locks** [comment]
I don't have much of an opinion on this. @michaelrkn ?

**Comment by michaelrkn** [comment]
Sounds good to me. I can take care of this before long.

**Comment by locks** [comment]
@michaelrkn I volunteer @acorncom for the task :trollface:

**Comment by michaelrkn** [comment]
@acorncom if you want to, the relevant code is in https://github.com/emberjs/guides.emberjs.com/blob/master/tasks/update-versions.js. Keep in mind that the change will only be for future versions - versions already released will have the old order.

**Comment by locks** [comment]
Yup, that's my one opinion on it (I have one after all). It will be confusing for someone changing between versions.

**Comment by acorncom** [comment]
I don't mind making the changes if we want to make them :-)

Re: versions already released having the old order ...  That's my one concern with making the change.  Is there no way to go back and change old versions?  I'm happy to do the leg work on the various pull requests if it's doable

**Comment by acorncom** [comment]
> I volunteer @acorncom for the task :troll face:

And agreed, @michaelrkn, you've got bigger fish to fry, leave this low-hanging fruit for the rest of us ;-)

**Comment by locks** [comment]
> Is there no way to go back and change old versions? I'm happy to do the leg work on the various pull requests if it's doable

Not currently feasible.

**Comment by acorncom** [comment]
Think we should skip it then?  Seems like bad UX to flip things on folks.  On the other hand, better to do it now than when we're on 2.6+

**Comment by locks** [comment]
I dream a dream that by `2.6` we'd have a different architecture.

**Comment by acorncom** [comment]
:-)  So then should I send in a pull request?

**Comment by locks** [comment]
@acorncom since this is non-critical and is a breaking ui change, I'd live to let it simmer a bit more.

**Comment by acorncom** [comment]
:+1:

**Comment by josemarluedke** [comment]
:+1

**Comment by locks** [comment]
@josemarluedke are you agreeing that we should change or that we shouldn't change? and why?

**Comment by josemarluedke** [comment]
Sorry, yeah, I think we should flip the order. For me makes more sense to have the newer versions on the top.

**Comment by greyhwndz** [comment]
Having the recent version on top would be :+1:

**Comment by michaelrkn** [comment]
Closed by #600.
