### ISSUE TITLE
Why is Ember Run Loop section removed?

### ISSUE THREAD

**Issue by phkavitha** [emberjs/guides#601]
The section that explains Ember run loop is really helpful for beginners. Why is that removed in Ember 2.0? Is it possible to bring it back?

**Comment by michaelrkn** [comment]
We removed the Understanding Ember section, since most of the content seemed better suited elsewhere. Since the run loop is most often used in components, it is now in the Components section: http://guides.emberjs.com/v2.0.0/components/run-loop/

**Comment by phkavitha** [comment]
Got it. Just found it.
