### ISSUE TITLE
General review of the Guides

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#602]
The Guides are long overdue for a top-to-bottom review. Let's split up the work and go through each section, looking for:

* clarity of writing;
* plenty of examples to illustrate concepts;
* starting with simple, easy concepts and moving to advanced, difficult concepts;
* keeping each page as short as possible and splitting up long pages;
* focus on the "happy path", and avoidance of edge cases;
* liberal linking to the API docs;
* removing mention of controllers as much as possible;
* and generally following the [Style Guide](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md).

Here are the sections and who is taking which:

* [x] Getting Started (will be taken care of via the tutorial)
* [x] ~~The Object Model~~ (recently reviewed)
* [x] Templates (@michaelrkn)
* [x] Routing (@michaelrkn)
* [x] Components (@michaelrkn)
* [x] Controllers (@michaelrkn)
* [x] Models (@bmac)
* [x] Services (@michaelrkn)
* [x] Testing (@toddjordan)
* [x] Ember Inspector (@mattw59)
* [x] ~~Addons and Dependencies~~ (moved to #824)
* [x] ~~Configuring Ember.js~~ (moved to #823)
* [x] ~~Contributing to Ember.js~~ (I took a glance and it seems fine)

If you'd like to help out, just leave a comment with which section you'd like to take on.

**Comment by michaelrkn** [comment]
@knownasilya @HeroicEric @acorncom @SaladFork @elbeezy @joost @eccegordo @mattw59 Any of you interested in helping out with this?

**Comment by SaladFork** [comment]
:+1:

**Comment by acorncom** [comment]
@michaelrkn Yeah, I'd be interested.  When are you wanting this done though?

**Comment by mattw59** [comment]
@michaelrkn Sure, I'm interested. I'll take a look at the Ember Inspector. I have the same question as @acorncom, mostly so I can prioritize my time.

**Comment by locks** [comment]
Two weeks before `v2.1`, see milestone.

**Comment by acorncom** [comment]
So about a month from now?  I'm happy to take controllers ...

**Comment by knownasilya** [comment]
I'll do services, since I need to get caught up on them.

**Comment by mattw59** [comment]
@michaelrkn @locks It is safe to assume you're looking for a PR with suggested changes?

**Comment by michaelrkn** [comment]
@mattw59 that's right.

**Comment by michaelrkn** [comment]
Can we actually set the deadline a bit sooner, in two weeks - Tuesday, September 1? Two weeks seems like plenty of time, and if somebody has to bow out, gives us more time to find a replacement to review that section.

**Comment by michaelrkn** [comment]
Also, as always, many small PRs are better than one large one - easier to review, faster to get feedback, more gets merged faster! Don't wait to open PRs until you are done reviewing your entire section - open PRs as soon as possible. Thanks!!

**Comment by michaelrkn** [comment]
@greyhwndz would you be interested in picking up one of the remaining sections?

**Comment by greyhwndz** [comment]
@michaelrkn maybe Components

**Comment by acorncom** [comment]
@michaelrkn We're still looking for help on Components apparently ...

**Comment by michaelrkn** [comment]
@acorncom I've ended up working on Controllers - could you take on Components?

**Comment by acorncom** [comment]
@michaelrkn I can *help* with Components, but don't think I'll have enough time to be the only one working on them :-)

**Comment by michaelrkn** [comment]
No worries! I'll take the Intro page for starters. Why don't you let me know what pages of the remaining ones you can get to, and I can figure out somebody else (likely me ;) to take the rest.

**Comment by michaelrkn** [comment]
I went ahead and dealt with Services.

**Comment by knownasilya** [comment]
Ah, was just getting stated on them. Sorry for the long delay. Thanks for tackling it.

**Comment by michaelrkn** [comment]
@knownasilya if you've got some bandwidth, we could use a hand on Testing and Components. If you'd prefer Components, just coordinate with @acorncom; if you'd prefer Testing, coordinate with me :)

**Comment by josescasanova** [comment]
I don't have much experience with Ember (~3 months), but am willing to help. Anything I can do?

**Comment by acorncom** [comment]
@josescasanova I'd suggest pulling down the Git repo and reading through the components pages (starting with "Wrapping Content in a Component").  If you notice any items that use a lot of jargon you don't understand, either create an issue (and mention me) or send in a pull request to fix it. Thanks!

**Comment by toddjordan** [comment]
@michaelrkn since I'm looking at updating the component testing guide, I'd be willing to go through the rest of the testing section and make sure things are up to date and the examples are working.

**Comment by michaelrkn** [comment]
@toddjordan That would be amazing! While you're looking at them, can you keep an eye out for anything that could use some cleanup to per the [Style Guide](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md#style-guide)? I took a quick first pass, but it could benefit from a more experienced set of eyes. Thank you!

**Comment by toddjordan** [comment]
No problem. Will do!

**Comment by toddjordan** [comment]
status: I'm working through the testing guides as follows:
* I created an ember project to run the test examples.  Its still a work in progress, but I wanted to make sure the examples ran and that the instructions were clear enough to get things running.  I plan to also install suave on it to make sure they are up to style standards.  Examples are here: https://github.com/toddjordan/ember-testing-guide-examples
* I'm working on updating each guide with changes as appropriate, with a focus on clarity and up to date code.  I'm still using the same examples for the most part.  I plan to have a PR opened by the weekend if I can continue to grab spare time.

**Comment by michaelrkn** [comment]
@toddjordan Sweet!!! The 2.1 release is scheduled for 1 week from today - if you're able to get a PR open by early next week so we can get the changes in before the release is cut, that would be super awesome.

**Comment by toddjordan** [comment]
Quick update on things with the testing guide... basic unit test, acceptance test, model, routes, and component guides are updated and in.  I passed over controllers because I thought their lives might be short, but I can go ahead an update things there if we think its worthwhile.  Also, I just submitted a PR on the test guide's intro, adding the concept of integration test, since that's more of a thing now.  Most of the text in that page was updated so I look forward to feedback I the pages I did check in I actually tried out in a project to make sure they work, except for acceptance tests, because I haven't written an app that can be basically tested by those tests.  I may go back and at least verify that the apis listed are still available though.

**Comment by michaelrkn** [comment]
@toddjordan Good stuff! If you have the time to do quick review of the Controllers page, that would be nice, since we're actually going to re-release this stuff for 1.13 and 2.0 (we normally don't re-release old versions of Guides, but since 1.13 will be supported for a long time, we're making an exception). Thanks for your good work!

**Comment by toddjordan** [comment]
👍Sure.  I'll work on it this evening.

**Comment by toddjordan** [comment]
Updated the testing intro guide based on comments, also created a new pr on the testing controllers guide
