### ISSUE TITLE
Add the "Editors" configuration page from Ember-CLI.com?

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#609]
I've found this page on the Ember CLI site to be quite handy on a regular basis (http://www.ember-cli.com/user-guide/#editors)  are we going to copy it over to the new Guides pages?  Seems like the best fit would be under "Configuring Ember.JS -> Editors", but I'm not sure that works well ...

**Comment by michaelrkn** [comment]
This doesn't feel like it's Guides material to me... I think @locks had suggested that this might be more appropriate for a blog post or something like that, and I'm inclined to agree.

**Comment by acorncom** [comment]
Sounds good, closing it now.
