### ISSUE TITLE
rootURL vs. baseURL :dizzy:

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#612]
So I'm not really sure which is correct here but I think we should make this more clear (so I can understand :smile: )

### Ember Guides

The [ember guides mention to specify a Root URL](http://guides.emberjs.com/v2.0.0/routing/) when "your Ember application is one of multiple web applications served from the same domain. For example, if you wanted to serve your blogging application from `http://emberjs.com/blog/`, it would be necessary to specify a root URL of `/blog/`."

### Ember CLI Guides

The [ember-cli guides mention to specify a Base URL](http://www.ember-cli.com/user-guide/#history-api-and-base-url) "if you are deploying the app to somewhere other than the root URL (/)"

### The Problem

This is confusing. I'm still not totally sure which one is the correct recommendation or maybe they both have their specific use cases but those are not clear to me.

I would have included a PR to help fix this but as I said, I'm not really sure what the answer is :smile: 

Can anybody halp so we can clear this up?

Related issues:

- [Remove specifying rootURL from ENV](https://github.com/ember-cli/ember-cli/pull/464)
- [rootURL deploy issues](https://github.com/ember-cli/ember-cli/issues/417)
- [Need more consistent handling of `baseURL` for testing apps in subdirectories](https://github.com/ember-cli/ember-cli/issues/4507)

Thanks to @davidpett for helping me out on Slack.

**Comment by locks** [comment]
I remember some discussion about potential problems with `<base>`, I was even under the impression it was to be removed.

**Comment by davidpett** [comment]
To further the confusion, both statements are correct. You use `baseURL` when you are deploying the app (meaning all app assets) to somewhere other than the domain root that it is served on (something like s3). In contrast, `rootURL` is used when the _application root_ is a sub directory on the domain

**Comment by jayphelps** [comment]
Further reading:

* [HistoryLocation doesn't use baseURL correctly](https://github.com/emberjs/ember.js/issues/5334)
* [Kill `<base>` tag](https://github.com/ember-cli/ember-cli/issues/2633)

**Comment by trek** [comment]
I'm going to schedule time with @rwjblue to clarify this

**Comment by michaelrkn** [comment]
@trek @rwjblue any progress figuring this out?

**Comment by michaelrkn** [comment]
@SaladFork is on this!

**Comment by michaelrkn** [comment]
Closing in favor of https://github.com/ember-cli/ember-cli/issues/4905.
