### ISSUE TITLE
Components > Composing Components Section inconsistently has pod based example

### ISSUE THREAD

**Issue by gjastrab** [emberjs/guides#614]
In the [Data Down](http://guides.emberjs.com/v2.0.0/components/composing-components/#toc_data-down) paragraph/subsection it introduces a template with a pod-based filepath for (I believe) the first time if sequentially reading the guides.

`app/users/template.hbs`

Wouldn't that be more consistent to be `app/templates/users.hbs`?

**Comment by michaelrkn** [comment]
Good catch! I think it would be `app/templates/components/users.hbs`, right?

@locks can you double-check me here?

@gjastrab could you open a PR to fix this?

Thanks!

**Comment by gjastrab** [comment]
@michaelrkn no this is referring to the template which uses the component being described.  Looks like all earlier examples always just refer to the main index: `app/templates/index.hbs` - perhaps that would be most appropriate?

**Comment by michaelrkn** [comment]
Oh I see what you're saying. Makes sense to me. But on the subject, are pods used anywhere else in the Guides? If not, we shouldn't use them here.

**Comment by locks** [comment]
Pods are not to be used until the RFC lands.

**Comment by greyhwndz** [comment]
@locks: What is the state for the Pods RFC?

**Comment by locks** [comment]
@greyhwndz I am not sure, but I haven't had word that the new structure is finalized.
