### ISSUE TITLE
Add a list of supported event type name on actions

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/guides#621]
Hi there. I think would be very helpful to have the list of events names that we can use when specifying  a action, e.g. `action 'someAction' on="submit"`. 

I assume that the best place for it would be here: http://guides.emberjs.com/v2.0.0/templates/actions/#toc_specifying-the-type-of-event Also, I tried out that example with the dash in the name and didn't worked (ember v2.0.0). Digging a little bit I found [this in the code](https://github.com/emberjs/ember.js/blob/v2.0.0/packages/ember-views/lib/system/event_dispatcher.js#L42), in there contain a list of events from the event dispatcher class.

I have 3 questions here:
- Are those types of events that that Ember supports?
- Which way is the correct way to specify the event name? `mouseUp` or `mouse-up`?
- Can I open a PR adding the list that is in the code as event names? Or do you have any other suggestion?

Thank you.

**Comment by gustavoguichard** [comment]
+1

**Comment by locks** [comment]
This used to be referred to at http://guides.emberjs.com/v1.12.0/views/handling-events/, but it's gone since Views are gone. Would be very helpful if someone updated that for components and submitted a PR.

**Comment by alvinvogelzang** [comment]
Interesting question. Maybe you can ask in the ember slack what's the correct way to specify event names. In http://guides.emberjs.com/v1.12.0/views/handling-events/ I see a link to the event names which are defined in the API http://emberjs.com/api/classes/Ember.View.html#toc_event-names. Maybe you can write a short section, as part of the components guide, about handling events. Because the Ember.Component Class still extends the Ember.View Class I think it's okay to still link to this list with event names.

**Comment by locks** [comment]
> Because the Ember.Component Class still extends the Ember.View Class I think it's okay to still link to this list with event names.

I disagree. That's an implementation detail, and views are legacy, users probably shouldn't need to know about them. Hm, we need to figure how best to update the documentation.

**Comment by alvinvogelzang** [comment]
True that. That can be quite confusing.

**Comment by pixelhandler** [comment]
So I'm curious, all the dom events that we had on view are still usable on components right? so perhaps just move the #toc_event-names section into the components guides.

Would be helpful, e.g. there are no guides (docs) for browser events in a framework to build browser apps, seems weird right. How does one know how to use drag / drop events in my components if I want to? Or, are events only supposed to be handled by using actions instead?

**Comment by locks** [comment]
Yup, that's what I'm going to do.

**Comment by pixelhandler** [comment]
@locks I'll take a stab at a PR for moving the events page back into the components section.
