### ISSUE TITLE
Component lifecycle hooks

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/guides#622]
Would be good to have a clear vision of the component life cycle, at this time I couldn't find a clear one.

We have the events in [API component doc](http://emberjs.com/api/classes/Ember.Component.html) and then we have [this blog post](http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html#toc_new-lifecycle-hooks) talking about new life cycles that is not in the API. It's confusing to understand that. Having a section in the guides could also be great for new devs coming from other frameworks.

**Comment by locks** [comment]
I believe someone is currently handling the components section, will confirm during today's meeting.

**Comment by josemarluedke** [comment]
I found this issue (emberjs/website#2321) that's related to this subject.

**Comment by greyhwndz** [comment]
I think this is worthy to be a Guide on its own under the Section Components. What do you think @locks?

**Comment by locks** [comment]
As per https://github.com/emberjs/website/issues/2321#issuecomment-135024955 they will be addressed when made public, which should be when glimmer components land.

**Comment by michaelrkn** [comment]
This is being worked on in #754.
