### ISSUE TITLE
Document that we support change highlighting

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#624]
Ran across this pull request today (https://github.com/emberjs/guides/pull/144).  @locks @michaelrkn did either of you know we support this?  Seems like it could be quite handy for longer guides (probably the tutorial?).

Want me to send in a pull request to document it in the contributing file?

**Comment by acorncom** [comment]
If we want to start doing this on the site, I'll open a separate issue to track the various places that need updating ...

**Comment by michaelrkn** [comment]
Oh interesting. I'm not sure where it would be useful in the Guides besides the tutorial though.

**Comment by acorncom** [comment]
![screen shot 2015-08-20 at 9 29 08 am](https://cloud.githubusercontent.com/assets/802505/9387484/f23f2616-471d-11e5-8923-d30cc41425c9.png)

?

I've noticed a number of places just looking through the templates where this type of short, additional snippet is added.  Doesn't seem urgent, but does seem like it could be a nice touch to the guides over time.

**Comment by locks** [comment]
@acorncom this ties in with a general confusion about the code snippets in the guides and the fact that most of them are partial (hence no copy pasting), so we have to address it from that angle as well.

**Comment by michaelrkn** [comment]
As discussed on the docs call today, we aren't going to do this.
