### ISSUE TITLE
[Typo] Section: Managing Dependencies

### ISSUE THREAD

**Issue by morganick** [emberjs/guides#625]
https://github.com/emberjs/guides/blob/master/source/addons-and-dependencies/managing-dependencies.md#javascript-assets-exporting-a-globals

Was the intent to say "Export Javascript assets as globals"?

**Comment by locks** [comment]
Some assets provide globals instead of modules (whether AMD, etc), so that header is about that. But "exporting a globals" seems grammatically wrong :P

**Comment by morganick** [comment]
I wasn't sure what it was trying to say.

**Comment by locks** [comment]
Not sure how to phrase it as a short header

**Comment by vikram7** [comment]
Just submitted a PR [635](https://github.com/emberjs/guides/pull/635) to help resolve some of the confusion.
