### ISSUE TITLE
[Brevity & Clarity] Guide: Configuring Ember CLI

### ISSUE THREAD

**Issue by morganick** [emberjs/guides#628]
https://github.com/emberjs/guides/blob/master/source/configuring-ember/configuring-ember-cli.md

"If you wish to make this change a permanent configuration change, change the .ember-cli file like:"

That's too much change. Also, if you already have an `.ember-cli` file with configuration options. You shouldn't change it to the following, but add the port to your current configuration.

**Change to:**

"To make this configuration permanent, add the `port` to your `.ember-cli` file:"

/cc @SaladFork

**Comment by SaladFork** [comment]
The "the" is still hanging, how about:
> To make this configuration permanent, add the `port` option to your `.ember-cli` file:

**Comment by morganick** [comment]
:+1:
