### ISSUE TITLE
Change all double quotes to single quotes

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#634]
Per https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md#strings.

**Comment by HeroicEric** [comment]
@michaelrkn in templates too? I usually use double-quotes in templates because HTML so wanted to clarify

**Comment by michaelrkn** [comment]
@rwjblue can you give some guidance here?

**Comment by rwjblue** [comment]
JS === single quotes
HTML / HBS === double quotes

Ember styleguide doesn't really address templates because there are very very few templates in the Ember repo.

**Comment by HeroicEric** [comment]
working on this now

**Comment by josenberg** [comment]
Why the use of quotes was defined this way?
