### ISSUE TITLE
Testing Controllers section uses `needs` in example

### ISSUE THREAD

**Issue by gjastrab** [emberjs/guides#643]
This has been removed in 2.0.0 yet is [an example](https://github.com/emberjs/guides/blob/e4e7978542bffa2fb8f8975aa572c60a4e8a8989/source/testing/testing-controllers.md#testing-controller-needs) in the v2.0.0 version of the guides.

**Comment by gjastrab** [comment]
was `needs` in a controller test also deprecated and replaced with something else?

```
moduleFor('controller:posts', {
  needs: ['controller:foo']   // replace with ??
});
```

**Comment by michaelrkn** [comment]
@trek maybe you can address this as part of your review of the Testing section?

**Comment by rwjblue** [comment]
`needs` in ember-qunit unit tests is not deprecated

**Comment by gjastrab** [comment]
PR opened to at least replace `needs` with `inject` in the controller examples
