### ISSUE TITLE
Should we explain in the controllers section of the guides that controllers will be going away?

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#660]
Per a discussion with @locks on Slack, he doesn't think so ...

**Comment by MarkMT** [comment]
Whether it should be in the controller section I'm not certain, but speaking as a newbie I do think it is important for this to be mentioned somewhere.

The reason I say this is that people reading the guides are not doing so in a vacuum, but rather in the context of a lot of other very visible writing and speaking emanating from the core team and other prominent developers. So inevitably the understanding they gain comes not just by mechanically digesting what the guides tell them but by trying to *interpret that* in relation to other reasonably authoritative things they're reading elsewhere. This is as much of a challenge for new people as simply understanding a simple description of the framework. It doesn't have to be much, but I think anything you can do to aid that process is worthwhile.

This is why, for example, in the Core Concepts strawman I wrote recently for #585, I made a point of noting how in the future components will take on the role that controllers currently play in relation to routing.

**Comment by locks** [comment]
This is material for the blog, like the 2.0 explaining the future of Ember.js.

**Comment by locks** [comment]
Routable components are still many point releases away, and at the right time a proper deprecation guide should be introduction with information on how to move, as well as an update of the relevant sections in the guide.
In my experience dealing with the subject, it would not be beneficial to say that routable controllers are going away. In fact, I wrote a blog post trying to clarify the meme that formed around controllers due to people saying controllers are going away.

**Comment by MarkMT** [comment]
> In fact, I wrote a blog post

That's great, though I can't say I recall seeing it, which maybe illustrates the challenge I'm talking about.

No disrespect intended... I'm just trying to give you a perspective from someone who has tried to use the guides recently. I think there are some opportunities in the guides to make life easier for people approaching the framework for the first time.

**Comment by locks** [comment]
> That's great, though I can't say I recall seeing it, which maybe illustrates the challenge I'm talking about.

I'd hug all the cats, but no one can do that :P I've talked to several people about ways to mitigate discoverability of community content, namely how to improve emberwatch.com.
