### ISSUE TITLE
Computed Property as setter

### ISSUE THREAD

**Issue by ofridagan** [emberjs/guides#664]
in http://guides.emberjs.com/v2.0.0/object-model/computed-properties/
it says:
"so if you want to use a computed property as a setter, you'll need to check the number of arguments to determine whether it is being called as a getter or a setter"

Is this still true?
It looks like the documentation doesn't fit the code example which shows a new syntax for defining a computed property setter:
```
fullName: Ember.computed('firstName', 'lastName', {
    get(key) {... },
    set(key, value) {...}
  })
```

**Comment by rwjblue** [comment]
Looks like the prose needs to be updated there.  Would you mind taking a look and submitting a PR?

**Comment by ofridagan** [comment]
OK, sure I can give it a shot.
I'm wondering myself though, is this now the only way to define a setter?
What about the Function's "Prototype Extensions" version? - ```(function(){}).property()```
how do you define a setter with it?

**Comment by rwjblue** [comment]
> I'm wondering myself though, is this now the only way to define a setter?

Yep.

> What about the Function's "Prototype Extensions" version? 
> 
> how do you define a setter with it?

You are correct, you cannot.

**Comment by ofridagan** [comment]
ok. thanks. let me prepare a PR

**Comment by ofridagan** [comment]
ah looks like it is already fixed on github:
https://github.com/emberjs/guides/commit/4aad8ea3cee8291b03ce448a15dd06db268192c5

Though I'm not sure why the part about "the previous value" was removed.
From the code, it looks to me like the setter is being called with the cached value - https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-metal/lib/computed.js#L464

**Comment by ofridagan** [comment]
if "the previous value" argument was indeed removed in Ember 2 then we can close this issue

**Comment by locks** [comment]
According to http://emberjs.com/blog/2015/05/13/ember-1-12-released.html#toc_new-computed-syntax it doesn't, so I'm closing this for now.
