### ISSUE TITLE
add ultra-basic one-page app

### ISSUE THREAD

**Issue by githubshrek** [emberjs/guides#700]
I know that folk are working on a "tutorial for building your first Ember app" https://github.com/emberjs/guides/issues/445. I think the example you're discussing there sounds great. I don't know enough Ember to comment on the detail, but I trust you!

However, I think though, for total Ember beginners, as I was a week ago, that the documentation desperately needs an ultra-basic one-page app (in addition to the more comprehensive tutorial example you are discussing).

The problem, as a newbie to Ember, was that there was nothing whatsoever to guide me between the Ember install (http://guides.emberjs.com/v2.0.0/getting-started/first-app/), and knowing what to do with all the hundreds of pages of text which follows. For example, though I read and understood the code in the Object Model pages (http://guides.emberjs.com/v2.0.0/object-model/classes-and-instances/), I had no idea where I was supposed to put such things.

I had "Welcome to Ember" on the browser window, but for a long time I had no idea how or where to change the app to make it do the "My name is {{name}} and I want to learn Ember!" example on http://emberjs.com/.

Concretely, what I propose is a new, single page, right after the http://guides.emberjs.com/v2.0.0/getting-started/first-app/ page which does:

* create another new app called "name-app" (and yes, I would make this another new app rather than an extension of the "my-new-app" app)
* starts up the server for this new app
* edits the /name-app/app/templates/application.hbs file and copy/paste the contents of the .hbs file for the "MY NAME IS AND I WANT TO LEARN EMBER!" example:
* save the file and refresh the web browser page

This might seem too trivial, but believe me, even for a seasoned web developer, this was totally missing and had to be figured out the hard way.

**Comment by michaelrkn** [comment]
This will be addressed by #445.
