### ISSUE TITLE
Explain, at least a little, the "my-new-app"

### ISSUE THREAD

**Issue by githubshrek** [emberjs/guides#701]
Going through the tutorial as a newbie to Ember (but as an experienced web developer), looking back at the past week, I realise one of the things which is missing is a very simple overview of the "my-new-app" which is created on http://guides.emberjs.com/v2.0.0/getting-started/first-app/.

The documentation currently just says "Navigate to http://localhost:4200 to see your new app in action.". That's it. OK, it works. Great. But there's currently no explanation whatsoever of how, or what files are involved etc.

Now, obviously at this stage in a user new to Ember you don't want to give them too much detail, but, at least the documentation should:

* indicate which file contains the "Welcome to Ember" message
* the basic meaning of this file, especially, in easy terms, what the {{outlet}} statement is all about, since that is new to folk like me
* what is actually happening in terms of how the server is processing this file (and other files)

**Comment by michaelrkn** [comment]
This will be addressed by #445.
