### ISSUE TITLE
Add very beginner view of the file structure of an app

### ISSUE THREAD

**Issue by githubshrek** [emberjs/guides#702]
One of the things which, I realise is totally missing from the very start of the http://guides.emberjs.com/v2.0.0/getting-started/first-app/ pages is a total beginner guide to the file structure of an Ember app.

Since I don't understand lots of the Ember stuff yet, I eventually figured out the things which are really relevant to me at this beginner stage of learning:
* in the my-new-app directory, the key folder is the "app" folder. This is where the meat of the application lives. The rest is Ember magic stuff which can be ignored for now.
* in the app folder (i.e. my-new-app/app), the index.html file is the basic file for the app
* from the templates folder (i.e. my-new-app/app/templates), is the Handlebar template file, application.hbs, which really does all the work for this first app
* the app folder has many other folders with names like components, controllers, helpers, models, routes and styles. You can see that the following documentation goes through each of these things one by one

This is what is currently missing from the "GETTING STARTED" section. This is probably about all the level of detail which is needed.

**Comment by michaelrkn** [comment]
This will be addressed by #445.
