### ISSUE TITLE
Swiftype search broken for v1.13.0 of the guides

### ISSUE THREAD

**Issue by louim** [emberjs/guides#705]
Hello,

When I try to use the search on the v1.13.0 of the guides, I get:

```
Uncaught TypeError: Cannot read property 'query' of undefined
```
in the console, and the search obviously doesn't work. It works correctly with all other version of the guides.

**Comment by josemarluedke** [comment]
Same problem as emberjs/website#2359.

**Comment by michaelrkn** [comment]
This is true. Sorry about that. We will be re-deploying before too long and it will be fixed then.
