### ISSUE TITLE
Improve selectability of text in guides

### ISSUE THREAD

**Issue by ononotofu** [emberjs/guides#711]
Text is generally difficult to select/highlight in the current version of the guides. A working example of this issue can be found at http://guides.emberjs.com/v2.0.0/object-model/enumerables/ -- try selecting the last paragraph of the opening section:

>The Enumerable API follows ECMAScript specifications as much as possible. This minimizes incompatibility with other libraries, and allows Ember.js to use the native browser implementations in arrays where available.

The selection is pretty much only possible if you start from the left, at the beginning of the paragraph, and select until the end. If you try from the right side, the margins are so tight that selecting just past the div [or ending period] will result in the entire left nav being also selected (from the beginning). I figured this was so minor that it wasn't really worth opening up an issue and that most intelligent users would probably just select from the left anyway and I was just an anomaly and I would try to correct this behavior. 

but then try selecting the following header:

>USE OF OBSERVABLE METHODS

some mystical lock or paperclip or something appears when you attempt to select it from the left, like a reasonable, normal person and still somehow the entire left nav bar becomes selected if you manage to work around the anchor.

I would guess this is probably the least important problem ever brought up in an issue but low friction means of remembering/selecting/grabbing portions of our guides should be a priority because new users might assume any presentation issues with our website could be due to the framework itself.

[edit: this is in Chrome on OS X Yosemite]

**Comment by digitalfrost** [comment]
I am not able to reproduce this issue in Chrome Version 45.0.2454.85 on Windows 8.1
nor in Firefox 40.0.3 on Ubuntu.

**Comment by ononotofu** [comment]
@digitalfrost Just tried it in Firefox (40.0.3) on Ubuntu and was able to reproduce, but because of style differences the ending period isn't completely aligned to the div's right edge as it is in OS X so the behavior is harder to trigger. The header example should still be illustrative as it is left-aligned.

**Comment by michaelrkn** [comment]
I can't reproduce either on Chrome/Yosemite. The markup for this page is very standard. Feel free to upload a video demonstrating the problem and re-open.
