### ISSUE TITLE
No idea given where the "Person" object needs to be located

### ISSUE THREAD

**Issue by githubshrek** [emberjs/guides#714]
On the http://guides.emberjs.com/v2.0.0/object-model/classes-and-instances/ page, there is currently no idea given where the "Person" object code needs to be put. I tried sticking it in the following place, which makes my Ember app not work any more. The example which follows has "app/components/todo-item.js" as a header to the example. Can the same thing be put above the "Person" code? 

import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';

var App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver
});

loadInitializers(App, config.modulePrefix);

Person = Ember.Object.extend({
	  say(thing) {
	    alert(thing);
	  }
	});

export default App;

**Comment by locks** [comment]
It's just a snippet of code, there is no specific place to put it. If you want a person object, use ES6 modules like normal: create a person file where you think it should go, export the object, import with the correct path.
