### ISSUE TITLE
JSBin Examples Broken

### ISSUE THREAD

**Issue by swashcap** [emberjs/guides#72]
* URL: **<http://emberjs.com/guides/components/wrapping-content-in-a-component/>**
* Browser: **Google Chrome Version 41.0.2272.101 (64-bit)**
* OS: **OS X 10.10.2**

![screen shot 2015-03-20 at 3 54 16 pm](https://cloud.githubusercontent.com/assets/1858316/6762231/9069332c-cf19-11e4-906f-a1ea56235af1.png)

I’m noticing that all the JSBin embeds in the _Components_ section are broke.

**Comment by trek** [comment]
We're in the process of removing the JSBins for 1.11
