### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by MaximAbramchuck** [emberjs/guides#731]
Hey, guys, I want to contribute to emberjs.com, so, I'm looking through issues at this repository and at the https://github.com/emberjs/website.
50% of all the issues is just broken links because of the versioning. What do you think about this problem?
Or how to determine where to redirect user if page with documentation is ready yet? Remove the link or redirect to the latest one stable release?
How can we solve it globally?

**Comment by michaelrkn** [comment]
Hey @MaximAbramchuck! Thanks for your interest in helping. There are two things that need to be done. First, you could audit the guides for broken links. Second, you could work on #598 to help this from becoming an issue again. Let us know if you have any other questions!
