### ISSUE TITLE
API: Missing method or broken link?

### ISSUE THREAD

**Issue by morganick** [emberjs/guides#734]
The following link should take you to the method `replaceRoute`, however, that method no longer exists.

http://emberjs.com/api/classes/Ember.ControllerMixin.html#method_replaceRoute

The link is in the text "See also replaceRoute" at the bottom of the `transitionToRoute` method.

**Comment by locks** [comment]
I can't find any reference to that link in the Guides, if you meant to open an API documentation issue, that's on emberjs/ember.js instead.
That method is still there though, it's just private so you have to have that toggled on.

**Comment by morganick** [comment]
:+1:
