### ISSUE TITLE
confusion about model hook and components and attr proxies

### ISSUE THREAD

**Issue by eccegordo** [emberjs/guides#757]
Here: 
http://guides.emberjs.com/v2.0.0/components/passing-properties-to-a-component/

It shows

```
export default Ember.Route.extend({
  model() {
    return this.store.findAll('post').get('firstObject');
  }
});
```

and suggests you can do the following in your templates

```
<h1>Template: {{title}}</h1>
{{blog-post}}
```
or 

```
{{blog-post title=title}}
```

This bare `title` attr is surprising to me. I thought this only worked this way with the ObjectController and proxy behavior.

Isn't the proper form this

```
{{blog-post title=model.title}}
```

I think some more substantive clarification on exactly how the model hook and the whole attrs hash should work would be helpful.

Also, a little puzzled by the whole linkage between route and component and the ambiguous messaging caused by the fact that routable components are not yet finished.

I think this is a bug unless i am misunderstanding the removal of ObjectController in 2.0. I am not sure most readers of the guides will necessarily pick up the fact that `legacy controllers addon` is needed to work with the guides as stated.

https://github.com/emberjs/ember-legacy-controllers

Here is a twiddle that demonstrates that the guides are wrong, at least in terms of the out of the box experience.

http://ember-twiddle.com/445278f057155cf10dbb

**Comment by michaelrkn** [comment]
Thanks for the heads up on this! In the future, for such a simple problem, it would probably be faster for both you and the guides maintainers if you just open a PR to fix the problem. Thanks!
