### ISSUE TITLE
Getting Started Component tutorial magical listing?

### ISSUE THREAD

**Issue by edgenard** [emberjs/guides#762]
I am going through the getting started guide, more specifically, the tutorial on adding a component. In [this](http://guides.emberjs.com/v1.13.0/getting-started/component-hide-show-image/#toc_hiding-and-showing-an-image) section there is a code snippet: 
```
<li>{{rental.owner}}'s {{rental.type}} in {{rental.city}}
    {{#if isImageShowing }}
       <p><img src={{listing.image}} alt={{listing.type}} ></p>
     {{else}}
       <button>Show image</button>
    {{/if}}
</li>
```
This code snippet introduces `listing`,  where does that come from? How would the template have access to that data? Especially if it wasn't passed it like `rental` was from the `index.hbs`.  It was not mentioned before or shown anywhere else.

**Comment by locks** [comment]
This is part of the tutorial (https://github.com/emberjs/guides/pulls/kellywerks), I merged it too early.

**Comment by michaelrkn** [comment]
I'll be re-deploying without this commit in a moment.
