### ISSUE TITLE
Update Code Blocks to include additions, removals, and highlights 

### ISSUE THREAD

**Issue by trek** [emberjs/guides#77]
A big challenge in writing tutorials where code mutates over time is accurately drawing the reader's attention to lines of code that have been added, removed, or need highlighting.

The react docs do an excellent job here:
![getting started react 2015-03-22 10-52-51](https://cloud.githubusercontent.com/assets/9736/6770051/9f3b6244-d081-11e4-8eba-a5af78ddc7f9.png)

They've augments the fenced code 'metadata' section with a micro syntax to define highlights:

Highlight one line:
~~~
```javascript{10}
~~~

Highlight multiple lines:
~~~
```javascript{3,10,55}
~~~

In addition to this, we can expand the syntax to include classes for line additions and removals:

Line 10 is removed:
~~~
```javascript{-10}
~~~

Line 10 is added:
~~~
```javascript{+10}
~~~

Line 10 is removed, line 15 is added, line 16 is highlighted:
~~~
```javascript{-10,+15,16}
~~~

**Comment by danmcclain** [comment]
@trek: I'd be interested in taking a stab at it, but wouldn't be able to start until tonight or tomorrow.

**Comment by tonylukasavage** [comment]
"line 15 is added" in your final example

**Comment by rwjblue** [comment]
@tonylukasavage - Good catch, updated.

**Comment by wycats** [comment]
This would be amazing!

**Comment by danmcclain** [comment]
Made some good progress on this last night, here are some screenshots of the styling I've come up with

 * Removed
![ember js - templates the application template 2015-03-23 07-28-51](https://cloud.githubusercontent.com/assets/144138/6779015/5c5f2020-d12e-11e4-9867-35fe593174c5.png)

 * Added (Contrast might need to be adjusted on line 6)

![ember js - templates the application template 2015-03-23 07-31-13](https://cloud.githubusercontent.com/assets/144138/6779078/afc8edae-d12e-11e4-961d-ff2f2c0992f5.png)

* Highlighted
![ember js - templates the application template 2015-03-23 07-32-35](https://cloud.githubusercontent.com/assets/144138/6779087/ca819966-d12e-11e4-9548-99ed7e328df9.png)

I think I'm going to lighten the colors across the 3 states, to make sure to maintain a good contrast

**Comment by trek** [comment]
:+1: this is great

**Comment by joostdevries** [comment]
really awesome!

**Comment by danmcclain** [comment]
I've been using [this contrast accessibility tool](http://webaim.org/resources/contrastchecker/) to updated the code block styles while picking colors for the highlights. Some of the contrasts are a little lacking, but wanted to keep the differentiation between things. Here is where I am at:

![ember js - the object model computed properties 2015-03-23 16-37-52](https://cloud.githubusercontent.com/assets/144138/6790064/4da7182e-d17b-11e4-94a8-6901ad14fd5d.png)

Compared to current:

![ember js - the object model computed properties 2015-03-23 16-41-09](https://cloud.githubusercontent.com/assets/144138/6790073/6dfdbbaa-d17b-11e4-8f0a-aa239b24f647.png)

Going to write up the parsing code now

**Comment by trek** [comment]
Closing for #80
