### ISSUE TITLE
What should be done with the Run Loop guide?

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/guides#775]
This seems sideways.

<img width="452" alt="screen shot 2015-09-19 at 11 03 03 am" src="https://cloud.githubusercontent.com/assets/1377/9977466/048c4300-5ebe-11e5-8b1e-81bac0870521.png">

**Comment by locks** [comment]
https://github.com/emberjs/guides/issues/570

**Comment by stefanpenner** [comment]
restoring it to the only thing in "concepts" seems better then this.

**Comment by michaelrkn** [comment]
> restoring it to the only thing in "concepts" seems better then this.

@stefanpenner can you elaborate?

**Comment by michaelrkn** [comment]
I'm pretty against having an "Understanding Ember" section, especially if it only has one page in it - the Guides should be focused on the practicality of how to build Ember apps, and any content about those practical applications should fit into the existing sections. On the docs call today, someone mentioned that Glimmer Components will make the run loop even less important to understand for most everyday Ember development. Personally I lean towards taking it out of the Guides entirely and putting its content into the API docs and maybe a blog post or tutorial somewhere else. But I'm open to other ideas.

**Comment by anotheredward** [comment]
I needed this page today and had to expand every tab to find it.

I found this statement unclear "Relying on autoruns is not a rigorous or efficient way to use the runloop. Wrapping event handlers manually is preferred."

Does that mean wrapping event handlers with Ember.run as in this example:

```javascript
$('a').click(() => {
  Ember.run(() => {  // begin loop
    // Code that results in jobs being scheduled goes here
  }); // end loop, jobs are flushed and executed
});
```

**Comment by mixonic** [comment]
@anotheredward you understand the meaning correctly.
