### ISSUE TITLE
run-loop guide has mistakes

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/guides#776]
`once` and `scheduleOnce` require stable functions, anonymous ones are new on each invocation and as such are run multiple times

https://github.com/emberjs/website/commit/ddbc9bc047cba3f4648d708b3b8d45e9b08480f2

My recommendation is:

* to remove the current incorrect usage of `once`, the [API docs](http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce) explain it correctly.

**Comment by michaelrkn** [comment]
Sounds good to me. Can you open a PR?
