### ISSUE TITLE
Add a "Working With Relationships" guide to Models

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#785]
Right now, there's scant documentation of how to work with related Ember Data models in the Guides. We should add a page called Working With Relationships that documents:

* how to create a new instance of a model that `belongsTo` another model
* how to update a model so that it `belongsTo` another model
* how to update a model that `hasMany` of another model
* how to work with relationships, especially that they return promises
* how to remove a relationship

**Comment by kevinkucharczyk** [comment]
I'd gladly help out with this, but I'm not quite sure on what the best practices in Ember are.

First of all, when creating a new model (let's say a *comment* model that `belongsTo` a *post* model), is the following okay?

```
var post = this.get('post');
var comment = this.store.createRecord('comment', {
  post: post
});
comment.save();
```
Is it necessary to also call `save()` on the *post* model after having saved the comment? I believe this would not be needed, as the backend should update the relationship on both sides and Ember Data would also know about it right after the `createRecord` call.


Next up, let's say I want to add the *comment* to the *post's* `hasMany` relationship:
```
var comment = this.store.createRecord('comment', { //content }});
this.get('post.comments').pushObject(comment);
comment.save(); // or maybe I should call save on the post? perhaps both models?
```
Is this correct?


And my last question is about removing relationships. For a `belongsTo`, I'd simply set the relationship to `null`:
```
comment.set('post', null);
comment.save();
```
This works, but is it the right way? What about removing a *comment* from the `hasMany` in *post*:
```
var comment = this.get('comment'); // or some other get operation
this.get('post.comments').removeObject(comment);
this.get('post').save(); // or should I call save on the comment?
```

**Comment by locks** [comment]
@kevinkucharczyk make the PR and we can discuss there ;) I would check with the ED peeps on Slack first.

**Comment by michaelrkn** [comment]
@kevinkucharczyk Thanks a bunch for jumping in on this! I have many of these same questions myself :) Just to give you a heads up, 2.1 is being released on Wednesday, so we have a hard deadline to close this issue by Tuesday 5pm Pacific (so that we have the evening to get ready to deploy); we're looking to have a PR open by Monday night so there is time to fix any problems. If there's any reason you don't think you can work on this in that timeframe, let me know and I'll probably pick it up myself. Thanks!!

**Comment by michaelrkn** [comment]
@bmac maybe you know the answer to some of @kevinkucharczyk's [questions above](https://github.com/emberjs/guides/issues/785#issuecomment-143548037)? Could you also review #818 and make sure those questions are addressed appropriately there?
