### ISSUE TITLE
Node version in "Getting Started"

### ISSUE THREAD

**Issue by workergnome** [emberjs/guides#788]
On the [Getting Started](http://guides.emberjs.com/v2.0.0/getting-started/) page, it talks about testing the current version of node.  It says:

> The output should say something like 0.12.x

It looks, though, like Node has jumped a bunch of versions [see here](https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d), and is now **v 4.1.0**.  That's a big enough change that it might be worth updating the docs?

**Comment by locks** [comment]
Make sure everything works under `4.x` and make the relevant PR if that is the case please.
