### ISSUE TITLE
Update initializers page to match 2.1 initializer changes

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#789]
Per https://github.com/emberjs/ember.js/issues/12336, there are changes come to the `initializers` page that will need to be put in.

@locks @michaelrkn Seems like we'd need to wait until 2.1 lands (and guides have split) to do this, but do we want to have a pull request pending to make the needed changes as soon as possible?

**Comment by michaelrkn** [comment]
@acorncom see https://github.com/emberjs/ember.js/issues/12336#issuecomment-142636333. A PR would be very welcome!!

**Comment by dgeb** [comment]
As requested by @michaelrkn, I'll work on this.

**Comment by michaelrkn** [comment]
@dgeb, can you also take care of #771/#772 while you're at this? It seems like this will supplant/fix those.

**Comment by michaelrkn** [comment]
@dgeb What's the status here? I believe 2.1 ships in the next couple days, so we need this ASAP to get it in!

**Comment by rwjblue** [comment]
I am generally shooting for release on Sunday, but it might end up being Monday (depends on this and a few other factors).

**Comment by michaelrkn** [comment]
Sounds good!

**Comment by dgeb** [comment]
I'm seeing how much of #827 I can complete before the release, since the initializer docs will be much improved by additional context. Given @rwjblue's schedule, I'll shoot for a PR by Friday.

**Comment by michaelrkn** [comment]
Sounds good. If you have the bandwidth, it would be great to get a PR by Thursday so we have Friday to review (the weekends are often pretty quiet in terms of folks helping out with docs).

**Comment by dgeb** [comment]
> it would be great to get a PR by Thursday so we have Friday to review

ok, will try!
