### ISSUE TITLE
Re-think glossary?

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#79]
I love the idea of having a glossary containing definitions/explanations of concepts necessary to understand how to work with Ember. I imagine many developers come to Ember without knowing what concepts like promises, ES6 modules, or even Node.js really mean. I think having glossary will go a long ways towards easing Ember's learning curve. Thanks @bsclifton for putting it together!

As I've taken a closer look at the current glossary, I worry that many people will skip over it, seeing it as just a big list of terms that may or may not be helpful. While all of the currently included terms are good to know, not all of them are really necessary to get going with Ember, such as _CDN_ and _Shadow DOM_.

I'd like to take a crack at re-writing a bit of it, trying to focus just on the concepts necessary to get going with Ember, and including a bit longer explanation for each of them.

If that sounds good, here is a brainstorm of what might be good to put in the glossary:

* node.js
* npm
* bower
* ES6 modules
* promises
* unit tests
* acceptance tests
* json

I'm intentionally excluding concepts that should be covered in the guides, and only including concepts that a developer should be familiar with _before_ starting with Ember.

I'd love to get suggestions of any other concepts that the rest of the guides should be able to assume reader familiarity with.

**Comment by bsclifton** [comment]
Shadow DOM was included so that folks don't confuse any talk of the virtual DOM. CDN I think is important because when it's time to deploy, you're going to want to host static content on something like Divshot and maybe even using the ember-cli-deploy

Looking forward to the changes :smile:

**Comment by vire** [comment]
for me as a person coming from non-ruby environment there were also few terms I've never heard before like:

- [ ] pods
- [ ] assets-pipeline

**Comment by trek** [comment]
It should probably also move to its own section. Making it part of another section seems odd.

**Comment by Serabe** [comment]
I would change _integration test_ to _acceptance test_ to fit ember-cli naming. Since I'm organise Ember.js Madrid, I can ask some people about what they miss in the _core concepts_ guide.

**Comment by michaelrkn** [comment]
@vire I think _pods_ and _asset pipeline_ probably deserve their own page entirely - #31 mentions that the info on the asset pipeline needs to moved over from http://www.ember-cli.com/. 

@trek _Getting Started_ feels like the appropriate place to put a list of background concepts that are important to understand. I'm thinking instead of trying to explain each of them in detail, I'll simply link to good blog posts or other pages that cover them in depth for a beginner.

@Serabe Thanks for the tip on acceptance test. I've updated it above. I'd love to get some feedback from your meetup.

I'm hoping to have some time tonight or tomorrow to start working on this. Thanks for the feedback so far.

**Comment by michaelrkn** [comment]
Oh also @bsclifton - What do you think about having two pages? One for crucial _background concepts_ with links to longer explanations, and one for _additional topics_ that aren't crucial for getting started, but will be useful as you get up to speed? In fact, I think most of the current glossary falls into this second category.

**Comment by bsclifton** [comment]
Love it- in fact, the short version of the glossary can probably be written as a general overview which links to the additional sites, like you're saying.  Just real quick off the top of my head, here's what I mean...almost like an end to end explanation

```
Welcome to the wonderful world of Ember.  Let's go over a the life of a typical web developer and the application they create, including getting folks using it.

1) Create your app using Ember-CLI.  This will create the directory structure and files to get you started.

2) Add in your own logic.  If you look at the existing documents, you'll notice everything is packaged as ES2015 compliant "modules".  Your code will work the same way; if you need access to a module, you just import it.  Most people write JavaScript, but some people prefer to use CoffeeScript, which is a language which end up compiling/transpiling to JavaScript.  Just something to be aware of

3) Style your app.  The bare bones way to do that would be with CSS... but you can also take advantage of more advanced styling using technologies like Sass or LESS, which might be easier for you to maintain and they'll get compiled to CSS.

4) Build and check your app.  You can create test cases, run a linter.  Things to increase your confidence in the code.  During this process, you'll be combining and minifying your source files, which makes it easier (and more efficient) for the client to process.  Some browsers can only make 2 or 4 concurrent HTTP requests, so this build pipeline helps.

5) Deploy your code.  This usually means just FTPing your content to your hosting provider.  While server side technologies like Rails and C# might be fine on your hosting, you may want to choose a CDN for the static content (images, CSS, JavaScript) since it doesn't change.  The content delivery network will geo-locate your static resources, meaning your client has even faster access to them.

Get stuck? usually you'll want to make a JSBin to isolate the problem.  You can ask for help on IRC... etc...
```

**Comment by michaelrkn** [comment]
@bsclifton I like the intent, but I'm not convinced those are the 5 most important points to think about as a new Ember developer, and if we're going to build an overview page, I want to really think about what the most important pieces of the process are. For now, I'm going to keep fairly close to the same format we have now and get some feedback. PR coming in a sec.

**Comment by Serabe** [comment]
@michaelrkn I didn't get any suggestion from the people in the meetup but I got a couple of them from a colleague starting with Ember: CSP and Semver.

**Comment by michaelrkn** [comment]
@Serabe Thanks a bunch! Semver seems like a really good one; I've added it. I searched the Guides and didn't see any places where CSP is referenced, so I think that's probably more "good-to-know" than "crucial background knowledge".

**Comment by Serabe** [comment]
Last week, I had a designer panicking because there were a huge error in the application and it was due a chrome extension adding some inline styles.
