### ISSUE TITLE
Invalid links on page "defining-models"

### ISSUE THREAD

**Issue by cyjia** [emberjs/guides#810]
On page [defining-models](http://guides.emberjs.com/v2.0.0/models/defining-models/), following links are invalid:

- [Creating and Deleting Records](http://guides.emberjs.com/v2.0.0/models/creating-and-deleting-records/)
- [Persisting Records](http://guides.emberjs.com/v2.0.0/models/persisting-records/)
- [Working with Records](http://guides.emberjs.com/v2.0.0/models/working-with-records/)
- [The Rest Adapter](http://guides.emberjs.com/v2.0.0/models/the-rest-adapter/)

The links didn't exist on [index page](http://guides.emberjs.com/v2.0.0/models/).

I checked source of branch v2.0.0, and found the pages were there. But on branch master, they are gone. Seems like [index page](http://guides.emberjs.com/v2.0.0/models/) and [defining-models](http://guides.emberjs.com/v2.0.0/models/defining-models/) are referencing deployments of master and v2.0.0.

**Comment by locks** [comment]
Hi, thanks for spotting it! Can you submit a PR fixing it?
The fix is linking to the new sections instead, since the current ones are outdated.

**Comment by cyjia** [comment]
I would like to fix it, but I didn't know how to do it.

I tested `bundle exec middleman` with branch `v2.0.0` in my local environment, and the links above were on `index` page of `models` section, but our on-line version didn't have those links.
