### ISSUE TITLE
Each-in is not in ember 1.13

### ISSUE THREAD

**Issue by amrdraz** [emberjs/guides#811]
I'm using Ember.js 1.13.10

I get an Assertion Error helper 'each-in' could not be found

I searched the code in my bower components and indeed the each-in helper is not in the codebase

I thought ember 1.13 is identical to 2.0 minus the depreciations.
but perhaps I misinterpreted the [change log](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_each-in-helper)

that said it's misleading to have this feature in the guide

**Comment by locks** [comment]
This guide slipped through, thanks for pointing it out.

**Comment by michaelrkn** [comment]
This is my fault. `each-in` is in 2.1. I recently re-released 1.13 and 2.0 to backport a number of important Guides changes and didn't properly remove `each-in` (or `with` for that matter). When 2.1 is released we'll fix this.

**Comment by locks** [comment]
Fixed!

**Comment by michaelrkn** [comment]
Thanks!!!
