### ISSUE TITLE
Update bound attribute syntax

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#82]
I believe Ember 1.11 removes the need for `bind-attr`, so https://github.com/emberjs/guides/blob/master/source/templates/binding-element-attributes.md and https://github.com/emberjs/guides/blob/master/source/templates/binding-element-class-names.md should be removed. 

Since inline `if`s are much saner to use for the new attribute binding syntax - 

```
<div class="{{color}} {{if isEnabled 'active' 'disabled'}}"></div>
```

I think it would make sense to add this example to https://github.com/emberjs/guides/blob/master/source/templates/conditionals.md. 

The only thing I'm not sure about is the part on [Adding data attributes](https://github.com/emberjs/guides/blob/master/source/templates/binding-element-attributes.md#adding-data-attributes). Maybe this should be moved to the Views section somewhere?

**Comment by kellysutton** [comment]
I'll take a crack at this. PR incoming.

**Comment by michaelrkn** [comment]
Thanks for helping out with this, @kellysutton!
