### ISSUE TITLE
Update "Configuring Ember.js" section

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#823]
The "Configuring Ember.js" section of the Guides could use some love. A couple things jump out at me. 

"Configuring Your App" should probably list out configuration options or at least link to an API reference of where to find those options.

The sections following "Configuring Your App" and "Configuring Ember CLI" feel like a grab-bag of configurations (prototype extension disabling, URL type, embedding apps, feature flags, and debugging). Is there a reason why these configurations are documented and others aren't? Should there be more guides on specific, widely-used configuration options? Are any of these configuration options not widely-used enough to merit inclusion in the Guides (like "URL type" - do more than a handful of Ember devs use `hash`? is the documentation of `none` in "embedding apps"?)? Are the debugging config options actually used much now that Ember Inspector is so well-developed?

**Comment by locks** [comment]
This will probably be revised when we do a more thorough read through.
