### ISSUE TITLE
Expand coverage of applications and their lifecycles

### ISSUE THREAD

**Issue by dgeb** [emberjs/guides#827]
While working on #789, I've come to realize that the entire "Services and Initializers" section needs a refresh.

I propose that we expand this section to cover applications, application instances, registrations (via `RegistryProxy` methods) as well as lookups (via `ContainerProxy` methods).

This whole section should probably be titled something like "Application Lifecycle" or simply "Applications" with subsections such as:

* Applications and instances
* Registrations and lookups
* Initializers [covering both application and instance initializers]
* Services

Open to suggestions here. I will do what's needed to launch the registry / container reform this week, but I also feel that much of this is needed to put the changes in the proper context.

**Comment by dgeb** [comment]
And of course this area of the guides is also directly related to the [engines](https://github.com/emberjs/rfcs/pull/10) work I'm starting.

**Comment by michaelrkn** [comment]
This sounds great!

**Comment by michaelrkn** [comment]
I like "Application Lifecycle" - @locks what do you think? Let's settle on it before 2.1 Guides are released so we don't bork version switching when 2.2 come out.

**Comment by dgeb** [comment]
> I like "Application Lifecycle"

I've been working on this a bit today and came up with "Application Concerns" as an alternative umbrella term. I thought this might be more inclusive of Services (although it's arguable that Services should just be moved into a separate section instead).

**Comment by michaelrkn** [comment]
Yeah, and "lifecycle" implies death of applications too ;) I don't know about "concerns"... I don't have super strong feelings though.

**Comment by dgeb** [comment]
Hmmm ... I share your concerns about "concerns". It's rather generic, but this is a grab bag of application-related topics after all. I suppose I could just use `/applications/` as the URL slug to start and then we could change the title text to anything application-related later.

**Comment by michaelrkn** [comment]
Good thinking on the slug!
