### ISSUE TITLE
Broken link: Defining a Model

### ISSUE THREAD

**Issue by jaydson** [emberjs/guides#837]
In the page `Using Fixtures` (http://guides.emberjs.com/v1.10.0/models/the-fixture-adapter/) the section `Define Your Model` have a broken link.

> You should refer to Defining a Model for a more in-depth guide...

`Defning a Model` is pointing to http://guides.emberjs.com/guides/models/defining-models (404 error), but te correct link should be http://guides.emberjs.com/v1.10.0/models/defining-models/

**Comment by michaelrkn** [comment]
Thanks for reporting! Unfortunately, because of the amount of work required, old versions of Guides aren't maintained. You should use the latest: guides.emberjs.com/v2.0.0/.
