### ISSUE TITLE
Document how to handle empty JSON response

### ISSUE THREAD

**Issue by mike-post** [emberjs/guides#838]
Using ember-data, if you receive an empty response (such as if you're dealing with a dumb API which returns just an HTTP status code upon success), the proper way to handle it is by having your API return an HTTP 204. (Returning a 200 with no response gives you a JSON.parse() exception.) It took me forever to find this information so I'm thinking it's a good candidate for somewhere in the guide.

**Comment by michaelrkn** [comment]
This feels like a corner case that affects a small minority of users and is probably better suited for the API docs or a blog post.

**Comment by mike-post** [comment]
Are the cookbooks coming back? I figured it was a candidate for that section.

**Comment by locks** [comment]
Cookbooks were handed to the community, currently at http://emberwatch.com/cookbook.html
