### ISSUE TITLE
Update component actions

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#853]
Several items didn't get addressed in #834. We should add in this content:

- [x] Threading actions through multiple layers of components
- [x] Passing arguments
- [x] Argument currying
- [x] Return values
- [x] `target`?
- [x] `value`?
- [ ] Bubbling to routes?

**Comment by szines** [comment]
We suggest more places in the guide, that a special event name should use dasherized version. A code snippet for example:

http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_specifying-dom-event-type
```
<div {{action "anActionName" on="double-click"}}>
  click me
</div>
```

My experience that this feature works only if we use the original camelCase version. Should we update these sections or it is already updated just not released yet?

This instruction is misleading as well.
http://guides.emberjs.com/v2.1.0/templates/actions/#toc_specifying-the-type-of-event

"You should use the dasherized event names, so two-word names like keypress become key-press."

I'm happy to give a hand if it haven't updated yet.

**Comment by acorncom** [comment]
Here's a Twiddle demo showing the problem:

https://ember-twiddle.com/ee3626653d2777a75678

**Comment by michaelrkn** [comment]
@szines thanks for reporting this! If you can open a PR on the Guides and the API docs to fix this that would be awesome.

**Comment by szines** [comment]
@michaelrkn I opened a PR on the Guides. Hope it is fine. Let me know if it should improve further.

I feel, there could be a little confusion, because in the following case, we have to use the dasherized even name: http://guides.emberjs.com/v2.1.0/templates/input-helpers/#toc_actions

**Comment by michaelrkn** [comment]
@szines Hrm, perhaps. I'm not sure what to do about it. We could add a note to the Input Helpers guide just saying that it's different than the `action` helper syntax.

**Comment by toddjordan** [comment]
@michaelrkn I'll spend some time rounding out component actions over the next week or two

**Comment by michaelrkn** [comment]
@toddjordan hooray!

**Comment by jdmarshall** [comment]
The section on bubbling is inaccurate at least in 1.13 and beyond.  You have to have an action on the component or you get an error.  It implies a default behavior you should rely on but that behavior no longer exists, and it provided no alternative.

I'm trying to have one component that has a list of items to select and another that displays the currently selected item, and the guides provide no leads on how that might be accomplished.

**Comment by michaelrkn** [comment]
@jdmarshall The section on bubbling has [been removed](https://guides.emberjs.com/v2.2.0/templates/actions/). There's [no attempt is made to update content, layout, or styles for older versions](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md). I'm not sure what you mean by "it implies a default behavior"; it would help the discussion if you could be a bit more specific.

**Comment by toddjordan** [comment]
ok, back around to looking at this...  I'm willing to take it on but gonna need some more information on these items.  Will do some research, but any further explanations on what the items in the above list mean (or links!) would be helpful.  

I assume return values means returning things like promises from closure actions, so the component can handle conclusions to synchronous calls.

Does passing arguments mean passing args to closure actions?

is `value` meaning the value attribute on the attrs object?  If so, I was under the impression we weren't ready to document attrs yet.

cc @mixonic @tomdale

**Comment by toddjordan** [comment]
ok, found some information on `target` and `value` here: http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_closure-actions  I believe there are also some tests exercising it in source

**Comment by toddjordan** [comment]
I also think I get the curry behavior as well from the same link in my last comment.  I'll start on this by creating a running example of these

**Comment by toddjordan** [comment]
Once this PR #1148 gets merged we can check off all but "Threading actions through multiple layers.." and "Bubbling to routes".  I'll work on those next.

**Comment by toddjordan** [comment]
All the checkboxes in the original issue are addressed by PRs, except "Bubbling to routes".  Does this need an example in the guide?
