### ISSUE TITLE
Explain the difference between running your tests via ember server and ember test --server

### ISSUE THREAD

**Issue by toddjordan** [emberjs/guides#857]
Interesting discussion in the Slack testing channel today where I learned that running your tests through ember server (via localhost:4200/tests)  could give you different results then running them through ember test --server.  

Really the difference comes down to `ember server` runs in `environment=development`, while running via `ember test --server` runs in `environment=test`.  This can have runtime ramifications, especially if you load some libraries only in test mode.

There's already a blurb about being able to run with /tests in the testing guide intro.  We just need to elaborate a bit to let people know the difference and to steer them towards using ember test.

I'll work on a PR to accompany this...

**Comment by michaelrkn** [comment]
:+1: thanks @toddjordan!!!

**Comment by pixelhandler** [comment]
@toddjordan yeah cool perhaps create a PR on the ember-cli project gh-pages branch to indicate the use of /tests and how that is representative of your dev env vs ember t -s uses test env.

**Comment by toddjordan** [comment]
@pixelhandler will do both
