### ISSUE TITLE
Document all available config options for .ember-cli

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/guides#858]
There really isn't any place to see all of the options that can be specified in `.ember-cli` and I've seen people ask about it a lot.

I would make  PR instead of just this issue but I must first figure out what they are :smile: This is a reminder.

- `disableAnalytics`
- `usePods`
- `proxy`

If anybody knows any that are missing off the top of their head, please comment here.

**Comment by locks** [comment]
I personally don't want to document pod usage until the final structure is here.
The other PRs are welcome ;)

**Comment by michaelrkn** [comment]
@HeroicEric this ties in with #823 - do you think you could look into the issues brought up there while you're at it?

**Comment by josenberg** [comment]
From [Ember-cli Docs](http://www.ember-cli.com/#runtime-configuration).

```
"skipGit" : true,
"port" : 999,
"host" : "0.1.0.1",
"liveReload" : true,
"environment" : "mock-development",
"checkForUpdates" : false
```

**Comment by Lxrd-AJ** [comment]
In addition to what @josenberg wrote
```
"output-path": "dist/"
```

**Comment by Lxrd-AJ** [comment]
Can we also include config options for `config/environment.js` @michaelrkn

**Comment by michaelrkn** [comment]
@Lxrd-AJ I think we should have one page for Ember CLI, and another page (or pages) for other configuration options. This issue is in particular for Ember CLI, but I've also opened #823 for documenting configuration more generally.

**Comment by locks** [comment]
@HeroicEric @josenberg @Lxrd-AJ could one of you send a PR so it can get reviewed and merged? thanks!
