### ISSUE TITLE
Add section about get and mut helpers on input helpers

### ISSUE THREAD

**Issue by Panman8201** [emberjs/guides#861]
Just had a [discussion](https://embercommunity.slack.com/archives/needhelp/p1444223216002500) with @rwjblue and @kamilbiela on the Slack channel about using the `(get)` helper with an `{{input}}` helper and requiring the `(mut)` helper to enable two way binding. Although there is an example in the [API docs](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_get), I think it would be helpful to make note of this situation in the guides, such as on the [Input Helpers page](http://guides.emberjs.com/v2.1.0/templates/input-helpers/). If I get some spare time, I could write a quick PR to add a mention, but wanted to add a note here before I forgot.

**Comment by locks** [comment]
Reference: https://github.com/emberjs/guides/pull/438 https://github.com/emberjs/guides/pull/594

**Comment by rwjblue** [comment]
I agree with #594 (`get` helper shouldn't have its own section for sure), but this technique of using `{{input value=(mut (get model.foo somePropOnFoo))}}` should be documented with the input helper (tiny blurb is totally fine).

We can also reference the API docs on `(get` [here](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_get) which shows the usage with `{{input}}`.

**Comment by michaelrkn** [comment]
@mixonic did a nice revamp of the [conditionals](http://guides.emberjs.com/v2.1.0/templates/conditionals/) page that explains all three ways of invoking a helper, included nested invocation.

Maybe we should rename that page "Conditionals and Helper Forms" or something to make it clear that it also gives the high-level overview?
