### ISSUE TITLE
Broken markdown syntax in Component page.

### ISSUE THREAD

**Issue by ChangJoo-Park** [emberjs/guides#863]
I have seen [defining-a-component](http://guides.emberjs.com/v2.1.0/components/defining-a-component/) page. 

I found `app/routes/index.js` source syntax highlighting was broken.
`Given the above template, you can now use the {{blog-post}} component:`
below this line, you will see exposed markdown syntax.

```app/routes/index.js
export default Ember.Route.extend({
  model() {
    return this.store.findAll('post');
  }
});

**Comment by locks** [comment]
Thanks for reporting, this is already fixed in master by https://github.com/emberjs/guides/pull/856.
