### ISSUE TITLE
Search feature shows broken links

### ISSUE THREAD

**Issue by pythonquick** [emberjs/guides#864]
Some search results on the guides result in broken links (HTTP 404).

Here's how to reproduce:

1. Visit the Guides page for version 1.13.0: http://guides.emberjs.com/v1.13.0/
2. Type "Setting up a Controller" into the search box (without the quotes)
3. Do NOT select the suggestion; just hit Enter to go to the search results page
4. A page with search results appears. Click the top link titled "SETTING UP A CONTROLLER"
5. A 404 error appears when the browser attempts to load the page with URL http://guides.emberjs.com/routing/setting-up-a-controller

There are similar broken links on the guide pages for other Ember versions

**Comment by michaelrkn** [comment]
Thanks for the heads up! This is a dup of #514, which was mistakenly closed.
