### ISSUE TITLE
Document component events

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#865]
We should add a page that documents component events, like `didInsertElement`.

**Comment by locks** [comment]
mupkoo [2:56 AM] 
Guys, why `didInitAttrs` and family are not documented?

rwjblue [2:57 AM] 
@mupkoo: because the hooks are not 100% finalized

rwjblue [2:58 AM]
@mupkoo: they will be documented as part of angle bracket components

**Comment by michaelrkn** [comment]
@locks not glimmer component events, [classical component events](http://emberjs.com/api/classes/Ember.Component.html).

**Comment by grapho** [comment]
I will volunteer some time to integrate dome data from the initial blog post into a guides section..

Im thinking a section titled "The Component Lifecycle"

**Comment by michaelrkn** [comment]
@grapho awesome! Am I understanding you correctly that you already have a blog post on this? If so, can you share it here?

**Comment by grapho** [comment]
grapho dont blog.

I was refering to the emberjs/bog that most ppl refer to for info

**Comment by michaelrkn** [comment]
If you're referring to [this post](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html), keep in mind that most of those hooks are for Glimmer Components, not classical components. This issue is only to document classical component events (see the [API docs](http://emberjs.com/api/classes/Ember.Component.html)). 

Also, for new contributors, we recommend starting with a blog post or other writeup before opening a pull request for a larger chunk of content like this, since the feedback cycle can take a while.

**Comment by grapho** [comment]
@michaelrkn  duly noted. the section will focus on the basic ones for now

**Comment by grapho** [comment]
@michaelrkn

https://github.com/emberjs/guides/pull/902

I am working on the dialog to make it more use-case oriented for the guides

**Comment by michaelrkn** [comment]
:+1:

**Comment by michaelrkn** [comment]
Closed via #902.
