### ISSUE TITLE
Firebase and Tutorial

### ISSUE THREAD

**Issue by locks** [emberjs/guides#877]
Switch to Mirage, put Firebase and Divshot on an optional "Extra credits" section.

**Comment by acorncom** [comment]
As was being discussed on Slack, another option was to use [LocalStorage](https://github.com/locks/ember-localstorage-adapter).  Per @locks though:

> people confuse the store with LS, not a great testing story, data still local to app

Is Ember-CLI-Mirage the option we want to be blessing as we introduce folks to Ember?  I've been liking it a bunch, but am not on the core team ;-)

**Comment by acorncom** [comment]
**/cc** @samselikoff, an FYI

**Comment by samselikoff** [comment]
Interesting. Fwiw I'm planning on switching the default serializer to JSON API, so it will work with Ember out of the box. This would be in a 1.0 or 2.0 release, not too far away.

I'm also planning on making a screencast for ember-cli-mirage.com's home page, once I finish the serializer + updated factory layer. So, we could also direct users there if we decide to go with something more barebones for the official tutorial. If we do want to use mirage, I'm more than happy to help out any way I can.

**Comment by michaelrkn** [comment]
Another option is to build a very simple Node.js app that users can deploy with a Heroku button. This has the advantage of using the JSON API adapter/serializer, which is the happiest path, and giving people a "real" public site.

I was initially in favor of Firebase, but we've been using it at Epicodus for a while and the adapter has a couple serious problems - you have to [save both sides of each relationship and deleting relationships can be weird](https://github.com/firebase/emberfire/issues/147), and creating a new belongsTo record causes it to show up twice in the store (can't find the issue in 30 seconds of looking).

**Comment by benoittgt** [comment]
ember-cli-mirage should be something great but maybe too powerful to start, specially with JSON API. 

On the documentation of Mirage you can read 
> For now, mocking a JSON:API backend with Mirage requires a bit more work, but soon the serializer layer and updated shorthands will make things much simpler.

But @samselikoff should know more on this subject than I. 

I think we just have to use the simpliest and the more 'local'.

**Comment by samselikoff** [comment]
I actually just merged the [JSON:API serializer](https://github.com/samselikoff/ember-cli-mirage/commit/9927a7f7a2232ddf8df15e01991e538eefadee9c) last night, so this will be ready + documented soon; though, it does add a bit more mental complexity, since you'll need a model/serializer definition in mirage, too.

Maybe there's a blueprint that could help out here.

**Comment by michaelrkn** [comment]
The tutorial branch is now updated with Mirage.
