### ISSUE TITLE
Migrate from Divshot to Firebase

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#878]
Looks like Divshot is joining Firebase (http://docs.divshot.com/migrate), does this affect guides deployments in any way?

**Comment by acorncom** [comment]
Per the Divshot website

> Divshot Hosting will wind down operation on December 14, 2015. The good news is Firebase Hosting is closely compatible with Divshot hosting and we've made it easy to transition your Divshot apps!

**Comment by locks** [comment]
> does this affect guides deployments in any way?

Yes, guides are deployed to Divshot.

**Comment by acorncom** [comment]
From their write-up, it sounded like the deploy process might be fairly similar, so wasn't sure if we would need to do a lot of work on updating deployment infrastructure ...

**Comment by Dundonian** [comment]
If you end up deciding to look elsewhere for hosting your guides, we'd ([Aerobatic](http://aerobatic.com)) be happy to host you for free, if you don't mind using our Bitbucket add-on for now. The Bitbucket add-on uses our latest hosting platform which we open-sourced under the [4front](http://4front.io/) project. Our old [yoke-cli](https://www.npmjs.com/package/yoke-cli) is using an older version of the platform but is still functional. Happy to field any questions anyone may have. Thanks.

**Comment by michaelrkn** [comment]
Thanks @Dundonian!

**Comment by michaelrkn** [comment]
Update: the plan is to simultaneously deploy to Divshot and Firebase for 2.2, and then try to switch to Firebase and see how it goes. This seems the simplest path for the moment, and will provide an easy fallback if something goes wrong.

**Comment by nahtnam** [comment]
There is also https://www.pagefronthq.com/ which is also very similar to divshot.

**Comment by michaelrkn** [comment]
I've done a deployment of the Guides to https://ember-guides.firebaseapp.com/. I've gone through and it seems to work just fine. I did get this message during the migration:

```
⚠ Warning: The following incompatible features were detected.
- clean_urls support is planned for Firebase Hosting, but is not yet available
```

But I don't actually see any problems.

@rwjblue I've invited you to the app, since I think you know something about the emberjs.com DNS and what needs to happen there. Let me know if there's anything I can do to help with that.

We will need to pay $5/month to have custom DNS. If that's a dealbreaker, let me know and we can try something else out.

**Comment by wifelette** [comment]
Is anyone particularly connected to the Firebase folk? Or is there someone @sararob could perhaps introduce us to?

@michaelrkn I'll ping you RE: DNS.

**Comment by michaelrkn** [comment]
@wifelette @tomdale Divshot shuts down in 4 days. How are things going with making the switch?

**Comment by acorncom** [comment]
Just got an email from Divshot stating that we've actually got until December 22nd.  So we have a bit more time (but I'm planning on being out of the office by that point ;-)

**Comment by wifelette** [comment]
The Firebase plan has been comped and set up (with the $49 plan, thanks Firebase!). 

I added the requested TXT records to the DNS for verification and it was successful. So we _should_ be basically set up. The custom domain is also set up for https://guides.emberjs.com.

Anything else I need to be doing for this?

**Comment by michaelrkn** [comment]
@wifelette It looks like we have to wait 24 hours for SSL to finish provisioning (it says they will email you when it completes). Then you can follow the directions at https://ember-guides.firebaseio.com/?page=Hosting# for setting up the CNAME record.

**Comment by wifelette** [comment]
Ah, not quite yet. We're set up and verified, but waiting for SSL to be provisioned ("This process can take up to 24 hours."). Once THAT happens, I can do the final DNS setup :)

**Comment by wifelette** [comment]
@michaelrkn Heh, yep. I'm right there with you. Only slower... ;)

**Comment by michaelrkn** [comment]
:ship: :night:

**Comment by wifelette** [comment]
Got the email that SSL is ready, updated the DNS.

_Now_ we should be good to go :)

**Comment by michaelrkn** [comment]
It's alive and working! I'll update the deploy instructions.

**Comment by michaelrkn** [comment]
@wifelette Can you create a new Firebase app called ember-guides-staging and add me as a collaborator?

**Comment by wifelette** [comment]
Done. Note: from my limited poking around, it looks like payments are pre _app_ not per _account_, so this will be on the free tier. Will that work for our purposes?

**Comment by rtablada** [comment]
![It's alive!](http://www.riotgames.com/sites/default/files/Alive.gif)

**Comment by michaelrkn** [comment]
@wifelette yup!
