### ISSUE TITLE
Markdown parser combines two consecutive code blocks into one

### ISSUE THREAD

**Issue by mshindal** [emberjs/guides#885]
Or at least I'm pretty sure that's what's happening. Go to http://guides.emberjs.com/v2.1.0/components/defining-a-component/ and look at the second block of code: it's actually supposed to be two separate blocks of code, but the markdown parser combined it into one.

**Comment by michaelrkn** [comment]
Thanks for catching this!

**Comment by mshindal** [comment]
Made a PR that just adds some extra text in between the two code blocks so that it doesn't render incorrectly.

**Comment by locks** [comment]
This is already fixed in master, it was a missing code fence, not the parser combining samples: https://github.com/emberjs/guides/pull/856.
