### ISSUE TITLE
Add API links throughout Guides

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#887]
Someone should go through all of the Guides and add links to the API docs, following the format at the bottom of the [contributing guidelines](https://github.com/emberjs/guides/blob/master/CONTRIBUTING.md).

**Comment by locks** [comment]
@acorncom

**Comment by acorncom** [comment]
I would suggest we break things up by major section of the guides and have people take them in chunks as desired.  In addition, I was trying to link the first mention of a new concept to the API guides, but in a paragraph where it gets mention 2 or 3 times, it seems redundant to link every single time ...

- [ ] Getting Started
- [ ] The Object Model
- [ ] Routing
- [ ] Templates
- [ ] Components
- [ ] Controllers
- [x] Models (I've already done this one)
- [ ] Application Concerns
- [ ] Testing
- [x] Ember Inspector (done as well)
- [ ] Addons and Dependencies
- [ ] Configuring Ember.js
- [ ] Contributing to Ember.JS

**Comment by acorncom** [comment]
I'm going to recommend skipping linking to APIs on the Controllers pages, as they link to older docs that reference Controllers and Views.

**Comment by acorncom** [comment]
Everything else here is up for grabs.  I'm going to work away on this as I have time, but would love to get help! ;-)

**Comment by acorncom** [comment]
@michaelrkn @locks We're finally finished here.  Can we get this pushed up to the live site, I'd love to see it in action ;-)

**Comment by locks** [comment]
:computer: says :no_entry:

**Comment by michaelrkn** [comment]
@acorncom you are a true hero!!!
