### ISSUE TITLE
Add a note about the `ember-cli-deprecation-workflow` to the site

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#889]
Under `Configuring Ember.js` -> `Debugging`, seems like it would be well worth mentioning https://github.com/mixonic/ember-cli-deprecation-workflow

**Comment by michaelrkn** [comment]
I'm not sure debugging is the right place for this; maybe it deserves its own page?

**Comment by acorncom** [comment]
Not sure about the placement either, just thought it'd be good to have that recommendation documented somewhere ...

**Comment by derekbassett** [comment]
I agree with adding this to the Deprecation page would be a great way to communicate this tool to the community.

**Comment by mixonic** [comment]
Somewhere we should document the conventional process to upgrade an app to a new version of Ember.

**Comment by derekbassett** [comment]
:+1:

**Comment by acorncom** [comment]
Seems to be dependent on https://github.com/emberjs/guides/issues/639

**Comment by michaelrkn** [comment]
Personally I don't want #639 to hold anything up. I am in favor of incremental change to the Guides until there is some major pressing need to force us to make a big change. Big changes are costly to implement and even more costly in the time to reach consensus.

I think this could be included under Configuring or in the Getting Started tutorial.

**Comment by locks** [comment]
#639 is an "idea" issue.

**Comment by SaladFork** [comment]
It should take into account the [existing guide under Ember Inspector that covers handling deprecations](http://guides.emberjs.com/v2.1.0/ember-inspector/deprecations/). We may also want to mention [ember-cli-template-lint](https://github.com/rwjblue/ember-cli-template-lint).

**Comment by toddjordan** [comment]
I've been working through this for my team's large application moving from 1.13 to 2.0, using the deprecation-workflow, template-lint, and deprecation handlers polyfill addons.  I could take a stab at writing something up this week, that would also include the existing inspector doc.  I was in process of writing all this up for a blog post anyways.

**Comment by acorncom** [comment]
@toddjordan :+1:

**Comment by michaelrkn** [comment]
@toddjordan that would be awesome!

**Comment by toddjordan** [comment]
Should have a first draft PR, by end of day.  Just adding some screen shots/code snippets...
