### ISSUE TITLE
Observer doesn't fire in`Getting started / Observers` 

### ISSUE THREAD

**Issue by ryrych** [emberjs/guides#893]
I tried to run the [first example](http://guides.emberjs.com/v2.1.0/object-model/observers/) both with Chrome snippet and 'regular' console, but every time I change `firstName` or `lastName` the `fullNameChanged` doesn't fire:

```
  fullNameChanged: Ember.observer('fullName', function() {
    // deal with the change
    console.log('fullName changed to', this.get('fullName'));
  })
```

**Comment by acorncom** [comment]
@ryrych Further down the page, it mentions

> If you never get a computed property, its observers will not fire even if its dependent keys change. You can think of the value changing from one unknown value to another.

Does that fix your issue?  Might be worth asking on Stackoverflow unless you're sure this is a bug in Ember / guides
