### ISSUE TITLE
Doc how and where to specify inflectors for pluralization of adapters

### ISSUE THREAD

**Issue by EricSchank** [emberjs/guides#898]
Currently the model guide is vague on where or how to handle non-standard pluralization.

**Comment by grapho** [comment]
I think
http://guides.emberjs.com/v2.1.0/models/customizing-adapters/#toc_path-customization
and
http://guides.emberjs.com/v2.1.0/models/customizing-adapters/#toc_pluralization-customization
cover most usecases.

Is there something missing from these examples that dont cover your use case?

**Comment by michaelrkn** [comment]
@grapho those guides show the code to use, but not where to put it. See #899.
