### ISSUE TITLE
phantomjs2 install step fails on debian/ubuntu

### ISSUE THREAD

**Issue by rnsloan** [emberjs/guides#907]
From this install step: http://guides.emberjs.com/v2.1.0/getting-started/#toc_installation

The binary it tries to download does not exist: https://github.com/zeevl/phantomjs2/pull/3 the repo and npm package have not been updated in 4 months.

Happy to create a PR to amend the docs if given direction on what amendments to make.

**Comment by rnsloan** [comment]
This phantomjs PR contains a list of binaries people have built for various linux distributions https://github.com/ariya/phantomjs/issues/1294 .

**Comment by michaelrkn** [comment]
Hrm, I hate to have to change our docs because of a temporary situation where somebody isn't updating the NPM package for one platform. I don't know anything about that situation - is there any chance of it being resolved any time soon?

@rnsloan that issue you linked to gives a 404 - can you double-check the link?

**Comment by rnsloan** [comment]
Updated the issue link that was giving a 404.

Fine for no change to be made to the doc, just letting you know that the npm package `phantomjs2` has not been updated in 11 months; the github repo in 4 months; and, as of at least some point in September going by a [stackoverflow comment](http://stackoverflow.com/questions/30084690/how-to-install-phantomjs-v2-with-npm#comment-53353397), the package will fail to work on debian/ubuntu systems because the phantomjs binary it tries to download returns a 404.

The `phantomjs` package [maintained by Medium](https://github.com/Medium/phantomjs) only has an alpha release of phantomjs2 available

@michaelrkn

**Comment by michaelrkn** [comment]
Maybe we should encourage installing phantomjs through the OS's package manager instead? Is that in a better state?

**Comment by locks** [comment]
Can we punt that to phantomjs' documentation?

**Comment by michaelrkn** [comment]
That seems ideal, if we can link somewhere that phantomjs keeps updated with installation instructions. @rnsloan do you know of any such resource?

**Comment by rnsloan** [comment]
@michaelrkn From memory, using the OS's package manager for Ubuntu is not advisable as it is out-of-date.

Linking to PhantomJS's documentation is a better step http://phantomjs.org/download.html

if `npm -g phantomjs2

**Comment by michaelrkn** [comment]
@rnsloan Good idea. Opened #910.
