### ISSUE TITLE
Add examples of ember-test-helpers `wait` helper.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/guides#909]
This was added in https://github.com/switchfly/ember-test-helpers/pull/112 (and is available in ember-qunit 0.4.13 and higher).  The largest benefit here is the ability to wait for pending async in your component integration tests.  

Example from the above PR (assumes the component does some async in an action triggered by the button click):

```js
import { moduleForComponent, test } from 'ember-test-helpers';
import wait from 'ember-test-helpers/wait';

test('it works when async exists in an event/action', function(assert) {
  this.render('{{my-foo}}');

  this.$('button').click();

  return wait()
    .then(() => {
      // assertions for after async behavior
    });
});
```

**Comment by toddjordan** [comment]
cool, I'd be happy to get something in there :+1:

**Comment by michaelrkn** [comment]
@toddjordan, Ember Guides testing mastermind :)

**Comment by toddjordan** [comment]
@michaelrkn is it an *evil* mastermind? 😼

**Comment by michaelrkn** [comment]
:scream:

**Comment by locks** [comment]
let's test it and find out!

**Comment by acorncom** [comment]
This issue should be closed
