### ISSUE TITLE
Make sure else if handlebars template expression is noted in the guides

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#932]
Was listening to a talk yesterday and Yehuda mentioned that `{{else if isAdmin}}` is a valid expression in `.hbs` files.  I'd never heard of it before and hadn't seen it in the guides.

It's listed here in the API docs though: http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_if

We should note this on the conditionals page: http://guides.emberjs.com/v2.1.0/templates/conditionals/

**Comment by locks** [comment]
I'm not too bothered if only the API docs mention it, it's usually a crutch that can be better solved some other way

**Comment by acorncom** [comment]
Should we close this then?
