### ISSUE TITLE
Add ability to backport JS

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#934]
@SaladFork and @rwjblue came up with a solution to help us add features to past releases of the Guides:

1. Add a universal JS file to https://github.com/emberjs/guides.emberjs.com/tree/master/snapshots, so that it is available to all versions.
2. Add that universal JS file to the present version of https://github.com/emberjs/guides/, as well as all past versions.
3. In the universal JS, detect what version of the Guides the user is viewing, and if necessary add any features that need to be backported.
4. Use the approach in 3 to backport the version warning code.

@SaladFork are you game to take this on?

**Comment by locks** [comment]
Unless I'm misunderstanding, this is partially implemented.
