### ISSUE TITLE
Mistake on documentation

### ISSUE THREAD

**Issue by ozanmuyes** [emberjs/guides#937]
Hello,

Thanks for the awesome framework. I've been reading the documentation and I found a mistake. In the last topic of the page http://guides.emberjs.com/v2.1.0/object-model/classes-and-instances/ set method referred as accessor, while it's a mutator.

Regards,
Ozan MÜYESSEROĞLU

**Comment by locks** [comment]
Hi @ozanmuyes, this isn't a mistake.
The `get`/`set` pair are called get accessor, and set accessor. You can see the same nomenclature being used in C#: https://msdn.microsoft.com/en-us/library/aa287786(v=vs.71).aspx.

**Comment by ozanmuyes** [comment]
Hi @locks, 

I am truly shocked by your OOP design ancestor preference (for the terminology at least). Sorry for my misunderstanding, I thought you follow Java guidelines. 

Regards, 
Ozan MÜYESSEROĞLU
