### ISSUE TITLE
Update syntax highlighting

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#944]
We currently use a fork of [CodeRay](https://github.com/rubychan/coderay) with support for Handlebars. CodeRay isn't well-maintained and doesn't support ES6. The Ember homepage uses [highlight.js](https://highlightjs.org/) client-side. We should probably switch to highlight.js.

If somebody can investigate this and make sure it's a good idea, and then implement it, that would be awesome!

---

Edit (**@acorncom**): we've got more data on what we're after and we're after a different option now.

We'd like to implement [Prism.js](http://prismjs.com) instead of Highlight.js as discussed below, as it supports [line highlighting](http://prismjs.com/plugins/line-highlight/) and [line numbers](http://prismjs.com/plugins/line-numbers/) as well as ES6, `.scss` and `.hbs` files

Here's what I think we need to do to get this working:
- [ ] Re-implement `_highlight` to produce HTML in a format that Prism.js supports.  [Our current implementation](https://github.com/emberjs/guides/blob/master/lib/highlighter.rb#L15-L30) uses CodeRay but we don't actually need to produce HTML using Coderay at all
- [ ] Setup the use of prism.js in a new JS file that handles things well.  We may want to make this globally available instead of versioned for each version of the guides (let's get this built for one version and then talk about this on a PR ...)
- [ ] Drop the use of the coderay gem (once we're sure we're ready to trash it).  We can't tell dgeb he can delete his fork yet, as `emberjs/website` still depends on it for API doc creation as well

**Comment by acorncom** [comment]
And we may want this to be a universal JS file as mentioned on #934

**Comment by michaelrkn** [comment]
I'm not sure about that. This isn't something we want to backport.

**Comment by dustyburwell** [comment]
I'm not sure how valuable the line numbers in the code formatting are, or if they're ever referenced throughout the rest of the documentation, but I came across this: https://highlightjs.readthedocs.org/en/latest/line-numbers.html

If the line numbers are important to anyone, then highlight.js is clearly not a good choice.

**Comment by dustyburwell** [comment]
@michaelrkn can you elaborate on what features are important/necessary in the code highlighting? From the description above, it sounds like HBS and ES6 support are a must. What else should be considered requirement?

**Comment by acorncom** [comment]
@dustyburwell On my end, I think one of the main "features" we'd be after is to have the plugin keeping fairly up-to-date with Babel features as they start landing.  There are a number of Babel items that Ember is helping lead the charge on, so once something hits about Stage 2, we'll probably start seeing it get adopted by the Ember core team.

**Comment by michaelrkn** [comment]
@dustyburwell line numbers aren't important. HBS and ES6 are... I'm not sure there's anything else we need to keep in mind. Might be worth taking a quick flip through the Guides and see if anything jumps out.

**Comment by jsmestad** [comment]
I'll take a stab at this. Been using highlight.js lately on some other projects.

**Comment by acorncom** [comment]
@jsmestad Cool!  Look forward to seeing it, we've needed it for a while :-)

**Comment by acorncom** [comment]
Just did some initial work on thinking through this, here's what I think we need to do to get this working:

- [ ] Re-implement `_highlight` to produce HTML in a format that highlight.js (or other comparable, well-maintained JS library that supports ES6 and HBS) supports.  [Our current implementation](https://github.com/emberjs/guides/blob/master/lib/highlighter.rb#L15-L30) uses CodeRay but we don't actually need to produce HTML using Coderay at all
- [ ] Setup the use of highlight.js in a new JS file that handles things well.  We may want to make this globally available instead of versioned for each version of the guides (let's get this built for one version and then talk about this on a PR ...)
- [ ] Drop the use of the coderay gem (once we're sure we're ready to trash it).  We can't tell dgeb he can delete his fork yet, as `emberjs/website` still depends on it for API doc creation as well

**Comment by acorncom** [comment]
@jsmestad Think you'd still have time to work on this?

**Comment by jkarsrud** [comment]
Is the idea to use Prism in the browser, or is this something that could be built into the build steps of the website? I like the idea of doing this on the server, as it would only require a tiny bit of extra CSS, and wouldn't require any more JS to be added to the guides at all.

That said, going the client-side route might be easier, as it would only require a small amount of changes to the markup output from `highlighter.rb`, and then Prism would handle the rest.
