### ISSUE TITLE
Tweak the pushing records example for pushPayload

### ISSUE THREAD

**Issue by acorncom** [emberjs/guides#945]
Under Pushing Payloads (http://guides.emberjs.com/v2.1.0/models/pushing-records-into-the-store/#toc_pushing-records) the second example is an example of a JSON-API payload.  It might make more sense to demonstrate a non-JSON API payload in the interests of explaining clearly that the store can handle other payloads and serialize them for the user ...

**Comment by jsangilve** [comment]
I just opened PR #963  to improve that example.The thing is, if you use a non-JSON API payload, the model must use something different from JSONAPISerializer (RESTSerializer) which is the default one since 2.0. So, I've included a simple custom RESTSerializer.
