### ISSUE TITLE
The code provided in the stubbing services section for testing components leads to an error

### ISSUE THREAD

**Issue by faeronsayn** [emberjs/guides#962]
Hi, 
I've noticed that the code provided in the [Stubbing services](http://guides.emberjs.com/v2.1.0/testing/testing-components/#toc_stubbing-services) section leads to the following error: `Uncaught TypeError: this.register is not a function` in the beforeEach block.

**Comment by michaelrkn** [comment]
cc @toddjordan

**Comment by toddjordan** [comment]
I have a working setup of the testing guides example here: https://github.com/toddjordan/ember-testing-guide-examples

Make sure your ember-qunit is up to date (0.4.15)

**Comment by michaelrkn** [comment]
Thanks @toddjordan. I'm going to close this out; @faeronsayn, if you have trouble getting things to work and can put together an Ember fiddle or other example showing the problem, feel free to re-open.

**Comment by faeronsayn** [comment]
Seems to have been the ember-qunit outdated version! Thanks!
