### ISSUE TITLE
ember testing helpers

### ISSUE THREAD

**Issue by faeronsayn** [emberjs/guides#975]
So I see that we have the ember-testing-helpers in v1.10.0 of the ember guides, the helpers are documented pretty well: http://guides.emberjs.com/v1.10.0/testing/test-helpers/

So in v2.1.0 of ember that section disappears from the guides. The test helpers are defined in the Ember Testing module, but I'm unable to use them in a v2.1.0 ember app, don't actually know where I can import them, do they still work or not? If they do, do we actually know where we can import them from?

If they do not work, what are the alternatives for `andThen` and something like `fillIn` that we could document? 

The testing guide also talks about how we can test if actions passed from the outside can be tested when called but doesn't talk about how we would go about testing if internal actions to the component can be tested when they are called. `andThen` would fix this but can't seem to use it.

**Comment by locks** [comment]
They are documented at http://guides.emberjs.com/v2.1.0/testing/acceptance/

**Comment by faeronsayn** [comment]
@locks seems like the helpers come from using the startApp, is it possible to use these helpers in integration tests where startApp isn't used at all in any of the examples (in the guide)
