### ISSUE TITLE
Search links have wrong URL structure

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#976]
1. Visit http://guides.emberjs.com/v2.1.0/.
2. Enter a search term and press Enter.
3. Click a link on the search results.

The URL looks like http://guides.emberjs.com/v2.1.0/v2.1.0/object-model. It should look like http://guides.emberjs.com/v2.1.0/object-model.

I believe the relevant code is in https://github.com/emberjs/guides/blob/master/source/javascripts/app/swiftype.js.erb. If somebody could take a look and try to fix it, that would be awesome!

**Comment by filipecrosk** [comment]
Hi @michaelrkn 
It's my first time here. :) 
I found the problem and how to fix. But I saw that the error change in each version. 
i.e: if you open _v1.13.0_ and search, the links will redirect to something like this: http://guides.emberjs.com/ember-inspector/routes (without **/version**).
And for versions _1.10.0_ and _1.11.0_ the modal doesn't open.

Could you help me to understand how this site works? When someone select a different version we load the code from other branch?

**Comment by locks** [comment]
@filipecrosk each version of the guides is a separate site, see https://github.com/emberjs/guides.emberjs.com/tree/master/snapshots, hence the different errors!

**Comment by filipecrosk** [comment]
Thanks @locks 
So how to fix this issue for each version?

**Comment by locks** [comment]
You don't :P

**Comment by michaelrkn** [comment]
@filipecrosk Thanks for getting involved! You're right, there are two different bugs. In 2.x guides, the version is added twice. In 1.x guides, the version isn't added at all. (On average, we got it right!) To start, only worry about fixing the 2.x guides - we can redeploy 2.1 and 2.2, and probably easily backport to 2.0. For earlier versions, we can fix them as @locks alluded to, using the approach outlined in #934.

**Comment by michaelrkn** [comment]
This is actually fixed on master and 2.2. I'm closing this in favor of #934.
