### ISSUE TITLE
Add Ember.getOwner section to Factory Lookup section.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/guides#982]
http://guides.emberjs.com/v2.1.0/applications/dependency-injection/#toc_factory-lookups

In the 2.3 guides we should also explain how to use `Ember.getOwner` to do the same things from within an instance of a class that was instantiated by the container.  See the [deprecation guide entry](http://emberjs.com/deprecations/v2.x/#toc_injected-container-access) for a few more details.

**Comment by tomdale** [comment]
@mixonic Is this something you can tackle?

**Comment by mixonic** [comment]
I'm feeling fairly swamped by getting the actions/events stuff fixed up, sorry. Will keep it in mind though.

**Comment by mitchlloyd** [comment]
I just started using this API in an addon and I'm excited about it. I can take a shot at it today.

**Comment by rwjblue** [comment]
Awesome! Thank you!
