### ISSUE TITLE
binding element class names with conditional example

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/guides#995]
An example appears in the 1.13 docs [here](http://guides.emberjs.com/v1.13.0/templates/binding-element-class-names/#toc_conditional-values)

but beyond that version an example of binding class name with conditionals is gone [see here](http://guides.emberjs.com/v2.0.0/templates/binding-element-attributes/)

**Comment by robbiespeed** [comment]
+1

**Comment by michaelrkn** [comment]
Conditionals have their [own guide](http://guides.emberjs.com/v2.2.0/templates/conditionals/). Class names are strings, just like the examples in the conditionals guide.

**Comment by Frozenfire92** [comment]
Good call, don't know how I missed that, sorry!

**Comment by michaelrkn** [comment]
No worries!
